### PR TITLE
Extracting AuthorityKeyID fields and SubjectKeyID from the X509 V3 extensions fields and storing it in the certificate structure

### PR DESCRIPTION
**Pull request by tothg001**
`Signed-off-by:` toth92g@gmail.com

## Description
X509 defines Subject Key Identifier and Authority Key Identifier fields under V3 extensions, but the current implementation does not collect these data. I made some changes to extract these information and provide it through new elements of the certificate structure.

## Status
Waiting for review

## Requires Backporting
NO

## Migrations
NO

## Additional comments
None

## Steps to test or reproduce
Can be tested with certifiactes which have the two mentioned fields (Authority Key Identifier has 3 subfields, so any combination of them, but only one of each in defined order based on X509)

### CODE REVIEW

**Comment by tothg001** [comment]
Hello Guys!

I am trying to find a memory leakage issue. As I know ssl-opt.sh script should do it with "-m" switch, but unfortunately the .sh scripts are just flashing and dying in a few seconds without any useful message. What prerequisites should I meet to run them?
I have Python2, Perl, MinGW64 (with gcc) all in the PATH. Can compile and run the tests (make tests). I think I forgot to install or set something.

Thank you!

**Comment by mpg** [comment]
Hi @tothg001 and thanks for your contribution! As discussed on the mailing-list, here are some details on the test that are failing on the CI.

- `all.sh` components `test_depends_hashes`, `test_depends_hashes_psa`, `test_depends_pkalgs`, and `test_depends_pkalgs_psa` fail in `test_suite_x509parse`. This means at least one test case is missing at least one dependency declaration. The failures I saw concerned SHA-1 and RSA, but there might be others. Note that in that case, `all.sh` is just a wrapper, the actual tests are Perl scripts `tests/scripts/depends-hashes.pl` and `tests/scripts/depends-pkalgs.pl` which may or may not work on Windows. If they don't, it's probably possible to reproduce the logic by hand: open `include/mbedtls/config.h`, comment out a hash or PK alg, try to build and run the test suite, see if anything breaks.
- `all.sh` component `test_memory_buffer_allocator` -> this seems unrelated an might be a spurious failure, I'd recommend ignoring it for now and checking its status in the next run.
- the API-ABI reports that the `mbedtls_x509_crt` structure was modified, which changes the library's ABI. This is expected for this kind of feature, so not a problem.

**Comment by mpg** [comment]
I just did a high-level pre-review of the PR (not looking at the code yet, just the structure, tests, etc.) and here are some notes:

- There are many commits that github sees as being in your PR which logically are not, at some point you should fix that in the history (I think `git rebase -i` is probably the right tool here). (Note: this might also increase the chances of someone picking up your PR for review - currently the github stats make it look bigger than it is.)
- I assume that was already part of your plans, but just because explicit is better than implicit: before we review, it would be nice to purge the history from commits such as "Debugging" (again `git rebase -i` seems appropriate).
- And also to be clear: _after_ we started reviewing for real (this pre-review doesn't count) please refrain from rewriting the history, and if you want to do so please check with the active reviewer(s) first (but for now you can rewrite the history without notice, that's just once we started reviewing).
- Thanks for adding test certificates. Please document how they were generated by adding rules to `tests/data_files/Makefile`. The rules don't need to re-generate the exact same certs (for example dates or random data might be different) but at least certs that exercise the same features. This is to make sure that in the future, if we need to re-generate those certificates (for example because they expired in the meantime) or variants of them, we know how to do so.
- Just a tip which may or may not be useful: when you get to evaluating coverage of the new parsing functions you added, you might find that it's a bit hard to cover all case of errors with certificate files. For this we have the test function `x509parse_crt` to which you can pass arbitrary data in hex. We normally start from a valid structure and them modify it by hand in order to introduce errors of our choice. I find the ASN.1 decoder at https://lapo.it/asn1js/ very helpful for this kind of thing. Producing hex data with the right error in the right place can be a bit tedious (as you often have to update lengths in enclosing structures), but for now it's usually our best chance to cover all the failing cases of parsing functions.
- Finally, please add a ChangeLog entry, see `ChangeLog.d/00README` for instructions.

**Comment by tothg001** [comment]
Hello Manuel!

 I will work on fixing each of these. I injected errors into the
certificate by hand based on the hex values. Whish I know this link
earlier... :) I am creating a Debian boot pendrive right now, I hope I will
be able to run coverage check on that. When I have corrected everything and
covered the new features I am planning to create a brand new branch and
pull request, because as you said, there are not many real changes, but the
current PR went out of my hand a bit, while trying to debug. It is easier
like this than trying to clean it up (or at least for me).

Thank you for your findings, will do my best :)

BR,
Gábor

Manuel Pégourié-Gonnard <notifications@github.com> ezt írta (időpont: 2021.
febr. 12., P, 9:59):

**Comment by tothg001** [comment]
Hello Manuel!

I have create a linux VM as you advised and was able torun the test perl
scripts resulting in partial success :) Let me  react to your last e-mails
with *blue* and provide some new questions with *green*:




   - all.sh components test_depends_hashes, test_depends_hashes_psa,
   test_depends_pkalgs, and test_depends_pkalgs_psa fail in
   test_suite_x509parse. This means at least one test case is missing at least
   one dependency declaration. The failures I saw concerned SHA-1 and RSA, but
   there might be others. Note that in that case, all.sh is just a wrapper,
   the actual tests are Perl scripts tests/scripts/depends-hashes.pl and
   tests/scripts/depends-pkalgs.pl which may or may not work on Windows. If
   they don't, it's probably possible to reproduce the logic by hand: open
   include/mbedtls/config.h, comment out a hash or PK alg, try to build and
   run the test suite, see if anything breaks. *Solved*
   - all.sh component test_memory_buffer_allocator -> this seems unrelated
   an might be a spurious failure, I'd recommend ignoring it for now and
   checking its status in the next run. *This issue seems to be static. I
   was not able to reproduce it locally so I have no idea how to start
   searching for the cause. Do you have any idea how to find out the source of
   the issue? *
   - the API-ABI reports that the mbedtls_x509_crt structure was modified,
   which changes the library's ABI. This is expected for this kind of feature,
   so not a problem.  *Disappeared*
   - There are many commits that github sees as being in your PR which
   logically are not, at some point you should fix that in the history (I
   think git rebase -i is probably the right tool here). (Note: this might
   also increase the chances of someone picking up your PR for review -
   currently the github stats make it look bigger than it is.)  *Solved: I
   have created a brand new PR...the previous one was a bit "fcked up" after I
   commited from Linux VM and was not able to correct it.*
   - I assume that was already part of your plans, but just because
   explicit is better than implicit: before we review, it would be nice to
   purge the history from commits such as "Debugging" (again git rebase -i
   seems appropriate).  *Solved *
   - And also to be clear: after we started reviewing for real (this
   pre-review doesn't count) please refrain from rewriting the history, and if
   you want to do so please check with the active reviewer(s) first (but for
   now you can rewrite the history without notice, that's just once we started
   reviewing). *Of course*
   - Thanks for adding test certificates. Please document how they were
   generated by adding rules to tests/data_files/Makefile. The rules don't
   need to re-generate the exact same certs (for example dates or random data
   might be different) but at least certs that exercise the same features.
   This is to make sure that in the future, if we need to re-generate those
   certificates (for example because they expired in the meantime) or variants
   of them, we know how to do so. *As I saw in the openssl documentation
   certificates with SubjectKeyId or AuthorityKeyId fields should be generated
   via config file so I added one and also updated the Makefile. Now the
   Makefile contains a command to regenerate the original "errorfree" crt to
   test my new features. I added comments after that line to describe how to
   create the ones with error injections. I saw that there were some
   RegEx-like commands in the Makefile for this purpose, but I was not able to
   figure them out, so I left it like this. I hope it can be accepted in this
   format. *
   - Just a tip which may or may not be useful: when you get to evaluating
   coverage of the new parsing functions you added, you might find that it's a
   bit hard to cover all case of errors with certificate files. For this we
   have the test function x509parse_crt to which you can pass arbitrary data
   in hex. We normally start from a valid structure and them modify it by hand
   in order to introduce errors of our choice. I find the ASN.1 decoder at
   https://lapo.it/asn1js/ very helpful for this kind of thing. Producing
   hex data with the right error in the right place can be a bit tedious (as
   you often have to update lengths in enclosing structures), but for now it's
   usually our best chance to cover all the failing cases of parsing
   functions. *Thank you! I modified them by hand based on the hex values,
   this would have been a bit easier)*
   - Finally, please add a ChangeLog entry, see ChangeLog.d/00README for
   instructions. *Done*


*When the membuffer related issue is solved how can I mark my PR to
"review"? Is it automatic or should I send an e-mail to request for it?*

Thank you for your help Manuel!

BR,
Gábor


Manuel Pégourié-Gonnard <notifications@github.com> ezt írta (időpont: 2021.
febr. 12., P, 9:59):

**Comment by mpg** [comment]
Note: this was closed because an updated was created as a new PR: #4140

**Pull request closed without merging**
