### PR TITLE
library: Port to Haiku.

### PR DESCRIPTION
**Pull request by waddlesplash**
@sbutcher-arm, @gilles-peskine-arm, sorry about that, here's the new (rebased) PR from #819.

### CODE REVIEW

**Comment by gilles-peskine-arm** [comment]
retest

**Comment by RonEld** [comment]
@waddlesplash Please confirm [this](https://os.mbed.com/users/waddlesplash/) is your Mbed account

**Comment by RonEld** [comment]
Please ignore my previous comment, I haven't seen your previous PR, with the CLA signed

**Comment by sbutcher-arm** [comment]
Note for gatekeeping, this needs a `ChangeLog` entry.

**Pull request merged**
