### PR TITLE
all.sh: make it possible to run a subset of the components

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Break up `all.sh` into components and make it possible to run a subset of the components by listing them on the command line.

To this effect:

1. Reorganize `all.sh` into functions.
2. A very minimal amount of tidying up. I did remove one redundant component.
3. All components back up `config.h` systematically.
4. If you pass component names on the command line, `all.sh` only executes these components. With `--except`, `all.sh` runs all the components except the ones named on the command line. With no non-option argument, `all.sh` executes all the components. Run `all.sh --list-components` to list available components.

Apart from some minor differences in the lead-in and clean-up to each component and some minor component reorganization, the result and reporting of `all.sh` should be the same as before.

Because the review of this PR was delayed and it contains commits that are very tedious to replay and to review, I merged `mbedtls-2.16.0` rather than rebasing my work on top of it. The commits before the merge were previously submitted in #2235 which has been reviewed.

Potential follow-ups, which are explicitly out of scope in this PR:

* Simplify keep-going mode: if a component fails in the middle, just move on to the next component.
* Make the reporting fit the component model better: report the names of failing components, report the number of passing components...
* Self-checks to ensure that when someone adds a component, they don't forget to add it to the default list.
* Aids to parallelization. The primary goal of this PR is to pave the way for parallelization, not to achieve parallelization.

### CODE REVIEW

**Comment by gilles-peskine-arm** [comment]
Run of `all.sh` (should succeed): https://jenkins-internal.mbed.com/job/mbedtls-release/907/

**Comment by mpg** [comment]
Note: the release job (which actually tests `all.sh`) in the CI passed. The PR job (which doesn't test `all.sh`) only failed in a known-intermittent test, so is as good as a pass.

**Comment by gilles-peskine-arm** [comment]
@Patater Oops, yes!

I was worried about this mistake, and I considered making `run_all_components` automatically enumerate all the components. I decided against it because there's no way to enumerate functions in sh (although it would have been possible with a dirty hack such as `grep <$0`) and because a few components are conditional (but not enough to warrant a conditional component declaration mechanism).

**Comment by gilles-peskine-arm** [comment]
I amended the merge commit to fix the missing component invocations.

**Comment by sbutcher-arm** [comment]
@gilles-peskine-arm - I can see you have a merge commit. Do you really need it? We have a policy to reject PR's with merge commits unless there's strong justification.

**Comment by gilles-peskine-arm** [comment]
@sbutcher-arm This PR starts with an intrusive change to `all.sh`, followed by a series of reorganization steps. The initial step especially requires being very careful not to omit a piece of code (by removing it, or by stuffing it into a function that doesn't get executed). Other commits also carry some risk of dropping code or making a failure go unnoticed.

Re-doing the PR would be a lot of work both for the submitter and for the reviewers, with a high amount of risk, and the stakes are that tests would stop being executed or test failures would stop being reported. The tedium also increases the risk of errors.

In contrast, the merge commit from 2.14 to 2.16 just took a few minutes to do and review.

A merge is significantly less work and less risk.

**Comment by sbutcher-arm** [comment]
Approved for merge, pending backport to `mbedtls-2.7`.

**Comment by pkolbus** [comment]
I've got a few open PRs that add tests to all.sh. 

Out of curiosity, is this planned to merge soon? If so I'm happy to rebase my work and adjust into the new structure.

**Comment by hanno-arm** [comment]
> Out of curiosity, is this planned to merge soon? If so I'm happy to rebase my work and adjust into the new structure.

@pkolbus Yes, we're planning to merge this soon, so if you could rebase your outstanding work on top of it, that would be very helpful.

**Pull request merged**
