### PR TITLE
ECC import: more useful choice of INVALID_ARGUMENT vs NOT_SUPPORTED

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
When attempting to create an ECC key, return NOT_SUPPORTED for a curve that isn't recognized at all, same as for a curve that is recognized but not included in the current build. Keep returning INVALID_ARGUMENT if there is an explicit bit-size which is inconsistent with the key data.

This is very minor in itself, but the current situation made it difficult to generate test cases in a systematic way, so it's on the critical path for #4076.

### CODE REVIEW

**Review by gabor-mezei-arm — DISMISSED** [review]

**Review by tom-daubney-arm — DISMISSED** [review]
These changes make sense and are straightforward to follow. This looks good to me.

**Comment by gilles-peskine-arm** [comment]
There was a merge conflict in `test_suite_psa_crypto.data` with the change of dependencies from `MBEDTLS_ECP_C` to `PSA_WANT_KEY_TYPE_ECC_KEY_PAIR`, so I rebased the PR on top of `development` and took the changes from this PR except with `MBEDTLS_ECP_C` replaced with `PSA_WANT_KEY_TYPE_ECC_KEY_PAIR` in modified and new test cases.

**Comment by gilles-peskine-arm** [comment]
I rebased again to resolve the merge conflicts. I also added a new commit because I noticed that I'd forgotten to update some documentation.

Here's a high-level description of the conflict resolution:

* The changes to the implementation of `psa_load_ecp_representation` from `psa_crypto.c` are now changes to `mbedtls_psa_ecp_load_representation` in `psa_crypto_ecp.{h,c}`.
* Some of the changes to add the new parameter when calling `psa_load_ecp_representation` or `mbedtls_ecc_group_of_psa` conflicted with other changes in `development`. I just went for the version from `development`, then…
* I updated new places where `mbedtls_psa_ecp_load_representation` (formerly `psa_load_ecp_representation`) or `mbedtls_ecc_group_of_psa` was called to pass the new parameter.

**Review by gabor-mezei-arm — APPROVED** [review]

**Review by tom-daubney-arm — APPROVED** [review]
As before, LGTM.

**Comment by gilles-peskine-arm** [comment]
The ABI check is failing due to a change in an auxiliary function which is [documented as a potentially unstable API, so this is acceptable](https://github.com/ARMmbed/mbedtls/pull/4072#issuecomment-771618480). So CI is considered a pass.

**Pull request merged**
