### PR TITLE
Backport 2.1: pkcs5: add support for additional hmacSHA algorithms

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Add support for the SHA-2 family to the PKCS#5 module. This is a very small code change and fixes an interoperability issue, hence the proposal to backport it even though this is technically a new feature.

Straightforward backport of #1219 (I only tweaked the ChangeLog entry)

### CODE REVIEW

**Comment by gilles-peskine-arm** [comment]
`all.sh` passed locally.

**Comment by hanno-arm** [comment]
@gilles-peskine-arm Do we need a backport to 2.7?

**Comment by gilles-peskine-arm** [comment]
@hanno-arm Thanks for raising this. We haven't decided yet whether we were going to backport this change. #1219 has been merged to development and can be merged to the 2.7 branch as well, so if we decide that we do want a backport, we can use #1219.

**Comment by sbutcher-arm** [comment]
Agreed and approved that this fix needs back porting to 2.1.

**Pull request merged**
