### PR TITLE
Wrap vsnprintf call in debug.c with mbedtls_vsnprintf

### PR DESCRIPTION
**Pull request by jorisa**
I have not tested the _WIN32 implementation. #760

### CODE REVIEW

**Comment by jorisa** [comment]
mbedtls_platform_win32_snprintf could probably call mbedtls_platform_win32_vsnprintf to avoid duplicate code.

**Comment by RonEld** [comment]
Hi jorisa,
Thank yo for your contribution, however, as you can see, the ci Travis failed with the following:

[0m[1m/home/travis/build/ARMmbed/mbedtls/library/platform.c:192:7: [0m[0;1;31merror: [0m[1mincompatible pointer types initializing 'int (*)(const char *, ...)' with an expression of type 'int (char *, unsigned long, const char *, __va_list_tag *)' [-Werror,-Wincompatible-pointer-types][0m
int (*mbedtls_printf)( const char *, ... ) = MBEDTLS_PLATFORM_STD_PRINTF;
[0;1;32m      ^                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0m1 error generated.
make[3]: *** [library/CMakeFiles/mbedcrypto.dir/platform.c.o] Error 1

which I believe is related to your change.
Please fix this error and amend your commit before we can continue on the review

**Comment by k-stachowiak** [comment]
@jorisa I looked at this PR and I found the reason for the travis build failure. It is a small typo in the following change:

    +#if !defined(MBEDTLS_PLATFORM_STD_VSNPRINTF)
    +#define MBEDTLS_PLATFORM_STD_PRINTF   vsnprintf /**< Default vsnprintf to use  */
    +#endif

The `vsnprintf` symbol has been assigned to `MBEDTLS_PLATFORM_STD_PRINTF` instead of `MBEDTLS_PLATFORM_STD_VSNPRINTF`. In some build configuration it leads `vsnprintf` to be assigned to a pointer to a `printf` implementation.

As the source branch is in your repository, would you be willing to introduce the correction so that the CI tests are passing and we may start reviewing the changes?

**Comment by sbutcher-arm** [comment]
I like what the PR does, but I wonder if we need it. We only have a single call to `vsnprintf()` in the library, which is only called by debug code, of whose use should be constant in the library, and compiled out in production code.

**Comment by sbutcher-arm** [comment]
I've studied this further, and I think similar to the comments @RonEld and @gilles-peskine-arm made in #1381, this is definitely an issue, but it's preferable to substitute use of `vsnprintf()` for `snprintf` rather than wire in another platform function.

However, I also think it's better to leave this PR open until we have a better solution, so we can assess them side by side, rather than close this prematurely.

**Comment by k-stachowiak** [comment]
Since @jorisa has not addressed my comment so far I created another PR introducing the necessary changes here: #1551.

@sbutcher-arm Could you please consider closing this PR?

**Comment by k-stachowiak** [comment]
@sbutcher-arm #1551 has been merged, so we may consider closing this PR

**Comment by RonEld** [comment]
Closing as a duplicate of the merged PR #1551

**Pull request closed without merging**
