### PR TITLE
Apply 4334 to development-3.0

### LINKED ISSUE #4280: Remove superseded/deprecated functions from hashing modules
Remove the functions that are currently marked as `\\deprecated` from the hashing modules, namely: md, md2, md4, md5, ripemd160, sha1, sha256, sha512.

All of these functions have been superseded by newer functions doing the same thing but returning `int` instead of `void` (and with a new name). The deprecated functions need to be entirely removed from the library.

### PR DESCRIPTION
**Pull request by mpg**
#4334 was merged in development instead of development_3.0 by mistake, this is a revival of it now targeting the correct branch :)

I rebased the over development_3.0 but kept the same commit structure, in order to make it easy to check that this indeed equivalent to the original using something like `git range-diff development..public/pr/4334 development_3.0..public/pr/4349` (after checking that the command is correct and adapting names to your local setup).

Fixes #4280

### CODE REVIEW

**Review by gilles-peskine-arm — APPROVED** [review]

**Comment by bensze01** [comment]
Do we need to merge this after the original commit-revert pair has been merged into development_3.0?
Or will that not cause any issues / will we fix those issues during the next merge?

**Comment by mpg** [comment]
Good question, I'm not sure. I would expect `git merge` to do the right think, but I wouldn't be overly surprised if it didn't. Probably safer to wait for the next merge of development there, then. I'm labeling "needs: preceding PR" to reflect that.

**Comment by bensze01** [comment]
#4366 was merged, so I'm removing the `needs: preceding PR` label.

**Comment by mpg** [comment]
Considering this is a straightforward port of a PR that was previously approved, this only needs a single approval.

**Comment by mpg** [comment]
The CI is passing except the API-ABI break check which is expected to fail, and the PR is targeting the 3.0 branch.

**Pull request merged**
