### PR TITLE
[baremetal] Add FI resistance to AES

### PR DESCRIPTION
**Pull request by artokin**
## Description
Add FI resistance to AES

__Impact on code-size:__

| | ARMC5 |
| --- | --- |
| `libmbedcrypto.a` before | 18497 |
| `libmbedcrypto.a` after | 18587 |
| gain in bytes Crypto | -90 |

## Status
**READY**

## Additional comments
This PR requires precending PRs ~#2918 and~ #2886

### CODE REVIEW

**Comment by mpg** [comment]
This has two approvals and a passing CI, but depends on a PR that still needs more review, so not labeling "ready for merge" just yet.

**Comment by mpg** [comment]
The prerequisite PR is now ready for merge, and this one still has two approvals, a passing CI, and no conflict or other dependency, so it's now ready for merge.

**Comment by sbutcher-arm** [comment]
I've reviewed this and see no issues, but I have demoted the dependent PR #2886, so am removing the 'ready for merge' label until that one is ready also.

**Comment by artokin** [comment]
PR #2886 is now `ready for merge`, so setting also this one as `ready for merge`

**Pull request merged**
