### PR TITLE
Backport 2.16: Query Mbed TLS configuration from ssl_client2 and ssl_server2

### PR DESCRIPTION
**Pull request by andresag01**
This PR is a backport for https://github.com/ARMmbed/mbedtls/pull/2105

## Description
This PR addresses:
* https://github.com/ARMmbed/mbedtls/issues/2029
* https://github.com/ARMmbed/mbedtls/issues/2030

The problem was that the detection of the current configuration in ssl-opt.sh used to be based on a fragile combination of calls to grep and sed which did not work in some cases and is not very portable. This PR replaces that mechanism by extending the command line interface for ssl_client2 and ssl_server2 to allow querying the current Mbed TLS configuration. For example, to check if MBEDLTS_AES_C was enabled at compile time, we simply need to run the command:
```
programs/ssl/ssl_server2 query_config=MBEDTLS_AES_C
```
A return value of 0 means that the feature is enabled and 1 means it was not. If the macro has a non empty expansion, this will be printed to stdout.

## Status
**READY**

### CODE REVIEW

**Comment by mpg** [comment]
@andresag01 This PR now has conflicts in `ssl-opt.sh`. Please resolve them.

**Comment by andresag01** [comment]
@mpg: Resolved conflicts. Waiting for CI results

**Comment by mpg** [comment]
@k-stachowiak Please re-review!

**Comment by mpg** [comment]
This has 2 approvals and a passing CI, fixes real bugs, has ChangeLog entries and is well covered by pre-existing tests, so ready for merge.

**Pull request merged**
