### PR TITLE
Expose SSL HW record acceleration error.

### PR DESCRIPTION
**Pull request by sander-visser**
Fix issue with variable shadowing.

Signed-off-by: sander-visser <github@visser.se>

## Status
**READY**

## Requires Backporting
NO  
## Migrations
If there is any API change, what's the incentive and logic for it.

YES | NO

## Additional comments
Any additional information that could be of interest

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
Outline the steps to test or reproduce the PR here.

### CODE REVIEW

**Comment by mpg** [comment]
Hi @sander-visser and thanks for your contribution!

Could you please give use more details about the issue this PR is fixing and how you found it:

- From the fix it looks like this is fixing a warning given by a compiler or static analyzer, not a bug in observable behaviour - is that correct ? (To be clear: we want to fix warnings just as well as functional bugs, we just want to be just what we're fixing.)

- As it happens, we're [planning on removing the `MBEDTLS_SSL_HW_RECORD_ACCEL` option in Mbed TLS 3.0](https://lists.trustedfirmware.org/pipermail/mbed-tls/2020-April/000022.html). If you're using this option and don't want it to be removed in Mbed TLS 3.0, you'll probably want to join the discussion on our [mailing list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls).

**Comment by sander-visser** [comment]
> 
> 
> Hi @sander-visser and thanks for your contribution!
> 
> Could you please give use more details about the issue this PR is fixing and how you found it:
> 
>     * From the fix it looks like this is fixing a warning given by a compiler or static analyzer, not a bug in observable behaviour - is that correct ? (To be clear: we want to fix warnings just as well as functional bugs, we just want to be just what we're fixing.)
> 
>     * As it happens, we're [planning on removing the `MBEDTLS_SSL_HW_RECORD_ACCEL` option in Mbed TLS 3.0](https://lists.trustedfirmware.org/pipermail/mbed-tls/2020-April/000022.html). If you're using this option and don't want it to be removed in Mbed TLS 3.0, you'll probably want to join the discussion on our [mailing list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls).

The issue is real as far as I have understood. Only the ret local to "if( mbedtls_ssl_hw_record_init != NULL )" would have seen the error and the shadowed ret that is returned from "end:" would still have been 0.

Im not a user of MBEDTLS_SSL_HW_RECORD_ACCEL. I just reacted to issue reported in Cppcheck 1.89 (I scanned the codebase since Im looking into optee that uses it (older version)).

**Comment by gilles-peskine-arm** [comment]
> I just reacted to issue reported in Cppcheck 1.89

Oh, interesting, thanks for the information. Last I tried cppcheck it didn't find anything interesting… But it does have the advantage that it explores different compile-time configurations, whereas almost every other static analysis tool work on the preprocessor output. [We should run it in our CI](https://github.com/ARMmbed/mbedtls/issues/3316).

**Comment by mpg** [comment]
I just checked that the issue was introduced in a refactoring that happened after 2.16, so it's not present in any of the LTS branches and doesn't need backporting.

**Pull request merged**
