### PR TITLE
[baremetal] Merge mbedtls-2.16 (2019-10-04)

### PR DESCRIPTION
**Pull request by mpg**
## Description

This is the periodic merge of mbedtls-2.16 into baremetal.

There were two conflicts:

- the usual, trivial one in the ChangeLog (as baremetal has an extra "baremetal" section at the top)
- a contextual one in `tests/scripts/all.sh` as mbedtls-2.16 removed some `unset` statements (no longer needed thanks to a change in the definition of `config.pl full`) while baremetal enabled pthread when invoking make or cmake on the subsequent line.

## Status
**READY**

### CODE REVIEW

**Comment by sbutcher-arm** [comment]
Failing CI with:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
FAILED: 1
test_asan_on_demand_parsing_remove_peer_cert: test: ssl-opt.sh, !MBEDTLS_SSL_KEEP_PEER_CERTIFICATE, MBEDTLS_X509_ON_DEMAND_PARSING: tests/ssl-opt.sh -> 1
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
Needs work!

**Comment by jarvte** [comment]
> Failing CI with:
> 
> ```
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> FAILED: 1
> test_asan_on_demand_parsing_remove_peer_cert: test: ssl-opt.sh, !MBEDTLS_SSL_KEEP_PEER_CERTIFICATE, MBEDTLS_X509_ON_DEMAND_PARSING: tests/ssl-opt.sh -> 1
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> ```
> 
> Needs work!

It's once again this test:
DTLS client reconnect from same port: reconnect ........................ FAIL

I had to restart my pr with memcmp 3 times to get it pass. I really think we must improve or remove this test.
I will restart the test

**Comment by jarlamsa** [comment]
There's also abi-api-check failing in the pr-head tests.

**Comment by jarvte** [comment]
> There's also abi-api-check failing in the pr-head tests.

It appeared on rerun

**Comment by mpg** [comment]
The API-ABI check only fails on pr-head, not on pr-merge, and this is because ABI changes have been merged to the base branch in the meantime (namely https://github.com/ARMmbed/mbedtls-restricted/pull/652 made some functions inline). I think this can be ignored as the change is not introduced by this PR, as demonstrated by the fact that this test passes on the pr-merge job.

**Comment by mpg** [comment]
To avoid discussions about whether we can accept the API-ABI spurious failure, I've rebase this PR.

@jarvte @jarlamsa Please review.

**Comment by mpg** [comment]
For some reason the CI wasn't reporting. Doing a zero-diff force-push to re-trigger it.

@jarvte @jarlamsa Sorry for dismissing your reviews with this force-push, can you double-check that there is no diff (for example by clicking on "force-pushed" in the github history since your last approval) and mark as approved again? Thanks!

**Pull request merged**
