### PR TITLE
Change the default IP addresses for DTLS samples

### PR DESCRIPTION
**Pull request by redtangent**
## Description
Changes the IP address to bind to for dtls_server.c to be "::" or optionally "0.0.0.0" if the preprocessor symbol FORCE_IPV4 is defined.

Also changes the destinaton IP address for dtls_client.c to be "::1" or if FORCE_IPV4 symbol is defined "127.0.0.1".

This change allows `dtls_server.c` and `dtls_client.c` to be configured to use either IPv4 or IPv6 at build time, so out of the box they will work together.

Previously `dtls_server.c` might bind to IPv6 and `dtls_client.c` connect over IPv4, leading to a failure.

## Status
**READY**

## Requires Backporting
Yes

This is a configuration of the build and doesn't materially change the logic. There is definitely a bug here, as this issue is causing the sample to fail to work on OSX and possibly Windows.

I think the decision to back port should be part of the review of this PR however.

Which branch?

`mbedtls-2.7` and `mbedtls-2.1`

## Todos
- [ ] Tests
- [ ] Documentation
- [x] Changelog updated
- [ ] Backported

### CODE REVIEW

**Comment by RonEld** [comment]
Resolves #977

**Comment by sbutcher-arm** [comment]
@mpg - Can you please give this PR design approval, if you feel it's a good idea?

**Comment by mpg** [comment]
I think that's a good idea, so I'm approving for design.

However the result needs to be manually tested on several platforms (Linux, OS X, Windows): please state what testing you've done so far.

**Comment by RonEld** [comment]
@redtangent Thank you for your contribution!

Although these changes look good, in addition to these, I think the fix should be added in the networking module (`net_sockets.c`), to automatically set the addresses to the default value , if `NULL` is given

**Comment by redtangent** [comment]
Hi @RonEld,

I think that's a bit outside the scope of what this PR is trying to do - which is to fix a sample that doesn't consistently work on all platforms.

The intention of the PR, is that when both DTLS samples are compiled on the same target, they both end up either on IPv6 or IPv4, not on different versions, which is currently happening.

I'm not sure changing the network layer to override NULL and override the platform and force an IP address and/or specific IP version is a good idea.

Why do you think the change is needed? What's the motivation?

**Comment by RonEld** [comment]
@redtangent 
>Why do you think the change is needed? What's the motivation?

The motivation is to modify the networking stack to support any application using it, not only the sample application. At the moment, the `net` API allows `NULL` as a parameter for address, but it doesn't behave as expected. Perhaps only documentation change is need in the networking module.
See #1817 for another similar issue on networking.

**Comment by redtangent** [comment]
I've now tested on more platforms, testing the default configuration and enabling the IPv4 override by defining `FORCE_IPV4`:

|                         | default | FORCE_IPV4 |
|-------------------------|---------|------------|
| OSX High Sierra 10.13.3 | PASS    | PASS       |
| Microsoft Windows 7     | PASS    | PASS       |
| Debian 4.9.0 - 32bit    | PASS    | PASS       |
| Ubuntu 18.04 - 64bit    | PASS    | PASS       |

For Linux, it worked without problem, but as an observation, for OSX and Windows however, the client makes the connection successfully and the server reports an error after the client disconnects:
```
  . Closing the connection... done
  . Waiting for a remote connection ... ok
  . Performing the DTLS handshake... failed
  ! mbedtls_ssl_handshake returned -0x7900

Last error was: -30976 - SSL - Processing of the ClientHello handshake message failed
```

There seems to be some spurious packet after the disconnect initiating a second handshake that ultimately fails. After that, any successive connections work without problem.

That is unrelated to this change, and I'm just mentioning it as I think an issue should be raised if we merge this change.

@mpg/@roneld - Can you please re-review and approve so we can merge this?

**Comment by sbutcher-arm** [comment]
@RonEld - if you can approve this, we can get it merged.

**Comment by RonEld** [comment]
@sbutcher-arm I believe my latest comment was not addressed.
Our networking stack allows [`NULL` as an input parameter](https://github.com/ARMmbed/mbedtls/blame/development/include/mbedtls/net_sockets.h#L123), and it should work with other applications, not only our dtls example. At the moment, if NULL is given, it will not always work. Changing the default IP address in our example, only hides the real problem, that our `bind()` function does not work as we document, in some use cases.

**Comment by sbutcher-arm** [comment]
So the PR is ready to merge, but in @RonEld's view we need another PR to close the issue(s).

**Comment by RonEld** [comment]
I don't think we need another PR to close the issue. I created #1987 for that purpose

**Comment by Patater** [comment]
Does this need backporting?

**Comment by sbutcher-arm** [comment]
Doh! Good point @Patater. Have demoted the PR until we have backports.

**Comment by redtangent** [comment]
I've backported this to `mbedtls-2.7` with PR #2041 and `mbedtls-2.1` with PR #2042.

**Comment by sbutcher-arm** [comment]
retest

**Pull request merged**
