### PR TITLE
Backport to Mbedtls 2.16:  Support set *_drbg reseed interval before seed

### PR DESCRIPTION
**Pull request by geecrypt**
Backport of #3393.

### CODE REVIEW

**Comment by geecrypt** [comment]
I did have a problem running local tests for this patch, but it seemed unrelated to my change.
`Failed to open test file: ./test_suite_asn1parse.datax` 
This also occured for a few other test datasets.

**Comment by gilles-peskine-arm** [comment]
> `Failed to open test file: ./test_suite_asn1parse.datax`

I guess you had built the project, then you changed to a 2.16 branch, then you ran `make clean`, then you built again. 2.16 doesn't have `test_suite_asn1parse`, and `make clean` deletes all `.datax` files but only deletes known executables, so `test_suite_asn1parse` was left behind. `make test` runs all the files called `test_suite_*` with no extension, it doesn't have a list of known test suites. The remedy is to run `make clean` before changing branches (which after several years of working on Mbed TLS I still forget regularly), or to delete the spurious files manually. Anyhow, it doesn't indicate a problem with the code.

**Comment by geecrypt** [comment]
> I guess you had built the project, then you changed to a 2.16 branch, then you ran `make clean`, then you built again. 
That's exactly what I did, hopefully I remember for next time ;)

**Review by gilles-peskine-arm — APPROVED** [review]
This is a faithful backport of #3393. The patch is identical except for expected differences (in CTR_DRBG, `reseed_counter` marks that the entropy nonce length is not set explicitly) due to https://github.com/ARMmbed/mbed-crypto/pull/305 which was added after 2.16.

**Comment by geecrypt** [comment]
> This is a faithful backport of #3393. The patch is identical except for expected differences (in CTR_DRBG, `reseed_counter` marks that the entropy nonce length is not set explicitly) due to [ARMmbed/mbed-crypto#305](https://github.com/ARMmbed/mbed-crypto/pull/305) which was added after 2.16.

I will add this info into future PRs. Should git blame to reference patch like you did.

**Review by ronald-cron-arm — APPROVED** [review]
This looks good to me as well.

**Pull request merged**
