### PR TITLE
Refactor ssl_context_info time printing

### PR DESCRIPTION
**Pull request by AndrzejKurek**
Follow-up for #3624 - refactoring time printing. 
Please only review the last commit. To be merged after #3624.

### CODE REVIEW

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Comment by tom-cosgrove-arm** [comment]
Approved, but wouldn't this be easier as an update to the other PR?

**Comment by AndrzejKurek** [comment]
> Approved, but wouldn't this be easier as an update to the other PR?

This change was not discussed by other reviewers or people engaged in the original PR, so I wanted to move any potential discussion (and additional review time, since it would invalidate the existing approval) here.

**Comment by AndrzejKurek** [comment]
Feature added to the original PR.

**Pull request closed without merging**
