### PR TITLE
Support Raw Public Key mode (RFC7250)

### PR DESCRIPTION
**Pull request by brycekahle**
This is definitely not complete enough to be included as is, but I wanted to start the discussion of what is required. I do have this implementation working against a tinydtls client, so it at least works for the cipher suite that I'm targeting of `ECDHE_ECDSA_WITH_AES_128_CCM_8`.

### CODE REVIEW

**Comment by miklis** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by mpg** [comment]
Thanks! Another feature that was on our roadmap, so the PR is really appreciated!

I'm doing a first superficial review and it looks good so far (I'm doing some nitpicking in line comments, but really nothing important). Of course we'll need to review it in more depth later and probably discuss a few points.

You've probably noticed you've got some failing tests in `tests/ssl-opt.sh`, some of them failing pretty badly (heap corruption). Please let me know if you need help with the test scripts - so far I'm conscious documentation may be lacking a be in this area.

**Comment by mpg** [comment]
Ok, lots of comments for a first review, but let me insist it generally looks good :)

I think the biggest thing we'd like to have and that is currently missing (which is not a problem as I understand it's work in progress) is the ability to compile without any X.509 support when RPK is enabled. This means we probably want an API to set keys and places to store them in `ssl_config` that are distinct from the X.509 functions/members.

Anyway, thanks again for your contribution, and we're looking forward to seeing it progress!

**Comment by brycekahle** [comment]
@mpg I addressed most of your comments (except the public key writing one and compiling without X509) and fixed all the tests. The code now allows configuration of the supported certificate types and the server checks the intersection of the sent and configured values. 

Pay special attention to the certificate type list iteration code. It feels gross because it requires `MBEDTLS_TLS_CERT_TYPE_NONE` in the certificate type list array`. I'm happy to redo that code in a style you desire.

**Comment by mpg** [comment]
Great, thanks! I'll be quite busy today and next week, so please allow some time before I do a second review of your code.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2086

**Comment by sbutcher-arm** [comment]
Hi @gilles-peskine-arm, when you've reviewed this fully and are satisfied by the design and architecture of this PR, can you please remove the 'needs design approval' label? 

Thanks

**Comment by stevew817** [comment]
@sbutcher-arm Is there a timeline for this feature to make it in?

**Comment by KShingala** [comment]
Hi, 

I need support for raw public key and in the process of resolving the conflicts in the files. However, I notice:
a. There are no samples that demonstrate use of the key.
b. The conversation in the ARM mbed forum suggests that this PR is incomplete. https://forums.mbed.com/t/to-support-raw-public-key-cert-type/4201

It will be nice if a summary of missing functionality could be provided. Thanks!

**Comment by KShingala** [comment]
I see that there is no mechanism to set the raw public key from the application side yet. I intend to introduce this mechanism with a callback to verify the peer's certificate. This approach will allow for out of band mechanism to verify the peer's raw public key. I do not know if there are any formal design guidelines. If there are, please point me to them. And it will be nice to get a reply!

**Comment by flaz83** [comment]
Any news about this?

**Comment by daverodgman** [comment]
Closing as #3552 builds on this PR

**Pull request closed without merging**
