### PR TITLE
Fix typo in sha512.h comment

### PR DESCRIPTION
**Pull request by ev-ermakov**
## Description
* Type: Typo in documentation
* Priority: Minor

### CODE REVIEW

**Comment by RonEld** [comment]
@ev-ermakov Thank you for your contribution and for your interest in Mbed TLS!
Although this is a straight forward fix, unfortunately our policy is to not accept contributions, without a Contributor’s Licence Agreement (CLA) signed or authorised by yourself or your employer.

If this is a personal contribution, the easiest way to do this is if you create an mbed account and [accept this click through agreement](https://os.mbed.com/contributor_agreement/). Alternatively, you can find a [slightly different agreement to sign here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/), which can be signed and returned to us, and is applicable if you don't want to create an mbed account or alternatively if this is a corporate contribution.

Thanks for your understanding and again, thanks for the contribution!

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by ev-ermakov** [comment]
@RonEld, I've created an account, but uh, I'm not quite sure that I understood everything about the license agreement.

**Comment by RonEld** [comment]
@ev-ermakov I assume you mean an Mbed account.
Could you please refer us to your Mbed account, as github and Mbed are not linked, so we need to manually search your user name.
If you want to use the click-through agreement, please read, and follow the instructions [here](https://os.mbed.com/contributor_agreement/)

**Comment by ev-ermakov** [comment]
@RonEld 
> Could you please refer us to your Mbed account

Sure. My user name is `odious` :)

**Comment by RonEld** [comment]
@ev-ermakov I'm sorry, but I can't seem to find your user name as an Mbed account.
Could you please double check there isn't a typo, or send a link to your account?

**Pull request closed without merging**
