### PR TITLE
Added AEGIS cipher to available ciphersuits for encryption, decryption and authentication

### PR DESCRIPTION
**Pull request by r0oto0r**
Notes:
* Pull requests cannot be accepted until:
-  The submitter has [accepted the online agreement here with a click through](https://developer.mbed.org/contributor_agreement/) 
   or for companies or those that do not wish to create an mbed account, a slightly different agreement can be found [here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/)
- The PR follows the [mbed TLS coding standards](https://tls.mbed.org/kb/development/mbedtls-coding-standards)
* This is just a template, so feel free to use/remove the unnecessary things
## Description
A few sentences describing the overall goals of the pull request's commits.

## Status
**READY/IN DEVELOPMENT/HOLD**

## Requires Backporting
When there is a bug fix, it should be backported to all maintained and supported branches.
Changes do not have to be backported if:
- This PR is a new feature\enhancement
- This PR contains changes in the API. If this is true, and there is a need for the fix to be backported, the fix should be handled differently in the legacy branch

Yes | NO  
Which branch?

## Migrations
If there is any API change, what's the incentive and logic for it.

YES | NO

## Additional comments
Any additional information that could be of interest

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
Outline the steps to test or reproduce the PR here.

### CODE REVIEW

**Comment by Patater** [comment]
HI @r0oto0r 

Thanks for your contribution! You may have noticed this PR has many file conflicts. This is because we've recently moved the cryptography portion of Mbed TLS to a separate repository to manage that library: [Mbed Crypto](https://github.com/ARMmbed/mbed-crypto). You can [read more about this move on our website](https://tls.mbed.org/tech-updates/blog/working-towards-mbed-tls-3).

Could you please make the necessary cryptography contributions in [Mbed Crypto](https://github.com/ARMmbed/mbed-crypto)? Once those are reviewed, approved, and merged, we can add the ciphersuite support here in Mbed TLS.

Thanks!

**Comment by r0oto0r** [comment]
I will work on this once I have little bit more time. Thanks for the feedback!

**Comment by yanesca** [comment]
Hi @r0oto0r, thank you again for your contribution! We are going to do some changes to the repository organisation, that might affect this PR: https://github.com/ARMmbed/mbedtls/issues/3064

**Comment by daverodgman** [comment]
Closing; at the moment we have not seen people asking for this cipher so it's not something we would look to add. This could change if there are significant use-cases which require it (please let us know if so).

**Pull request closed without merging**
