### PR TITLE
Backport 2.1: Support certificate signing with alternative RSA implementations

### PR DESCRIPTION
**Pull request by hanno-arm**
__Summary:__ This is the backport of #1089 to Mbed TLS 2.1.

__Internal Reference:__ IOTSSL-1538

### CODE REVIEW

**Comment by hanno-arm** [comment]
@andresag01 My understanding is that we do usually not backport tests and enhancements, so I deliberately omitted all of what you mentioned in the backports.

**Comment by andresag01** [comment]
@hanno-arm: My understanding was that we backport tests unless there are good reasons not to. Also, I thought that some of the versions checks you added in the original PRs were more like bugs because for example, you cannot have a v1 cert with extensions, etc.

**Comment by hanno-arm** [comment]
Waiting for @gilles-peskine-arm's review and opinion on the necessity of backports before potentially working on them.

**Comment by gilles-peskine-arm** [comment]
@hanno-arm @andresag01 Regarding what to backport:

* Style changes: yes, to ease merges of future backport, if we're confident that there's no risk of a semantic change in the executed code. E.g. whitespace changes are fine, but things that may realistically cause a compiler to emit different code should generally not be backported.
* Test cases: if you're backporting a bug fix, always backport its non-regression tests.
* Example programs and test infrastructure: we can be more liberal with those, we can backport features if they make our life more convenient, but we shouldn't expend effort on those if the backport wouldn't make our life more convenient. I don't consider the pedagogical value of backported example programs to be important: if you want to see how to use the library, look at the current version.

**Comment by hanno-arm** [comment]
@andresag01 @gilles-peskine-arm Added remaining commits from father PR. Note that fc77144 and d8a6f7c have been subsumed under the first commit f581e11 of this PR. Please review.

**Comment by hanno-arm** [comment]
ChangeLog still needs extension.

**Comment by hanno-arm** [comment]
ChangeLog extended.

**Comment by gilles-peskine-arm** [comment]
CI failed only due to timing tests (known issue), ok to merge

**Pull request merged**
