### PR TITLE
Add option to use smaller AES tables (table sizes reduced by 6144 bytes)

### PR DESCRIPTION
**Pull request by jkivilin**
This patch adds MBEDTLS_AES_SMALL_TABLES option to reduce number of AES
look-up tables and thus save 6 KiB of memory. Enabling this option
cause performance hit MBEDTLS_AES_SMALL_TABLES of ~7% on ARM and ~15%
on x86-64.

Benchmark on Cortex-A7 (armhf):

Before:
  AES-CBC-128              :      14394 Kb/s,          0 cycles/byte
  AES-CBC-192              :      12442 Kb/s,          0 cycles/byte
  AES-CBC-256              :      10958 Kb/s,          0 cycles/byte

After:
  AES-CBC-128              :      13342 Kb/s,          0 cycles/byte
  AES-CBC-192              :      11469 Kb/s,          0 cycles/byte
  AES-CBC-256              :      10058 Kb/s,          0 cycles/byte

Benchmark on Intel Core i5-4570 (x86_64, 3.2 Ghz, no turbo):

Before:
  AES-CBC-128              :     215759 Kb/s,         14 cycles/byte
  AES-CBC-192              :     190884 Kb/s,         16 cycles/byte
  AES-CBC-256              :     171536 Kb/s,         18 cycles/byte

After:
  AES-CBC-128              :     185108 Kb/s,         16 cycles/byte
  AES-CBC-192              :     162839 Kb/s,         19 cycles/byte
  AES-CBC-256              :     144700 Kb/s,         21 cycles/byte

### CODE REVIEW

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by sbutcher-arm** [comment]
Thanks for the contribution!

I think we'd like to accept this once I've given it a fuller review, but to accept your current contributions or any future contributions we will need a Contributor’s Licence Agreement (CLA) signed or authorised by yourself. You can [find an agreement to sign here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/), which can be signed and returned to us, or you could create an mbed account and [accept a slightly different agreement here with a click through](https://developer.mbed.org/contributor_agreement/) if this is a personal contribution. 

Thanks for your understanding, and apologies it's taken so long to come back to you since you made the contribution.

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by sbutcher-arm** [comment]
@mpg - Could you please do the design review?

**Comment by mpg** [comment]
Design reviewed and approved.

**Comment by mpg** [comment]
Note: I did some time tests on a FRDM-K64F board (based on a Cortex-M4 core) with Mbed OS (using the online compiler), and here are the results for running time of `mbedtls_aes_self_test(0)` (with CBC, CFB and CTR enabled) in milliseconds, depending of whether tables are stored in ROM or RAM, and whether we use 4 tables or 1. In the RAM case, the first line is with tables no initialised yet, and the second with tables initialised.

```
           4       1
RAM     1248    1244
        1248    1244
ROM     2614    2563
```

The results surprise me:
- apparently the time it takes to generate the tables in negligible
- apparently the code runs slightly faster with fewer tables
However I checked them many times and can't find a flaw with the measurement.

If the results are correct, then I would suggest making 1 table the new default.

**Comment by Patater** [comment]
Hi @jkivilin

Thanks very much for your contribution. We've merged your work into the development branch via commit 8645e908255694e8d3c3f1c04b439cc66cdd35a3.

Thanks!

**Comment by jkivilin** [comment]
Thanks. 

Merging this pull-request took over two years. Is this typical?

**Comment by hanno-arm** [comment]
Hi @jkivilin, 

apologies for taking such a long time to consider and merge your PR - it's without question that a delay as the one experienced here is unfavourable for multiple reasons, and we're actively working on reducing the time to review and integrate community contributions at the moment.

Thanks again for your contribution,
Kind regards,
Hanno

**Pull request closed without merging**
