### PR TITLE
Backport [mbedtls-2.16] : Init function variable to avoid compiler warning

### PR DESCRIPTION
**Pull request by jainvikas8**
Issue : https://github.com/ARMmbed/mbedtls/issues/2340

https://github.com/ARMmbed/mbed-crypto/pull/228

### CODE REVIEW

**Comment by Patater** [comment]
Needs a ChangeLog entry

**Comment by yanesca** [comment]
Since we didn't managed to reproduce or find the issue, this change is only a robustness improvement and not a bugfix. I don't think we need a Changelog entry for this.

**Comment by RonEld** [comment]
I think that this requires a ChangeLog, to credit the person that raised the issue

**Comment by jainvikas8** [comment]
Closing as not needed and not the right fix. Re-open if you can reproduce the error and know how to fix the real error (as opposed to masking it with blind initialization).

**Pull request closed without merging**
