### PR TITLE
Fix net_sockets regression on Windows

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Fix https://github.com/ARMmbed/mbedtls/issues/4465: `mbedtls_net_poll()` and `mbedtls_net_recv_timeout()` became unusable on Windows in Mbed TLS 2.26 and 2.16.10. No intended behavior change on other platforms.

Backports:

* 2.x: https://github.com/ARMmbed/mbedtls/pull/4688
* 2.16: https://github.com/ARMmbed/mbedtls/pull/4689

### CODE REVIEW

**Review by paul-elliott-arm — DISMISSED** [review]
This looks good to me, although the 64 bit issue does concern me - do we have a task backlogged for that?

**Comment by gilles-peskine-arm** [comment]
> do we have a task backlogged for that?

No. Based on https://stackoverflow.com/questions/1953639/is-it-safe-to-cast-socket-to-int-under-win64 it didn't seem that important to me: plenty of other code would break so it's unlikely that Windows will change, and Windows is not a tier 1 platform for us so we're unlikely to ever spend time making the Windows code more robust.

**Review by mpg — DISMISSED** [review]
Looks good to me, as soon as the CI is happy too.

In addition to the already mentioned documentation I also looked at [this](https://docs.microsoft.com/en-us/windows/win32/winsock/select-and-fd---2) to confirm that `FD_SET()` doesn't have the same kind of limitation on windows as it has on Unix.

**Comment by daverodgman** [comment]
It seems slightly inconsistent that there are still a couple of 'if( ctx->fd == -1 )' in mbedtls_net_close and mbedtls_net_free? Is this intentional?

**Comment by gilles-peskine-arm** [comment]
@daverodgman Indeed. Since this was not a necessary part of the bug fix, and is only an incomplete robustness improvement (without doing the 64-bit part as well, it's probably never going to matter), I've gone and retracted the robustness improvement. This PR is now solely the bug fix.

**Comment by gilles-peskine-arm** [comment]
I filed the lack of support for handles above 2^31-1 in https://github.com/ARMmbed/mbedtls/issues/4692.

**Review by daverodgman — APPROVED** [review]
LGTM

**Review by mpg — APPROVED** [review]
LGTM

**Pull request merged**
