### PR TITLE
Fix null pointer arithmetic in NIST_KW

### LINKED ISSUE #4025: Null pointer arithmetic in an edge case in NIST_KW
Steps to reproduce (on x86_64, Ubuntu 20.04 to be precise):
```
git checkout 2427d15ea382cf4f405778c85715adb40759311a
scripts/config.py full
export ASAN_CFLAGS='-Werror -Wall -Wextra -fsanitize=address,undefined -fno-sanitize-recover=all'
make CC=clang-10 CFLAGS="$ASAN_CFLAGS -O2" LDFLAGS="$ASAN_CFLAGS" lib
make CC=clang-10 CFLAGS="$ASAN_CFLAGS -O2" LDFLAGS="$ASAN_CFLAGS" -C tests test_suite_nist_kw
(cd tests && ./test_suite_nist_kw)
```
(This has probably been the case ever since NIST_KW was implemented.)

Expected outcome: the tests pass. This is what happens with GCC 9.3.0, with Clang 3.6 and with Clang 6.

Actual outcome:
```
NIST KW self test ................................................. PASS
NIST KW mix contexts and modes .................................... PASS
NIST KW init #1 wrapping AES-128: OK .............................. PASS
NIST KW init #2 unwrapping AES-128: OK ............................ PASS
NIST KW init #3 CAMELLIA-256: unsupported cipher .................. PASS
NIST KW init #4 AES-224: bad key size ............................. PASS
NIST KW init #5 BLOWFISH-128: bad cipher .......................... PASS
NIST KW lengths #1 KW plaintext OK (2 to 2^54 - 1 semiblocks) ..... PASS
NIST KW lengths #2 KWP plaintext OK (1 to 2^32 - 1 octets) ........ PASS
NIST KW lengths #3 KW ciphertext OK (3 to 2^54 semiblocks) ........ PASS
NIST KW lengths #4 KWP ciphertext OK (2 to 2^29 semiblocks) ....... PASS
NIST KW lengths #5 KW plaintext too short (2 to 2^54 - 1 semiblock  PASS
NIST KW lengths #6 KWP plaintext too short (1 to 2^32 - 1 octets) . PASS
NIST KW lengths #8 KW ciphertext too short (3 to 2^54 semiblocks) . PASS
NIST KW lengths #9 KWP ciphertext too short (2 to 2^29 semiblocks)  PASS
NIST KW lengths #10 KW plaintext not a multiple of semiblocks. .... PASS
NIST KW lengths #11 KW ciphertext not a multiple of semiblocks. ... PASS
NIST KW lengths #12 KWP ciphertext not a multiple of semiblocks. .. PASS
NIST KW lengths #13 KW wrapping output buffer too short ........... PASS
NIST KW lengths #14 KWP wrapping output buffer too short .......... PASS
NIST KW lengths #15 KW unwrapping output buffer too short ......... PASS
NIST KW lengths #16 KWP unwrapping output buffer too short ........ PASS
NIST KW lengths #17 KW plaintext NULL (2 to 2^54 - 1 semiblocks) .. PASS
NIST KW lengths #18 KW wrapping output NULL ....................... nist_kw.c:192:32: runtime error: applying non-zero offset 8 to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior nist_kw.c:192:32 in 
```

Looking at the code, I can confirm that it does indeed have undefined behavior because it tries to do arithmetic on a pointer which, in this particular test case, is null. We've gotten away with it in all the CI builds so far because the result of this pointer arithmetic is only _used_ if a certain condition is met, and this condition is not met in the problematic test case. However, in the source code, the arithmetic is _performed_ before checking the condition.
```
int mbedtls_nist_kw_wrap( mbedtls_nist_kw_context *ctx,
                          mbedtls_nist_kw_mode_t mode,
                          const unsigned char *input, size_t in_len,
                          unsigned char *output, size_t *out_len, size_t out_size )
{
…
    unsigned char *R2 = output + KW_SEMIBLOCK_LENGTH;
…
        if( out_size < in_len + KW_SEMIBLOCK_LENGTH )
        {
            return( MBEDTLS_ERR_CIPHER_BAD_INPUT_DATA );
        }
…
}
```

The test code calls `mbedtls_nist_kw_wrap` with `output=NULL` and `out_size=0`.

The function documentation does not clearly indicate whether these parameters are allowed. It states that `out_size` must have a certain minimum value which is nonzero, and that `output` must point to a buffer of size `out_size`, so `output=NULL` is never a valid parameter. However, `output=NULL` and `out_size=0` is a correct way to pass an empty buffer, and the function is defined to return an error if the buffer is too small, which presumably includes an empty buffer.

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
* Remove a duplicated definition of `ASSERT_ALLOC` (due to some bad merging along the line of the Mbed Crypto fork/merge).
* Remove a few spurious test case dependencies on PEM (minor but I noticed this when looking at something unrelated).
* Fix #4025.
    * I didn't write a changelog entry because although it was flagged by recent a UBSan, I think this is benign on today's hardware (but probably not on tomorrow's hardware!).
    * No non-regression because I couldn't find a way to trigger UBSan with the older compiler versions on the CI. You can test locally that an UBSan build with Clang 10 now passes the unit tests.

Backports: [2.x](https://github.com/ARMmbed/mbedtls/pull/4593), [2.16](https://github.com/ARMmbed/mbedtls/pull/4598)

### CODE REVIEW

**Review by mpg — APPROVED** [review]
Looks good to me, thanks for those fixes.

I'll just note that the first two commits seem unrelated to the PR's title, but mentally appending "and other simple fixes" to that title works :)

**Review by bensze01 — APPROVED** [review]
Looks good to me too.

**Comment by mpg** [comment]
@gilles-peskine-arm The links to the backports in the description are actually to this PR, and I'm not seeing the backports in the list of open PRs. That's probably intended, but then I find the links as bit misleading.

**Comment by gilles-peskine-arm** [comment]
Oh, sorry about the extra commits, I hadn't realized I'd applied the patch on top of another small-bugfix branch https://github.com/ARMmbed/mbedtls/pull/4592 instead of `development`.

Since you've both approved the whole thing I'll combine the fixes in the backports as well.

**Comment by gilles-peskine-arm** [comment]
Backports updated: [2.x](https://github.com/ARMmbed/mbedtls/pull/4593) (trivial), [2.16](https://github.com/ARMmbed/mbedtls/pull/4594) (different for the test framework parts)

**Pull request merged**
