### PR TITLE
Replaced config.h with more unique name mbedtls_config.h

### PR DESCRIPTION
**Pull request by Hadatko**
Hello, This is kindly request to replace config.h file name with some less common name, more specific to your project. Otherwise i have a conflict due to combining with other github projects which are using same file name inside their projects.

Notes:
* Pull requests cannot be accepted until:
-  The submitter has [accepted the online agreement here with a click through](https://developer.mbed.org/contributor_agreement/) 
   or for companies or those that do not wish to create an mbed account, a slightly different agreement can be found [here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/)
- The PR follows the [mbed TLS coding standards](https://tls.mbed.org/kb/development/mbedtls-coding-standards)
* This is just a template, so feel free to use/remove the unnecessary things
## Description
A few sentences describing the overall goals of the pull request's commits.

## Status
**READY/IN DEVELOPMENT/HOLD**

## Requires Backporting
When there is a bug fix, it should be backported to all maintained and supported branches.
Changes do not have to be backported if:
- This PR is a new feature\enhancement
- This PR contains changes in the API. If this is true, and there is a need for the fix to be backported, the fix should be handled differently in the legacy branch

Yes | NO  
Which branch?

## Migrations
If there is any API change, what's the incentive and logic for it.

YES | NO

## Additional comments
Any additional information that could be of interest

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
Outline the steps to test or reproduce the PR here.

### CODE REVIEW

**Comment by RonEld** [comment]
Hi @Hadatko 
Thank you for your contribution and for your interest in Mbed TLS!

Please note that this is a very big change, and it is breaking usability to existing applications.
I understand your use case, however as it is a breaking change, I am not sure we can accept it.
However, a splution for your problem, is for you to have your own copy of `config.h`, which you can name it a you want ( perhaps make it a soft link to `include/mbedtls` for easy version upgrading?), and in your compilation, define `MBEDTLS_CONFIG_FILE` to be this file.
Does this make sense?

**Comment by Hadatko** [comment]
Hi, solution for me would be delete config.h (or rename as i proposed). Use macro is not enough. Because combination of include path and config.h file in these include paths is breaking application built for others libraries using their config.h file. I understand that built did not pass. But i need get rid of config.h file in common include file. It can be moved or renamed.

**Comment by RonEld** [comment]
Thanks for clarifying your use case.

This is why your include path should be `<Mbed TLS root>/include`, and not  `<Mbed TLS root>/include/mbedtls`.
You will see that all of Mbed TLS' `.c` files include headers with the `mbedtls` namespace.

I think that if you will change your include path, to not include the `mbedtls` namespacing, you will not encounter your issue.

**Comment by Hadatko** [comment]
Yes that make sense. But unfortunately the tool we are using is creating include paths based on location of header files :/

**Comment by RonEld** [comment]
Thank you for explaining your situation!
We will take it into consideration.
However, since this is a breaking change, if we accept it, it would  probably be for version 3.0

cc @mpg

**Comment by Hadatko** [comment]
Thank you very much for considering this.

**Comment by irwir** [comment]
> I am also trying to convince maintainers of other projects

It would be a lot cheaper to fix or replace the tool that imposes such restrictions.

**Comment by mpg** [comment]
I think it's not the first time people run into this issue. I agree with @irwir that in principle the tools that impose such restrictions should be fixed, but in practice there will always be inflexible tools to deal with, and we should rename. In the near-ish future we're going to split `config.h` in at least two, possibly three files as mbed-crypto becomes a separate library, so that would be a good occasion to do some renaming.

In the meantime, you can always rename locally in your source tree, then define `MBEDTLS_CONFIG_FILE` on your compiler command line to the new name. IIRC this was added precisely to deal with that kind of issue (though in retrospect perhaps renaming would have been better, but I think it wasn't done for compatibility reasons, and then we forgot when moving to 2.0, and now as Ron said we have to wait until 3.0).

**Comment by irwir** [comment]
> we should rename

It might be necessay to rename `error.h` too, because that is a common name also.
What is next, `net.h`, `threading.h` and so on? Logically, all header file names should have globally unique  for all the libraries that ever existed. :)
Inflexible (or buggy) tools need improvements; and that is more practical approach than coersing library makes to rename files while users have to adjust their working code to breaking changes.

**Comment by mpg** [comment]
I principle I agree. In practice we only seem to be getting complaints about `config.h`, and as I said, we're very likely to split it for unrelated reasons, so we'll need new names anyway.

**Comment by gilles-peskine-arm** [comment]
I'm closing this pull request because the library has evolved since then and the code would need heavy rework. We won't rename `include/mbedtls/config.h` in a minor version of Mbed TLS because it would break backward compatibility. We are considering this for 3.0 where `config.h` is going to be split into a user-editable part and a part included from code. See https://github.com/ARMmbed/mbedtls/issues/3960

**Pull request closed without merging**
