### PR TITLE
Include configuration file to headers

### LINKED ISSUE #1371: File pem.h does not include "confg.h"
### Description
- Type: Bug 
- Priority:  Minor

---------------------------------------------------------------
## Bug
File pem.h does not include "confg.h"
It is neccessary to add such code

#if !defined(MBEDTLS_CONFIG_FILE)
#include "config.h"
#else
#include MBEDTLS_CONFIG_FILE
#endif

### PR DESCRIPTION
**Pull request by RonEld**
## Description
Add inclusion to configration file in header files,
instead of relying on other header files to include
the configuration file. This issue resolves #1371

## Status
**READY**

## Requires Backporting

Yes

## Todos
- [ ] Tests
- [ ] Documentation
- [x] Changelog updated
- [x] Backported

### CODE REVIEW

**Comment by mazimkhan** [comment]
I approve this PR in principle. However, these 5 lines in every file look very odd. I know it is legacy but can it not just be part of ```config.h``` like:

config.h:
```
#if !defined(MBEDTLS_CONFIG_FILE)

normal config.h content

#else
#include MBEDTLS_CONFIG_FILE
#endif
```
@gilles-peskine-arm what do you think?

**Comment by RonEld** [comment]
@gilles-peskine-arm I have thought about it, but then decided not to do it, since it might increase code size, without a real need. Personally, I don't like including redundant headers.

@mazimkhan I like your approach, but I would consider doing it in a different PR.

**Comment by gilles-peskine-arm** [comment]
@RonEld Including an extra header might mean a very small increase in compilation time, but it wouldn't affect generated code.

Furthermore the only reason why this header isn't needed everywhere is that we aren't clean about declaring functions only if they're defined. If we were, all the modules would have `#if defined(MBEDTLS_XXX_C)` around all the function declarations.

**Comment by RonEld** [comment]
@gilles-peskine-arm I agree that all modules should have `#if defined(MBEDTLS_XXX_C)` . I will include the configuration to all header files.

**Comment by gilles-peskine-arm** [comment]
As mentioned above, I'd prefer to include `config.h` everywhere, but I'm ok with merging this PR as it is since it's an improvement. I've checked and no new headers in development are affected as of 4ed3880a10d868ce42fe99b90f294c3d22ac8a36 (2.10+).

Please prepare backports.

**Comment by RonEld** [comment]
Backports available at #1796 and #1797

**Comment by RonEld** [comment]
removing "needs backports" label, as backports were raised, reviewed and approved

cc @sbutcher-arm @Patater

**Comment by irwir** [comment]
The approach with modified `config.h` looks good.
Should it  ever be accepted, it would be better to reverse comparison like this:
```
#ifdef MBEDTLS_CONFIG_FILE
#include MBEDTLS_CONFIG_FILE
#else
. . .
normal config.h content
. . .
#endif //MBEDTLS_CONFIG_FILE
```
The reason is that both alternatives will be immediately visible, no need to scan the whole file for the matching `#else` keyword.

**Comment by sbutcher-arm** [comment]
@RonEld - Can you fix the merge conflict with`cmac.h` on this and the back ports? Also - can you check (again - sorry for that) that no new headers have been added?

I'd like to get this merged in the next week.

**Comment by RonEld** [comment]
@sbutcher-arm I have rebased to resolve the conflicts, and added the inclusion of `config.h` to all the header files, as requested by @gilles-peskine-arm and to new header files.

I will add the fix to version 2.7 branch.

**Comment by sbutcher-arm** [comment]
@gilles-peskine-arm - Could you please re-approve? Thanks.

**Comment by RonEld** [comment]
@gilles-peskine-arm I agree, and it is already done in #2319

**Pull request merged**
