### PR TITLE
Contributions from our in-house project

### PR DESCRIPTION
**Pull request by p2k**
## Description
In the course of an in-house project, several additions to mbedTLS have been made by me that I am willing to share in the hope that they are useful. Please see the individual commit messages and let me know if anything is amiss.

## Status
**READY**

## Requires Backporting
No

## Migrations
The API has merely been extended, not changed. There are some changes to internal functions.

## Additional comments
I have read and accepted the [online agreement](https://developer.mbed.org/contributor_agreement/)

## Todos
- [ ] Tests
- [ ] Changelog updated

## Steps to test or reproduce
There currently is no explicit test for this PR. Tell me if you want me to write additional tests.

### CODE REVIEW

**Comment by p2k** [comment]
FYI: I don't know how to fix this Traivs build error:

```
$ tests/scripts/check-generated-files.sh
'library/error.c' was either modified or deleted by 'scripts/generate_errors.pl'
The command "tests/scripts/check-generated-files.sh" exited with 1.
```

**Comment by hanno-arm** [comment]
Hi @p2k,

thank you very much for your interest in Mbed TLS and for your contribution! 

I can see that your changes are substantial, affect several modules of Mbed TLS, and partly extend the API. To ease the reviewing process, can you consider opening separate PRs for the various enhancements you wish to contribute? That would be very helpful and prevent stopping approved changes from being merged because they are within the same PR as changes that might need more discussion.

Thanks again,
Kind regards,
Hanno, Mbed TLS team member

**Comment by hanno-arm** [comment]
Hi @p2k,

could you confirm that [this](https://os.mbed.com/users/p2k/) your Mbed user account?

Regards,
Hanno

**Comment by hanno-arm** [comment]
> FYI: I don't know how to fix this Traivs build error:
> 
> ```
> $ tests/scripts/check-generated-files.sh
> 'library/error.c' was either modified or deleted by 'scripts/generate_errors.pl'
> The command "tests/scripts/check-generated-files.sh" exited with 1.
> ```

@p2k This happens if you add, remove or modify error codes, including their documentation. In this case, `library/error.c` needs to be regenerated by executing `./scripts/generate_errors.pl`. Travis executes `./scripts/generate_errors.pl` and compares the result with `library/error.c` to see if this was done.

**Comment by hanno-arm** [comment]
@p2k Your commit 4e08e01 on UTF8 strings appears to have overlap with #1641 which will be merged soon. Could you please check if #1641 obsoletes 4e08e01 before creating a PR for it?

**Comment by RonEld** [comment]
@p2k Thank you for your contribution!
As you know, we cannot accept contributions until a CLA has been accepted.
Although I believe you have accepted the individual online agreement, as mentioned in the description, and Hanno referenced your account, if this is a corporate contribution,  you will need to accept the corporate CLA agreement, [here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/).
Thank you for your understanding and cooperation!

**Comment by p2k** [comment]
@hanno-arm 
Okay, I'll be closing this pull request and repackage my changes into individual features. Also thanks for checking my additions against current features and current pull requests as I don't have a clear overview over everything that's happening in mbedTLS. I'll have a look at #1641.

Yes, [this](https://os.mbed.com/users/p2k/) is my account using my office email address (which is used in commits as well).

@RonEld 
I'll have the corporate CLA agreement sorted asap.

**Comment by p2k** [comment]
@hanno-arm 
Okay, I'll be closing this pull request and repackage my changes into individual features. Also thanks for checking my additions against current features and current pull requests as I don't have a clear overview over everything that's happening in mbedTLS. I'll have a look at #1641.

Yes, [this](https://os.mbed.com/users/p2k/) is my account using my office email address (which is used in commits as well).

@RonEld 
I'll have the corporate CLA agreement sorted asap.

**Comment by p2k** [comment]
@hanno-arm 
Okay, I'd like to close this pull request and repackage my changes into individual features (github won't let me close the PR). Also thanks for checking my additions against current features and current pull requests as I don't have a clear overview over everything that's happening in mbedTLS. I'll have a look at #1641.

Yes, [this](https://os.mbed.com/users/p2k/) is my account using my office email address (which is used in commits as well).

@RonEld 
I'll have the corporate CLA agreement sorted asap.

**Comment by p2k** [comment]
@hanno-arm 
Okay, I'll be closing this pull request and repackage my changes into individual features. Also thanks for checking my additions against current features and current pull requests as I don't have a clear overview over everything that's happening in mbedTLS. I'll have a look at #1641.

Yes, [this](https://os.mbed.com/users/p2k/) is my account using my office email address (which is used in commits as well).

@RonEld 
I'll have the corporate CLA agreement sorted asap.

**Comment by p2k** [comment]
@hanno-arm 
Okay, I'll be closing this pull request and repackage my changes into individual features. Also thanks for checking my additions against current features and current pull requests as I don't have a clear overview over everything that's happening in mbedTLS. I'll have a look at #1641.

Yes, [this](https://os.mbed.com/users/p2k/) is my account using my office email address (which is used in commits as well).

@RonEld 
I'll have the corporate CLA agreement sorted asap.

**Comment by p2k** [comment]
(Sorry, I had issues with Github)

**Pull request closed without merging**
