### PR TITLE
RSA encryption: accept null plaintext

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Add tests for RSA encryption with null plaintext, which is supported for the sake of PSA (see rationale below) since #2395.

----

Accept null buffers for a zero-length plaintext in RSA encryption and decryption.

The Mbed TLS documentation does not explicitly state that buffers must be non-null even if their size is 0, but a lot of code assumes it. PSA explicitly states that a null pointer is ok when the buffer size is 0. This pull request has a limited scope: to add support for null pointers where the PSA code requires it, which turns out to be only for RSA encryption and decryption.

I didn't add a changelog entry because this doesn't change the promised behavior of the library. At this stage, it's only a matter of internal behavior.

Precursor to PSA (asymmetric encryption).

### CODE REVIEW

**Comment by sbutcher-arm** [comment]
retest

**Comment by Patater** [comment]
I've rebased on the latest development branch so that this can go through CI.

**Comment by Patater** [comment]
pkcs1_v15-suite is failing in CI

**Comment by gilles-peskine-arm** [comment]
I fixed the bug which was due to incomplete input for `rnd_buffer_rand`, causing a fallback to `rand()`, which worked on my machine and all our Linux test platforms because they have the same `rand()`, but not on FreeBSD which has a different `rand()`. I wonder why there wasn't a Windows failure — or was there and did we miss it with the CI instabilities?

**Comment by Patater** [comment]
"but a lot of code assumes it" implies explicitly supporting this would be a good candidate for a backport to 2.7.

**Comment by gilles-peskine-arm** [comment]
The library change (d6feef7523beb9019cd0aca77a03ffa8b2b2a474) has already been merged via #2395. The test changes still need to go in. I'll rebase this PR to be on top of current development and to have only the test changes.

**Comment by gilles-peskine-arm** [comment]
Rebased on top of development, without the commit that was already there. Previous history at https://github.com/gilles-peskine-arm/mbedtls/commits/rsa-null_plaintext-2

**Pull request merged**
