### PR TITLE
Remove redundant i increments

### PR DESCRIPTION
**Pull request by pieceofsummer**
Doesn't matter performance-wise, but still...

### CODE REVIEW

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by mazimkhan** [comment]
@gilles-peskine-arm changes look good. Only known timing tests have failed in CI.

**Comment by mazimkhan** [comment]
@pieceofsummer can you please rebase you PR. There have been some fixes in development branch to stabilise timing tests.

**Comment by gilles-peskine-arm** [comment]
@mazimkhan As long as the failures are only in the timing tests and the PR doesn't change anything related to timing, we can take it as it is, there's no need to rebase. We have to do another round of testing after merging anyway. If you approve this PR, please mark it as “Approved” in Github.

**Pull request merged**
