### PR TITLE
Allow test suites to be run on Windows

### PR DESCRIPTION
**Pull request by mazimkhan**
Back port from ARMmbed:development

### CODE REVIEW

**Comment by mazimkhan** [comment]
@gilles-peskine-arm CI is still running. But it does fix mingw build https://jenkins-internal.mbed.com/job/mbedtls-pr/455/execution/node/73/log/

**Comment by gilles-peskine-arm** [comment]
This is a backport of #353 to 1.3, for some reason back then it had only been backported to 2.1 but our 1.3 test runs need fixing as well.

**Comment by mazimkhan** [comment]
LGTM

**Comment by gilles-peskine-arm** [comment]
This is a backport of something we've had for a while in development and 2.1 and have no complaint with. @mazimkhan is happy with it, I'm happy with it, CI is happy with it. CI is unhappy without it (failed builds on #1081 and #1083), which makes me unhappy without it. Therefore, I'm merging it.

**Comment by gilles-peskine-arm** [comment]
Tagging as bug since the lack of it is breaking our CI.

**Pull request merged**
