### PR TITLE
Remove duplicate #include

### PR DESCRIPTION
**Pull request by masap**
Signed-off-by: Masashi Honma <masashi.honma@gmail.com>

## Description
Remove duplicate #include

## Status
READY

## Requires Backporting
NO

## Migrations
NO

## Additional comments
None

## Todos
None

## Steps to test or reproduce
make check passed

### CODE REVIEW

**Comment by masap** [comment]
This PR replaces PR #2305.

**Comment by masap** [comment]
Hello @AndrzejKurek . I will fix the author information based on suggestion by RonEld.
Do you require other file modification ?

**Comment by AndrzejKurek** [comment]
@masap - No, that's the only thing I would like to request.

**Comment by masap** [comment]
@RonEld 

> I have added a fix suggestion to the changLog entry.

I fixed it.

> Please create a branch, which contains only your fix, and create a PR from your branch on your fork, to the master development branch.

OK, I created a branch for PR. So I need to create new PR  #2326.

**Pull request closed without merging**
