### PR TITLE
Allow cmake build from subdirectory

### PR DESCRIPTION
**Pull request by tripplet**

### CODE REVIEW

**Comment by zeil** [comment]
You also need to specify config file with -f option.
So, full command will be:
execute_process(COMMAND ${PERL_EXECUTABLE} ${CMAKE_SOURCE_DIR}/scripts/config.pl -f ${CMAKE_SOURCE_DIR}/include/mbedtls/config.h get MBEDTLS_TEST_NULL_ENTROPY RESULT_VARIABLE result)

**Comment by tkelman** [comment]
Is this okay to merge? The warning from #541 is confusing contributors.

**Comment by sbutcher-arm** [comment]
Thanks for the pull request @tripplet. I appreciate the fix is trivial, but unfortunately, to accept the contribution and any future contribution we still need a Contributor’s Licence Agreement (CLA) to be accepted. 

To do this you could create an mbed account and [accept the agreement here with a click through](https://developer.mbed.org/contributor_agreement/) which may be easiest if this is a personal contribution, or you can [find a slightly different agreement to sign here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/), which should be signed and returned to us, and would be suitable if the contribution is on behalf of a company.

**Comment by zeil** [comment]
Hello everyone! I think we should use only one of the CMAKE_SOURCE_DIR or CMAKE_CURRENT_SOURCE_DIR flags for the uniform.

**Comment by andresag01** [comment]
I have created a new PR at https://github.com/ARMmbed/mbedtls/pull/589 that takes into account @zeil suggestions and also adds a test for this functionality.

**Comment by tripplet** [comment]
I accepted the Contributor’s Licence Agreement (CLA) with username "ttobias", but if you want to merge the pr by  @andreasag01 that's also fine by me.
I made the pull request to get the problem fixed upstream 😄

**Comment by sbutcher-arm** [comment]
Thanks for signing the CLA! The two PR's are very similar, but I would like to accept @andresag01 's because it adds an additional test to our test suite, to guard against this regressing again. To be honest, we should have spotted this prior to release, so the extra test is good.

I'll leave this PR open until we've merged the fix.

Thanks for the support of mbed TLS!

**Comment by sbutcher-arm** [comment]
I've merged @andresag01's fix in #589, as that contained a test to avoid regression, so this PR can now be closed as the issue is resolved.

**Pull request closed without merging**
