### PR TITLE
Remove duplicate #include

### PR DESCRIPTION
**Pull request by masap**
Signed-off-by: Masashi Honma <masashi.honma@gmail.com>

## Status
READY

## Requires Backporting
NO  

## Migrations
NO

## Additional comments
None

## Todos
None

## Steps to test or reproduce
make check passed

### CODE REVIEW

**Comment by masap** [comment]
This PR replaces PR #2318.

**Comment by RonEld** [comment]
Note: This will require backporting to branches `mbedtls-2.7` and `mbedtls-2.16`

**Comment by sbutcher-arm** [comment]
Backported this PR to `mbedtls-2.7` as PR #2341.

The PR doesn't need backporting to `mbedtls-2.16` as this PR is based on Mbed TLS 2.16.0 and can be merged into both `development` and `mbedtls-2.16`.

**Comment by RonEld** [comment]
The backport to `mbedtls-2.7` has been fully approved, so removing the "needs backports" label

**Pull request merged**
