### PR TITLE
Backport 2.16: add missing some error checks in ECP and bignum

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Straightforward backport of https://github.com/ARMmbed/mbedtls/pull/3942

### CODE REVIEW

**Review by ronald-cron-arm — DISMISSED** [review]
This looks all good improvements to me.

**Review by mpg — DISMISSED** [review]
LGTM

**Comment by mpg** [comment]
The CI only fails in (1) compat.sh in Travis which was fixed in the meantime by #3590 (2) armcc license issue, which is independent from this PR.

**Comment by gilles-peskine-arm** [comment]
I'm going to add a changelog entry, make the (trivial, I think) 2.7 backport, and rework https://github.com/ARMmbed/mbedtls/pull/3512 to be standalone.

**Review by ronald-cron-arm — APPROVED** [review]
LGTM

**Review by mpg — APPROVED** [review]
LGTM

**Pull request merged**
