### PR TITLE
Remove deprecated things from crypto_compat.h and dependent tests.

### PR DESCRIPTION
**Pull request by TRodziewicz**
Signed-off-by: TRodziewicz <tomasz.rodziewicz@mobica.com>

## Description
Remove deprecated things in psa/crypto_compat.h. For more details see the originating issue.

Fixes: #4284 

## Status
READY

## Requires Backporting
NO  

## Todos
- [x] Tests
- [x] Documentation
- [x] Changelog updated

### CODE REVIEW

**Review by gilles-peskine-arm — APPROVED** [review]

**Review by gilles-peskine-arm — APPROVED** [review]

**Review by mpg — CHANGES_REQUESTED** [review]
This is looking good to me, but the CI is not fully happy:
```
******************************************************************

* check_doxygen_warnings: Check: doxygen warnings (builds the documentation) 

* Fri Apr 16 21:18:25 UTC 2021

******************************************************************

/var/lib/build/include/psa/crypto.h:779: warning: explicit link request to 'PSA_KEY_TYPE_GET_CURVE' could not be resolved

FAIL

^^^^check_doxygen_warnings: Check: doxygen warnings (builds the documentation): tests/scripts/doxygen.sh -> 1^^^^
```

**Comment by mpg** [comment]
Note: the doxygen warning only occurs in the `pr-merge` job, so I think before you can reproduce and fix you need to merge the current `development_3.0` into your branch:

```
git checkout remove_deprecated_things_in_crypto_compat_h
git fetch public
git merge public/development_3.0
```

(Replace `public` with the name of the remote that points to `ARMmbed/mbedtls.git`, you can check with `git remove -v`. If you don't have a remote pointing to that repo yet, you can get one by running `git remote add public git@github.com:ARMmbed/mbedtls.git` before running the above commands.)

Then you should be able to reproduce the issue y running `tests/scripts/doxygen.sh` and fix it. (Note: if your doxygen version is too recent, you'll also get other warnings which you don't need to fix, just fix the one that's also found by the CI. The others are already tracked elsewhere.)

**Comment by gilles-peskine-arm** [comment]
The CI problem is a bug introduced by #4174 and fixed by #4318. It's present in the `development_3.0` branch, which was last synched from `development_2.x` between the merge of these two PR. The proper fix would be to update the 3.0 branch.

**Comment by mpg** [comment]
Oh, so this can be ignored for the purpose of merging this PR. Thanks Gille for clarifying that.

**Review by mpg — APPROVED** [review]
LGTM and Gilles clarified that the doxygen issue was pre-existent and is already being fixed elsewhere, so we're good to go.

**Comment by gilles-peskine-arm** [comment]
Uh, sorry if I was unclear, I meant that we should wait to merge this PR until 3.0 is up-to-date. I've made a [PR to update 3.0](https://github.com/ARMmbed/mbedtls/pull/4366).

Never mind about merging this PR, let's just merge https://github.com/ARMmbed/mbedtls/pull/4366 quickly.

**Comment by mpg** [comment]
Aw, I'll review 4366 quickly then.

**Pull request merged**
