### PR TITLE
Implement AES-XEX mode

### PR DESCRIPTION
**Pull request by Aorimn**
XEX mode, known as "xor-encrypt-xor", is the simple case of the XTS mode, known as "XEX with ciphertext stealing". When the buffers to be encrypted/decrypted have a length divisible by the length of a standard AES block (16), XTS is exactly like XEX.
XTS is a mode used for disk encryption, where data unit is a sector (commonly 512 bytes). As 512 is a multiple of 16, only the XEX part is used, hence this first -simple- implementation.

This PR includes test cases with vectors extracted from the [XTS test vectors](http://csrc.nist.gov/groups/STM/cavp/documents/aes/XTSTestVectors.zip) given by the CAVP initiative of the NIST, filtered for taking only divisible-by-16 plaintexts/ciphertexts.

Notes :
- TrueCrypt implementation of AES-XTS mode is really only AES-XEX.
- OpenSSL has a working, true, AES-XTS (i.e: not just AES-XEX renamed in AES-XTS like TrueCrypt).

### CODE REVIEW

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by sbutcher-arm** [comment]
Hi @Aorimn,

Thanks for the contribution and support of mbed TLS.

To accept the contribution we would need a Contributor's Licence Agreement (CLA) to be signed, but looking through the Pull Request, I can see that some of the work is not your own, and in particular draws from @BrianGladman's work which is also under the GPL licence, and until that is removed we can't accept the contribution.

Can you replace that code with your own? I can then do a more thorough review, although most of the work looks pretty good already.

To submit a CLA, you can [find the forms here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/).

Thanks!

**Comment by sbutcher-arm** [comment]
Hi @Aorimn,

Just to follow-up, if you can sign our Contributor's License Agreement (CLA), and would like to resubmit the contribution, addressing the issues above, we'd still be very happy to take the contribution.

**Comment by Aorimn** [comment]
Hi @sbutcher-arm,

Sorry for not answering before. I won't have time right now to update the contribution as requested in your previous message.
As for the CLA, do I have to send it to support@mbed.com, as requested on [the page you linked](https://www.mbed.com/en/about-mbed/contributor-license-agreements/), or to cla-submissions@arm.com, as requested in the PDF?

**Comment by sbutcher-arm** [comment]
Hi,

Please send the completed agreement to cla-submissions@arm.com, or alternatively for personal contributions, you can create an mbed account and accept an online agreement with a click through [here](https://developer.mbed.org/contributor_agreement/), which is much quicker and simpler, but does require you to create an account.

Thanks for the support!

**Comment by Aorimn** [comment]
Ok, it has been sent to that address. Next phase is reimplementing some code, but as said above, that will be later, please be patient on that point :-)

**Comment by Aorimn** [comment]
Hi @sbutcher-arm,

I've changed the gf128mul.c file with my own implementation, as requested. I've also taken the time to implement the proper AES-XTS mode, on a byte boundary (not on the bit boundary).
Moreover, I've rebased the PR-branch to the development one to make it easier to merge. Tell me if you need anything else.

**Comment by flatz** [comment]
Hi,

Any news on this? Would be nice to see it in the latest development branch.

**Comment by pjbakker** [comment]
It's on our list. Currently we cannot provide an arrival date for this change yet.

**Comment by Patater** [comment]
Hi @Aorimn

I've extended this PR in #1602 and we'll work from there to get this contribution into the library. Thanks very much for your contribution!

**Pull request closed without merging**
