### PR TITLE
build: Makefile: misc cleanups

### PR DESCRIPTION
**Pull request by alonbl**
Few years ago I offered help to apply autotools build to polarssl and was rejected, autoconf/automake/libtool are the best tools available for multiplatform/crosscompile build environment. Writing standalone Makefiles is not easy, especially when the consumer are packagers that relay on some practice.

I still recommend autotools build system over anything else (including cmake) to enable flexibility required for such important infra library.

I got a request to help cross compile on Windows and post that fix, attached are some more to make the build closer to comply with best practice, I hope this will be sufficient at this point.

Thank you,

### CODE REVIEW

**Comment by alonbl** [comment]
ping

**Comment by mpg** [comment]
Sorry for not getting back to you earlier. I made a few line comments.

**Comment by mpg** [comment]
I cannot find back the other line comments so I'll follow up here regarding CFLAGS moving from `+=` to `=`. I'm afraid I cannot see the benefits of it. With `+=` you can do `CFLAGS=-foo make` to add to our default CFLAGS (resulting in `-foo -O2`) and `make CFLAGS=-foo` to override our default (resulting in `-foo`). With `=` you can only override, not preppend.

Also, I read [this section of the GNU make][1] as an indication that using the environment is encouraged, though not mandatory.

Except this detail, I like your changes with the introduction of LOCAL_CFLAGS and WARNING_CFLAGS.

[1]: https://www.gnu.org/software/make/manual/html_node/Environment.html

**Comment by alonbl** [comment]
ok, so if you accept the LOCAL_CFLAGS which are the mandatory flags for application and WARNING_CFLAGS which are optional compiler specific warnings.

we left with CFLAGS that are user customizable and we do not need to append anything, just to provide sane default if user has no preferences.

replacing CFLAGS entirely is the expected behaviour for downstream package management such as rpm, deb, ebuild. so having CFLAGS implemented this way makes package build system somewhat more expected.

**Comment by alonbl** [comment]
BTW: we can use both environment and argument using:

CFLAGS := -O2

**Comment by mpg** [comment]
I think I like `:=`. What I really don't like with plain assignment is silently discarding things from the user's environment, that just seems rude. Lemme think about it some more :)

**Comment by alonbl** [comment]
ok, you can now override LDFLAGS and CFLAGS via environment as well.

I moved the mingw fix to top, will look into it later.

**Comment by mpg** [comment]
Thanks! I've merged everything except the last commit in my personal branch and am running a few extra tests on it before I push.

Regarding mingw, I checked what the mingw wiki has to say about [building shared libraries][1], and they don't mention -fpic or -fPIC. Since the wiki looks like the official documentation, I would assume it's correct and -fpic is not needed for this target, which is what the compiler warning says.

[1]: http://www.mingw.org/wiki/sampledll

So unless you have new reliable information, as far as I am concerned our current build system is correct and there is no problem to be solved here.

**Comment by alonbl** [comment]
thanks!

I just curios why it works at my side and not at yours, it is not critical, but this is part of builtin gcc behaviour, should not be a change between various of targets.

will look at it.

**Comment by mpg** [comment]
Well the warning looks quite target-specific to me.

I *think* but am not sure that previously gcc tended to be silent about unused arguments and the new tendency is to give more warnings, or maybe even errors in the future, about that kind of thing. That could explain the difference if I'm using a newer version than yours. Otherwise, I'm just as perplexed as you :)

**Comment by alonbl** [comment]
I use gentoo... always the most recent :)

$ x86_64-w64-mingw32-gcc --version
x86_64-w64-mingw32-gcc (Gentoo Hardened 4.9.2 p1.0, pie-0.6.2) 4.9.2

**Comment by mpg** [comment]
Indeed. Well if you find out the explanation, please let me know, I'm quite curious!

**Comment by alonbl** [comment]
if you like, I can make an effort to convert the plain Makefile based build into autotools, the outcome will be much simpler in term of ease of maintenance, and more compatible with best practises. I believe that autotools provides the best solution for infra libraries, my experience is that good autotools based package is the most flexible and compatible to most environments including cross compile. but this is large effort so need confirmation before I start.

**Comment by mpg** [comment]
Thanks for the offer but we're not interested in moving to autotools. It is important for us to keep a "simple" build system, and we already have two actively maintained build systems, I don't think adding a 3rd would be a good idea in terms of maintenance costs. So I'm glad you asked before starting :)

**Comment by alonbl** [comment]
autotools should replace the Makefile build, which is not simple at all as you could see. it has many issues such as inability to create shared library on many system other than Linux (example: aix), it has severe issue of inconsistent build as left overs using flags X and new with flags Y are built, there is inability to add optional components properly and more.

actually, the autotools simplifies the build, make it much easier to maintain and use.

experience shows that as cmake is a newer build system it did not address the major issues, nor provide any actual benefit. had you chosen to leave only cmake I would have understood, but as long as you also maintaining Makefile it worth discussing.

see the recent work to make the Makefile actually behave slightly more expected... which could have been avoided if you were using autotools or at least could have been much simpler.

BTW: old thread was[1], and it seems not that trivial to keep maintaining "simple" Makefile.

[1] https://tls.mbed.org/discussions/generic/build-system

**Comment by mpg** [comment]
The make-based build system is not going away. IMO it has two essential qualities:

1. It's simple enough that everyone can understand it and hack it if necessary. This is not true of autotools nor cmake. 
2. It's more universal than any other option, in particular in the embedded word.

Now, regarding point 2 and one question you asked in the old thread, indeed we're not targeting only embedded environments, and it's hard to manually maintain a Make-based build system that works out-of-the-box on every Unix or Windows variant, but I think this is sufficiently mitigated by the availability of CMake as an alternative that works well in these environments, and the hackability of the Make-based system.

Looking at it another way, most projects only offer one option of build system, we're already offering two, a "ligth" and a "heavy", which I think is an excellent combo. Replacing make by autotools would result in two "heavy" systems which is no good, and regarding the choice of cmake vs autotools as the "heavy" system, I'm sure a huge amount has already been argued on the topic without reaching agreement.

I'd also like to point out that our code is quite portable, which makes the autoconf part of autotools much less interesting for us than for most projects. Overall, I'm not saying our selection of build systems is the best in general has no drawback but I honestly think it fits our particular needs pretty well.

I appreciate your contributions and am grateful for you offer, but I think we'll have to agree to disagree on this point.

**Comment by alonbl** [comment]
OK, your call.

I think you are wrong regarding the portability of your current Makefile
and cmake. But I guess you will see this if this library will be actually
used in large variant of target.

**Pull request closed without merging**
