### PR TITLE
Fix boolean values according to DER specs

### LINKED ISSUE #318: X.509 boolean values recognized on Windows and Linux, but not on OS X
I've created a self-signed CA with the `mbedtls_cert_write` command. This certificate works on Windows 10 and Fedora 21, but not on OS X 10.11 (El Capitan). 

The Basic Constraints extension critical flag is recognized on Windows, Linux, and with `openssl` command on Mac OS X 10.11, but not by OS X Keychain app: 

criticalflagosx

Also, the `CA` flag is not recognized on OS X.
Maybe OS X is expecting a value of `0xff` (255) for `TRUE`, not `1` ?

### PR DESCRIPTION
**Pull request by jleroy**
In BER encoding, any boolean with a non-zero value is considered as
TRUE. However, DER encoding require a value of 255 (0xFF) for TRUE.

This commit makes `mbedtls_asn1_write_bool` function uses `255` instead
of `1` for BOOLEAN values.

With this fix, boolean values are now reconized by OS X keychain (tested
on OS X 10.11).

Fixes #318.

### CODE REVIEW

**Comment by miklis** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by jleroy** [comment]
This commit break the `x509write` test, but I don't know how to fix that...

```
# ./test_suite_x509write
Certificate Request check Server1 SHA1 ............................ PASS
Certificate Request check Server1 SHA224 .......................... PASS
Certificate Request check Server1 SHA256 .......................... PASS
Certificate Request check Server1 SHA384 .......................... PASS
Certificate Request check Server1 SHA512 .......................... PASS
Certificate Request check Server1 MD4 ............................. ----
Certificate Request check Server1 MD5 ............................. PASS
Certificate Request check Server1 key_usage ....................... PASS
Certificate Request check Server1 ns_cert_type .................... PASS
Certificate Request check Server1 key_usage + ns_cert_type ........ PASS
Certificate Request check Server5 ECDSA, key_usage ................ PASS
Certificate write check Server1 SHA1 .............................. FAILED
  olen >= pem_len - 1

Certificate write check Server1 SHA1, key_usage ................... FAILED
  olen >= pem_len - 1

Certificate write check Server1 SHA1, ns_cert_type ................ FAILED
  olen >= pem_len - 1

Certificate write check Server1 SHA1, version 1 ................... PASS
X509 String to Names #1 ........................................... PASS
X509 String to Names #2 ........................................... PASS
X509 String to Names #3 (Name precisely 255 bytes) ................ PASS
X509 String to Names #4 (Name larger than 255 bytes) .............. PASS
X509 String to Names #5 (Escape non-allowed characters) ........... PASS
X509 String to Names #6 (Escape at end) ........................... PASS

----------------------------------------------------------------------------

FAILED (18 / 21 tests (1 skipped))
```

**Comment by yanesca** [comment]
I don't know the reason either, but I hope that this will be somewhat useful:

On my Linux system only a single test fails after your patch:
```
Certificate Request check Server5 ECDSA, key_usage ................ PASS
Certificate write check Server1 SHA1 .............................. PASS
Certificate write check Server1 SHA1, key_usage ................... FAILED
  memcmp( buf, check_buf, pem_len - 1 ) == 0

Certificate write check Server1 SHA1, ns_cert_type ................ PASS
Certificate write check Server1 SHA1, version 1 ................... PASS
X509 String to Names #1 ........................................... PASS
```
And it only fails because a bitwise comparison with a previously generated certificate. I think that the functionality is correct so replacing the reference certificate with a newly generated one would be a reasonable solution.

**Comment by jleroy** [comment]
@yanesca Thanks. I have reissued the certificate with the same parameters, and all test pass now.

The two others failed tests are caused by another modification on my side.

**Comment by mpg** [comment]
There should be a one byte difference between the old and new reference cert used in the test, but looking at the diff it looks like the difference is much more than that.

**Comment by jleroy** [comment]
I've compared the two certificates with an ASN.1 decoder.
Here's the diff: 

```Diff
--- old.asn	2015-10-14 13:56:37.000000000 +0200
+++ new.asn	2015-10-14 13:57:17.000000000 +0200
@@ -85,5 +85,5 @@
       OBJECTIDENTIFIER 1.2.840.113549.1.1.5 (sha1WithRSAEncryption)
       NULL 
    }
-   BITSTRING 0x5777271342dab133f783eba1265cbfc34d9377b70e17e6b3ce2a8e408c6212f2642672c19d9c8f76d74e134654d0fcd54360ab2ce4fcc1067ca8797741070fcbfdec7ed9becfc437cd78774502fc1656957a97f572278f1948ddb689ad15afb0925d47132ab9bf4b18176181902d17505517d7e4d90ad5d065ba54deda74661d4583bcd327febdfe60e350340c88b776174b1751fb50f0f07d4c2417941c917c34caab9eb33726c6f0809f19e00142a8152f7bd565828c2a3c94ccce5ce8de0309a26e2853f5705a6d5ccdd70de039f4816e91c58bbef46d681b28f5ae72c14ab6fad71ad2d541e2a47c8d6520c59679d76f90c596048a85ae40412cb388e3e0 : 0 unused bit(s)
+   BITSTRING 0x1282ff5c749b9ec46381f8d76b9ede08425a0834ed571129a9a75124ecb67a88e53d264afb8faf184835d401eb7eb489b72d0645cfdd2f6bc461e251d78afc9ab162cd986a60ace744d25a9a27a781f37268ecc356205ec43aa66630933534df3aacdfad60b7b2523b32f674dd088f0232e3ba9f2d06ff017857d889acee006ea95a58a89b921d1d2ab0dfdce9680813722b6cad4c07a0894e4c417dc49ce44e285080479b0c3e45254b39cccc9c6937535ddd99f1b49dd84cb6b332cb1059652530a192e3459e89e661d2bfe93ca28d4f6107a28af3443f9de681569885ad202d4224eb3341469635b949b143e45048c23260f05bd5179d1e7dacf049769a5a : 0 unused bit(s)
 }
```

**Comment by mpg** [comment]
Oh yes, sure, the signatures are different, obviously. Embarrassing that I didn't realise that immediately. Thanks for checking!

**Pull request merged**
