### PR TITLE
Remove deprecated functions for Mbed TLS 3.0

### PR DESCRIPTION
**Pull request by ShobhitSamuelSingh**

### CODE REVIEW

**Comment by daverodgman** [comment]
Implements #4029

**Comment by mpg** [comment]
@ShobhitSamuelSingh Thanks for your contribution, it's good to see people making use of the "good first issue label"!

However, I'm afraid the changes you made are not those that we intended: we want to entirely remove the functions that are currently deprecated. That is, when you see block
```
#if ! defined(MBEDTLS_DEPRECATED_REMOVED)
...
#endif              
```
we want to entirely remove that block from the code base.

**Comment by mpg** [comment]
Note: as @yanesca mentioned earlier, we hadn't create the branch for 3.0 work when you created your PR. Now we have, so I've updated your PR to point the correct branch.

**Comment by ShobhitSamuelSingh** [comment]
Okay...thanks for the help but I'm still learning so can't figure out what to do.

**Pull request closed without merging**
