### PR TITLE
Feature/transparent test driver

### PR DESCRIPTION
**Pull request by carlaageamundsen**
Notes:
* Pull requests cannot be accepted until the PR follows the [contributing guidelines](../CONTRIBUTING.md). In particular, each commit must have at least one `Signed-off-by:` line from the committer to certify that the contribution is made under the terms of the [Developer Certificate of Origin](../dco.txt).

## Description
This pull request implements a test driver for transparent signatures as specified in https://github.com/ARMmbed/mbedtls/issues/3344
The driver implements functions for key generation, obtaining the public key, signing a hash, verifying a hash  It uses Mbed TLS functions internally to perform the calculation.

A unit test suite is included to validate the functions, and a component is added to tests/scripts/all.sh that runs the unit tests.

## Status
**READY**

## Requires Backporting
NO  

## Migrations
NO

## Steps to test or reproduce
The unit test can be executed with the following command from the mbedtls base directory:
$ tests/scripts/all-in-docker.sh test_transparent_test_driver

### CODE REVIEW

**Comment by carlaageamundsen** [comment]
Who should review this PR? I see that @ronald-cron-arm is already listed as reviewer. Should we add another reviewer?
Do I need to do anything in order to start the review?

**Comment by ronald-cron-arm** [comment]
From our last sync, I was rather expecting you addressing the comments on #3526 and thus review #3526 before this one. Did you take into account the comments made by @gilles-peskine-arm in #3526 for the new version of this PR?

**Comment by carlaageamundsen** [comment]
Hi @ronald-cron-arm .  I intentionally addressed this PR (my own) before https://github.com/ARMmbed/mbedtls/pull/3526  (https://github.com/kjeir) since I did not want you to spend time commenting on the same issues all over again. My work, the transparent test driver, is based on the opaque test driver that Kjell Eirik worked on (before me), so about half of your comments (if not more) apply to this PR as well. I did actually mention my intention in the sync meeting on Monday. This plan was also the most practical at that time since I did not have write access to Kjell Eirik's repo. However since then I have accepted an invitation to access his repo so I should be able to do the same updates in the opaque test driver now,, and that should be faster. Of course, there seem to be a significant set of comments that are specific to the opaque test driver and I may need to investigate some background rational, including potential chats with Kjell Eirik.

**Comment by ronald-cron-arm** [comment]
Ok, thanks for the clarification. I just got it wrong during the meeting then, no worries. I will review this one tomorrow then with an eye on what has been going on in #3526.

**Comment by ronald-cron-arm** [comment]
I am confused. How does this PR relate to #3501? They implement both the same transparent driver functions namely: generate_key(), sign_hash(), verify_hash(). Is this PR supposed to be a clean-up of what is done in #3501? Why would we merge the two PRs?

**Comment by carlaageamundsen** [comment]
In PR https://github.com/ARMmbed/mbedtls/pull/3501 @stevew817  needed an initial minimal transparent test driver for testing. Then I was assigned https://github.com/ARMmbed/mbedtls/issues/3344 to implement a more extended transparent test driver, analogous to the opaque test driver that Kjell Eirik implemented in https://github.com/ARMmbed/mbedtls/issues/3343. I agree it is somewhat confusing. My first reaction was that Steven had already implemented a lot of  https://github.com/ARMmbed/mbedtls/issues/3344, but the intention was to extend and add a test suite directly on top of the transparent test driver, similar to what Kjell Eirik did for the opaque test driver.

**Comment by ronald-cron-arm** [comment]
I am closing this PR as we don't intend to review and merge it. We already have a transparent test driver with key generation, public key export and sign/verify entry points. Otherwise, the testing of driver implementations is not something we've planned to do now.

**Pull request closed without merging**
