### PR TITLE
Use current cmake directory instead of source root directory when exu…

### PR DESCRIPTION
**Pull request by schwabe**
…ting config.pl

When mdbedtls is added as a subdirectory to another project this will call config.pl with the right path
If mbedtls is build standalone current and root source directory are identical

### CODE REVIEW

**Comment by RonEld** [comment]
Hi @schwabe Thank you for suggesting a fix. I believe this addresses issue #541 which #589 should have resolvedit.
We will look into this

**Comment by schwabe** [comment]
@RonEld #589 fixes out of tree builds. This is a about when medtls is use as a subdirectory in another project as library that is build as part of another project (add_subdirectory(mbedtls)). #589 is actually a prequisite for this patch. 

${CMAKE_SOURCE_DIR} and ${CMAKE_CURRENT_SOURCE_DIR} are identical if mbedtls is build standalone but differ when it is used as part of another project ${CMAKE_SOURCE_DIR} will point to the root of the parent project.

If you want I can create a minimal working example to demonstrate the issue.

**Comment by RonEld** [comment]
@schwabe Thank you for your clarifications!

**Comment by gilles-peskine-arm** [comment]
Hi @schwabe , rather than calling `config.pl` from the source directory, I'd rather create a symbolic link in the build directory. The reason I prefer this is that it's needed to do SSL testing in out-of-tree builds (`ssl-opt.sh` calls `config.pl`). I opened a PR for that at #1470 . Would that approach also work in your case?

**Comment by schwabe** [comment]
@gilles-peskine-arm your PR seems also to use CMAKE_CURRENT_SOURCE_DIR instead CMAKE_SOURCE_DIR so should for me. My problem is that CMAKE_SOURCE_DIR is wrong variable when used as subproject (If it is not a subproject both variables are identical)

**Comment by gilles-peskine-arm** [comment]
Thanks @schwabe. On second thoughts, here the binary directory isn't required so we might as well stick to calling `config.pl` in the source directory, so I'm for merging exactly your patch.

How hard would it be to create a minimal example for this? We're working on improving our testing of build environments and it would be nice to have a non-regression test so that we don't break this again in the future.

**Comment by gilles-peskine-arm** [comment]
Gatekeeper note: this should be merged into `mbedtls-2.7` and `development`. No 2.1 backport since 2.1 didn't do the problematic check.

**Comment by schwabe** [comment]
Minimal examples:

Folder test with: test.c (empty) mbedtls (git clone of this) and CmakeLists.txt:

```
cmake_minimum_required(VERSION 3.4.1)

add_subdirectory(mbedtls)
add_executable(testpgm test.c)
target_link_libraries(testpgm mbedtls)
```
```
 cmake .
Can't open perl script "/Users/arne/tmp/test/scripts/config.pl": No such file or directory
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/arne/tmp/test
```

with the patch applied:
```
 cmake .
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR) 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/arne/tmp/test
```

Ignore the openssl errors that is probably OS X related

**Comment by gilles-peskine-arm** [comment]
Thanks for your help. https://github.com/ARMmbed/mbedtls/pull/1073 is now merged with an identical patch, so I'm closing this PR. We're tracking the need for a test for that in our CI in #1482, your scenario description will be useful for that.

**Pull request closed without merging**
