### PR TITLE
Use mbedtls_time instead of libc's time in mbedtls_ssl_cache_set

### PR DESCRIPTION
**Pull request by AntonBikineev**

### CODE REVIEW

**Comment by andresag01** [comment]
This PR fixes issue https://github.com/ARMmbed/mbedtls/issues/666.

**Comment by RonEld** [comment]
same fix as https://github.com/ARMmbed/mbedtls/pull/874

**Comment by RonEld** [comment]
Hi @AntonBikineev Thanks for your contribution!
In addition, unfortunately our policy is to not accept contributions, without a Contributor’s Licence Agreement (CLA) signed or authorised by yourself or your employer.
If this is a personal contribution, the easiest way to do this is if you create an mbed account and [accept this click through agreement](https://developer.mbed.org/contributor_agreement/). Alternatively, you can find a [slightly different agreement to sign here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/), which can be signed and returned to us, and is applicable if you don't want to create an mbed account or alternatively if this is a corporate contribution.
Thanks for your understanding and again, thanks for the contribution!
I apologize if you have already signed the CLA which I have missed

**Comment by sbutcher-arm** [comment]
Bug #666 has now beed resolved, so this can be closed.

Thanks for the contribution and support of the project!

**Pull request closed without merging**
