### PR TITLE
Backport 3.6: Fix some test case dependencies (PEM_C)

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Fix some test case dependencies:

* `pk_parse_keyfile_rsa` not getting executed
* redundancy on `mbedtls_x509_crl_info`

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** no (tests only)
- [x] **development** https://github.com/Mbed-TLS/mbedtls/pull/9049
- [x] **2.28 backport** https://github.com/Mbed-TLS/mbedtls/pull/8929 (came first)
- [x] **tests** provided

### CODE REVIEW

**Review by mpg — DISMISSED** [review]
Faithful backport

**Review by minosgalanakis — APPROVED** [review]
LGTM

**Review by mpg — APPROVED** [review]
Approving as a faithful backport.

**Review by mpg — COMMENTED** [review]
I'm happy with the DER files, but it we want to insist that files named `rsa_pkcs1_*` be plain PKCS1, not wrapped in PKCS8, then I'll note the PEM version of the new keys (768-784 bits) look like PKCS8 to me. (The pre-existing ones, 1024-4096, look like plain PKCS1 though.)

**Comment by gilles-peskine-arm** [comment]
> the PEM version of the new keys (768-784 bits) look like PKCS8 to me. (The pre-existing ones, 1024-4096, look like plain PKCS1 though.)

_sigh_ Thanks for noticing. `openssl genrsa` changed in OpenSSL 3.0, like `openssl rsa`. I've fixed the files I generated with OpenSSL 3.0 to be what they say on the tin. Having portable instructions in the makefile is out of scope here, so I just added a note in a comment.

**Review by mpg — APPROVED** [review]
LGTM.

```sh
for i in rsa_pkcs1_*_clear.pem; do
printf "$i: "; openssl rsa -noout -text -in $i | head -n1
openssl asn1parse -inform pem -in $i > $i.parse
j=${i%.pem}.der
openssl asn1parse -inform der -in $j > $j.parse
diff $i.parse $j.parse
! grep OBJECT $i.parse
done
```
```
rsa_pkcs1_1024_clear.pem: RSA Private-Key: (1024 bit, 2 primes)
rsa_pkcs1_2048_clear.pem: RSA Private-Key: (2048 bit, 2 primes)
rsa_pkcs1_4096_clear.pem: RSA Private-Key: (4096 bit, 2 primes)
rsa_pkcs1_768_clear.pem: RSA Private-Key: (768 bit, 2 primes)
rsa_pkcs1_769_clear.pem: RSA Private-Key: (769 bit, 2 primes)
rsa_pkcs1_770_clear.pem: RSA Private-Key: (770 bit, 2 primes)
rsa_pkcs1_776_clear.pem: RSA Private-Key: (776 bit, 2 primes)
rsa_pkcs1_784_clear.pem: RSA Private-Key: (784 bit, 2 primes)
```

**Pull request merged**
