### PR TITLE
PSA: Rename AEAD tag length macros

### PR DESCRIPTION
**Pull request by bensze01**
This PR renames the AEAD tag length macros that were renamed in the PSA crypto API spec between Beta 3 and 1.0.0

Fixes parts of #3278

## Status
**READY**

## Requires Backporting
No, PSA only

## Migrations
Yes, This brings them in line with PSA Crypto API 1.0.0

`PSA_ALG_AEAD_WITH_DEFAULT_TAG_LENGTH `-> `PSA_ALG_AEAD_WITH_DEFAULT_LENGTH_TAG`
`PSA_ALG_AEAD_WITH_TAG_LENGTH`                 -> `PSA_ALG_AEAD_WITH_SHORTENED_TAG`

### CODE REVIEW

**Comment by bensze01** [comment]
#3984 Is dealing with an overlapping set of macros. Once the relevant parts of this PR are merged into that one (which I've already requested), I'll drop the overlapping changes, and refocus this PR on renaming `PSA_ALG_AEAD_WITH_DEFAULT_TAG_LENGTH` -> `PSA_ALG_AEAD_WITH_DEFAULT_LENGTH_TAG`
`PSA_ALG_AEAD_WITH_TAG_LENGTH` -> `PSA_ALG_AEAD_WITH_SHORTENED_TAG`, which would have been out of scope in the first place.

**Comment by bensze01** [comment]
I've pushed a new version of the PR that removes the overlaps with #3984

**Comment by bensze01** [comment]
I've rebased this PR on top of develoment.

**Review by ronald-cron-arm — CHANGES_REQUESTED** [review]
There is one remaining usage of the PSA_ALG_AEAD_WITH_TAG_LENGTH in tests/scripts/set_psa_test_dependencies.py that was introduced by PR 4012. Otherwise this looks good to me.

**Comment by bensze01** [comment]
Rebased PR again, and updated to account for new occurrences of `PSA_ALG_AEAD_WITH_TAG_LENGTH` added in #4010 and #4012

**Review by ronald-cron-arm — APPROVED** [review]
LGTM

**Review by gabor-mezei-arm — APPROVED** [review]

**Pull request merged**
