### PR TITLE
Backport 2.7: Documentation error in `mbedtls_ssl_get_session`

### PR DESCRIPTION
**Pull request by RonEld**
## Description
Backport of #927 to mbedtls-2.7

## Status
**READY**

### CODE REVIEW

**Comment by RonEld** [comment]
Ported latest commit in the main PR

cc @sbutcher-arm @andresag01 @mpg

**Comment by andresag01** [comment]
@RonEld: The main PR has not been approved. As there are some change requests there, I will wait until after that is resolved before reviewing this PR.

**Comment by RonEld** [comment]
@andresag01 The main PR is now approved, and I have pushed the latest commit

**Comment by RonEld** [comment]
@gilles-peskine-arm I fixed the issue in the ChangeLog. It was caused by an erronous cherry-pick which I have missed

cc @mazimkhan

**Pull request merged**
