### PR TITLE
Address issues found by Coverity

### PR DESCRIPTION
**Pull request by hanno-arm**
__Summary:__ This PR addresses three issues raised by the latest Coverity run, some of which are new, and some of which are partially pre-existing. Specifically:

1) [new] `mbedtls_rsa_import_raw` used an uninitialized return value when it was called without any input parameters. While not very progressive, this use-case is allowed and should be a succeeding no-op. Also, a test should be added to document the behavior in this case.

2) [pre-existing] The MPI test for prime generation missed a return value check for a call to `mbedtls_mpi_shift_r`. This is neither critical nor new but it's cleaner to be consistent and check all return values.

3) [pre-existing but amplified by RSA changes] Both the RSA keygeneration example program and the RSA test suites contained code initializing an RSA context after a potentially failing call to CTR DRBG initialization, leaving the corresponding RSA context free call in the cleanup section of the respective function orphaned. This existed before but Coverity picked up on it again because of newly introduced MPI's that were also wrongly initialized only after the call to CTR DRBG init. The commit fixes both the old and the new issue by moving the initializtion of both the RSA context and all MPI's prior to the first potentially failing call.

### CODE REVIEW

**Comment by andresag01** [comment]
@hanno-arm: Do the RSA changes work with Visual Studio? I was working on something else and noticed that if I ran `./scripts/generate_visualc_files.pl` I get the following diff:
```
diff --git a/visualc/VS2010/mbedTLS.vcxproj b/visualc/VS2010/mbedTLS.vcxproj
index 65730cd..1027266 100644
--- a/visualc/VS2010/mbedTLS.vcxproj
+++ b/visualc/VS2010/mbedTLS.vcxproj
@@ -199,6 +199,7 @@
     <ClInclude Include="..\..\include\mbedtls\platform_time.h" />
     <ClInclude Include="..\..\include\mbedtls\ripemd160.h" />
     <ClInclude Include="..\..\include\mbedtls\rsa.h" />
+    <ClInclude Include="..\..\include\mbedtls\rsa_internal.h" />^M
     <ClInclude Include="..\..\include\mbedtls\sha1.h" />
     <ClInclude Include="..\..\include\mbedtls\sha256.h" />
     <ClInclude Include="..\..\include\mbedtls\sha512.h" />
@@ -267,6 +269,7 @@
     <ClCompile Include="..\..\library\platform.c" />
     <ClCompile Include="..\..\library\ripemd160.c" />
     <ClCompile Include="..\..\library\rsa.c" />
+    <ClCompile Include="..\..\library\rsa_internal.c" />^M
     <ClCompile Include="..\..\library\sha1.c" />
     <ClCompile Include="..\..\library\sha256.c" />
     <ClCompile Include="..\..\library\sha512.c" />
```

**Comment by hanno-arm** [comment]
@andresag01 Thanks for spotting that, yet I'm puzzled that running this script is not part of our CI.

**Comment by andresag01** [comment]
@hanno-arm: That is a good point. @mazimkhan, @dgreen-arm is `./scripts/generate_visualc_files.pl` part of our Ci scripts? Perhaps part of the Windows testing scripts that @dgreen-arm was working on last year?

**Comment by mpg** [comment]
I think it should be added to  `tests/scripts/check-generated-files.sh` as it's what it is (generated files) and this script is already run by the CI (part of all.sh and other CI jobs I guess). I created IOTSSL-2003 to track this issue.

**Comment by Patater** [comment]
When I ran `bump_version.sh`, it also updated the `vcxproj` file in the same way.

```diff
diff --git a/visualc/VS2010/mbedTLS.vcxproj b/visualc/VS2010/mbedTLS.vcxproj
index 65730cd..1027266 100644
--- a/visualc/VS2010/mbedTLS.vcxproj
+++ b/visualc/VS2010/mbedTLS.vcxproj
@@ -199,6 +199,7 @@
     <ClInclude Include="..\..\include\mbedtls\platform_time.h" />
     <ClInclude Include="..\..\include\mbedtls\ripemd160.h" />
     <ClInclude Include="..\..\include\mbedtls\rsa.h" />
+    <ClInclude Include="..\..\include\mbedtls\rsa_internal.h" />^M
     <ClInclude Include="..\..\include\mbedtls\sha1.h" />
     <ClInclude Include="..\..\include\mbedtls\sha256.h" />
     <ClInclude Include="..\..\include\mbedtls\sha512.h" />
@@ -267,6 +269,7 @@
     <ClCompile Include="..\..\library\platform.c" />
     <ClCompile Include="..\..\library\ripemd160.c" />
     <ClCompile Include="..\..\library\rsa.c" />
+    <ClCompile Include="..\..\library\rsa_internal.c" />^M
     <ClCompile Include="..\..\library\sha1.c" />
     <ClCompile Include="..\..\library\sha256.c" />
     <ClCompile Include="..\..\library\sha512.c" />
```

**Pull request merged**
