### PR TITLE
Use socklen_t on Android

### LINKED ISSUE #2977: compile time warning when building net_sockets.h on Android
### Description
- Type: Bug
- Priority: Minor
Raised in the [forum](https://forums.mbed.com/t/how-to-avoid-warning-passing-int-to-parameter-of-type-socklen-t-aka-unsigned-int-converts-between-pointers-to-integer-types-with-different-sign-wpointer-sign/6638) by pii

---------------------------------------------------------------
## Bug

**OS**  
Android

**mbed TLS build:**  
Version: 2.16.3
OS version: Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/

**Expected behavior**   
Build finishes without any warning
**Actual behavior**  
Build warning because neither `#if defined(__socklen_t_defined) || defined(_SOCKLEN_T) ||  \
    defined(_SOCKLEN_T_DECLARED) || defined(__DEFINED_socklen_t)` is defined:
~~~
External/.build_area/mbedtls-2.16.3/library/net_sockets.c:332:37: warning: passing 'int *'
      to parameter of type 'socklen_t *' (aka 'unsigned int *') converts between pointers to integer types with
      different sign [-Wpointer-sign]
                    (void *) &type, &type_len ) != 0 ||
                                    ^~~~~~~~~
/Users/pi/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/sys/socket.h:311:92: note: 
      passing argument to parameter '__value_length' here
__socketcall int getsockopt(int __fd, int __level, int __option, void* __value, socklen_t* __value_length);
                                                                                           ^
External/.build_area/mbedtls-2.16.3/library/net_sockets.c:342:80: warning: passing 'int *'
      to parameter of type 'socklen_t *' (aka 'unsigned int *') converts between pointers to integer types with
      different sign [-Wpointer-sign]
                                             (struct sockaddr *) &client_addr, &n );
~~~
`getsockopt` receives 'socklen_t *' (aka 'unsigned int *') , however since none of the precompilation checks is defined, `int` is sent as parameter

### PR DESCRIPTION
**Pull request by okhowang**
Fixes #2977

Signed-off-by: okhowang(王沛文) <okhowang@tencent.com>

Notes:
* Pull requests cannot be accepted until the PR follows the [contributing guidelines](../CONTRIBUTING.md). In particular, each commit must have at least one `Signed-off-by:` line from the committer to certify that the contribution is made under the terms of the [Developer Certificate of Origin](../dco.txt).
* This is just a template, so feel free to use/remove the unnecessary things
## Description
Use socklen_t on Android

## Status
READY

## Requires Backporting
NO  

## Migrations
NO

## Todos
- [ ] Tests
- [ ] Documentation
- [x] Changelog updated
- [ ] Backported

### CODE REVIEW

**Comment by ronald-cron-arm** [comment]
CI is failing because check_files.py is not happy:
Missing newline at end of file:
ChangeLog.d/android-socklen_t.txt
Otherwise, did you check this under an Android build environment?

**Comment by okhowang** [comment]
> Missing newline at end of file:
ChangeLog.d/android-socklen_t.txt

fixed

> did you check this under an Android build environment?

Yes, test with ndk r13.

**Comment by ronald-cron-arm** [comment]
In #2977 using _POSIX_VERSION was suggested by @gilles-peskine-arm. This could potentially have a broader impact than ANDROID. Did you try it?

**Comment by okhowang** [comment]
`_POSIX_VERSION` is ok for android. I have modify condition to `defined(_POSIX_VERSION)`

**Comment by ronald-cron-arm** [comment]
Another question: no need to check that the POSIX_VERSION is high enough? Has `socklen_t` been included in the Posix spec from the start.

**Comment by okhowang** [comment]
the `socklen_t` defined in [POSIX.1-2004 or IEEE Std 1003.1-2004](https://pubs.opengroup.org/onlinepubs/009695399/)
which `_POSIX_VERSION` is `200112L`
I couldn't found public older specific, for example POSIX.1-2001.
I have modify marco to `#if _POSIX_VERSION >= 200112L`

**Review by ronald-cron-arm — APPROVED** [review]
Thanks for the changes and answering my questions. LGTM.

**Review by gabor-mezei-arm — APPROVED** [review]

**Pull request merged**
