### PR TITLE
Add support for New Hope, Salsa20 and ChaCha8

### PR DESCRIPTION
**Pull request by dmjones500**
## Description

Introduces support for [New Hope key exchange](https://eprint.iacr.org/2015/1092), which is believed to be quantum resistant. Also adds support for Salsa20 and ChaCha8 stream ciphers.

## Status
**READY**

## Requires Backporting
NO  

## Migrations
NO

## Additional comments
Note that the values defined in `include/mbedtls/ssl_ciphersuites.h` are the next unassigned values [from IANA](https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-4). There does not yet appear to be agreed values for these ciphersuites.

### CODE REVIEW

**Comment by RonEld** [comment]
Hi @dmjones500 Thank you for this contribution!
Please note that two of the CIs have failed, please look into that:
~~~
/builds/ws/mbedtls/9e682cfe/yotta/module/source/salsa20.c:89:6: error: conflicting types for 'mbedtls_salsa20_setup'
08:13:06  void mbedtls_salsa20_setup( mbedtls_salsa20_context *ctx, const unsigned char *key,
08:13:06       ^~~~~~~~~~~~~~~~~~~~~
08:13:06 In file included from /builds/ws/mbedtls/9e682cfe/yotta/module/source/salsa20.c:30:0:
08:13:06 /builds/ws/mbedtls/9e682cfe/yotta/module/mbedtls/salsa20.h:95:6: note: previous declaration of 'mbedtls_salsa20_setup' was here
08:13:06  void mbedtls_salsa20_setup( mbedtls_salsa20_context *ctx, const unsigned char *key,
08:13:06       ^~~~~~~~~~~~~~~~~~~~~
~~~
and:
~~~
The command "tests/scripts/recursion.pl library/*.c" exited with 0.
0.02s$ tests/scripts/check-generated-files.sh
Duplicated error code: 0x5080 (MBEDTLS_ERR_NEWHOPE_BAD_INPUT_DATA)
The command "tests/scripts/check-generated-files.sh" exited with 29.
0.06s$ tests/scripts/check-doxy-blocks.pl
The command "tests/scripts/check-doxy-blocks.pl" exited with 0.
0.25s$ tests/scripts/check-names.sh
Analysing source code...
1250 macros
     156 enum-consts
tests/scripts/list-identifiers.sh: oops, lost some identifiers
The command "tests/scripts/check-names.sh" exited with 1.
~~~
In addition, I have a couple of general comments:
1. Note our alternative algorithm support philosophy has changed a bit.  The API is now outside the `XXX_ALT` directive.lok at https://github.com/ARMmbed/mbedtls/pull/867 for reference
2. This contribution is consisted of a large amount of files, so it would take some time to review it all. WIll it be possible to split this PR into (at least) three differnt PRs? (e.g. chacha, poly and newhope ciphersuite support?). This way they can be merged much quicker and easier.

Thank you again for your contribution!

**Comment by dmjones500** [comment]
Hi @RonEld. I've resolved most build issues, except for the `tests/scripts/check-generated-files.sh` test. I cannot reproduce the errors on my system, yet Travis consistently fails. Have you encountered similar problems before?

**Comment by RonEld** [comment]
Hi @dmjones500 
`*error.c*` and `*version_features.c*` are auto generated files. Have you inserted the new error codes manually? It seems that `error.c` is different than what is auto generated, and this is probably reason for error.
Please run `scripts/generate_errors.pl` and `scripts/generate_features.pl` 

In addition, would you mind splitting this PR into several PRs, in order for these features to be handled faster and separately?

**Comment by dmjones500** [comment]
@RonEld Yes, I'll work on splitting up the PR.

Re. the failing test, I already generated both files automatically. I wonder if there's something in the environment that causes the file to be generated in a different order. I'll see if I can uncover the cause; it seems to be to do with pk.h appearing before or after pkcs12.h and pkcs5.h.

**Comment by dmjones500** [comment]
@RonEld To make it easier for you guys to review, we've decided to hold fire on splitting up the PR and will pick this back up when there are some post-quantum IANA ciphersuites to aim towards. We'll keep [our fork](https://github.com/thales-e-security/mbedtls) up-to-date with your development branch, so anyone interested in experimenting with New Hope can try it out there.

If you're happy, I'll leave this PR open and we can revisit it in the future when standards have progressed.  Does that sound ok to you?

**Comment by RonEld** [comment]
HI @dmjones500 
It is ok to leave this PR open, and keep your fork up to date is blessed. We believe that Chacha and Salsa should be in different PRs as they are used in other cipher-suites and standards as well, and as such it would be highly appreciated if they were to be split to other PRs. 
Nevertheless, we understand you have your own considerations and priorities.

**Comment by dmjones500** [comment]
We will maintain a fork with this change here: https://github.com/thales-e-security/mbedtls

**Pull request closed without merging**
