### PR TITLE
adjusting size of sliding window array to correct size.

### LINKED ISSUE #3591: Stack usage in sliding-window exponentiation
The sliding window for the sliding-window exponentiation is allocated (on the stack) with:

`W[ 2 << MBEDTLS_MPI_WINDOW_SIZE ]`

this should (most likely) be:

`W[ 1 << MBEDTLS_MPI_WINDOW_SIZE ]`

I ran the tests with this modification and they passed. To ensure the tests would catch actually fail if the array would be to small, I also ran them with a `W[ (1 << MBEDTLS_MPI_WINDOW_SIZE) - 1]`, and they failed as expected.

This change will also reduce stack usage (during this function), by nearly a factor of 2! 🤩

The PR #3592 contains the modification.

### PR DESCRIPTION
**Pull request by d-otte**
Probably the `W[2 << MBEDTLS_MPI_WINDOW_SIZE]` notation is based on a transcription of 2**MBEDTLS_MPI_WINDOW_SIZE.

This PR fixes #3591 [edited by mpg to use github keyword]

## Status
**READY**

## Requires Backporting
This change is easy to backport, but is not strictly required.

I would recommend to backport it to all LTS branches.

## Migrations
No API changes

## Additional comments
This change would improve stack usage significantly.

## Todos
- [x] Changelog updated
- [x] Backported

### CODE REVIEW

**Review by mpg — COMMENTED** [review]
Other that the things already pointed out by Gilles, this looks good to me. Thanks for spotting and fixing this!

With the default configuration, the stack saving is `64 * sizeof (mbedtls_mpi)` which appears to be 768 bytes on ARMv6-M and 1536 bytes and x86-64. That's quite significant, so I agree that it would be great to have this backported, as there is no drawback.

**Comment by d-otte** [comment]
Now, back from vacation, I included your recommendations. I also changed the notation in the comment from `2 << MBEDTLS_MPI_WINDOW_SIZE` to `2 ** MBEDTLS_MPI_WINDOW_SIZE`. I found several occasions in other source files which use `**` to denote exponentiation.

Since some time had passed, should I rebase my changes?

**Comment by gilles-peskine-arm** [comment]
Thanks for updating. You don't need to rebase, but you can if you want. Rebasing after review makes it harder to review large changes, but this is a very small change so here it isn't an issue.

Please note that all commits must have a signed-off-by line to indicate that you warrant that you have the right to submit it. We can't accept the pull request if the DCO check fails.

**Review by mpg — CHANGES_REQUESTED** [review]
Thanks for making the suggested changes. Looks good to me except for two things:

1. I think this deserves a ChangeLog entry, saving 768 of stack in the default config in 32-bit platforms is significant. (As Gilles suggested earlier, I think the "Changes" section is appropriate.)
2. As Gilles pointed out, we need the Signed-Off-By line in the last two commits as well.

**Comment by d-otte** [comment]
I added the `Signed-off-by:` lines, but had to force the push. I hope this does not confuse the history to much.

Thanks for reminding me to take credit in the ChangeLog 😆. 

I used the description *significant* to designate the improvement, since it might vary from platform to platform. `sizeof(mbedtls_mpi)` depends on the size of `int` , `size_t`, `mbedtls_mpi_uint` and maybe alignment or padding, but the most common cases will indeed be 768 byte for 32-bit systems and 1536 bytes for 64-bit systems.

**Review by mpg — APPROVED** [review]
Looks all good to me.

**Review by gilles-peskine-arm — APPROVED** [review]

**Comment by gilles-peskine-arm** [comment]
Thanks! Would you mind submitting backports to `mbedtls-2.16` and `mbedtls-2.7` as well?

**Comment by d-otte** [comment]
> Would you mind submitting backports to mbedtls-2.16 and mbedtls-2.7 as well?
I will try to get this done today. But since I will probably be away the next seven weeks, maybe someone else has to finish this.

Should I base my changes on the `mbedtls-2.16` and `mbedtls-2.7` branch and create two dedicate PRs?

And I'm a bit unsure about the Mbed OS Testing failures. Do I have to care about them? I can't view the details, so I have no idea what they are about.

**Comment by mpg** [comment]
> I will try to get this done today. But since I will probably be away the next seven weeks, maybe someone else has to finish this.

Ok, if you can create backports before you go, that would be very helpful and we'll be sure to review them quickly, otherwise we'll take care of the backports.
 
> Should I base my changes on the `mbedtls-2.16` and `mbedtls-2.7` branch and create two dedicate PRs?
> 
Precisely! The description of the new PRs can be just "Backport of #3592 to the xxx branch." (Usually `git cherry-pick` is helpful creating backports.)

> And I'm a bit unsure about the Mbed OS Testing failures. Do I have to care about them? I can't view the details, so I have no idea what they are about.

Thanks for asking, but you don't need to care about them, we're actually going to remove them from our CI, see #3650

**Pull request merged**
