### PR TITLE
Fix check-doxy-blocks.pl to run from root dir

### PR DESCRIPTION
**Pull request by andresag01**
Modify tests/scripts/check-doxy-blocks.pl to ensure that:
* It can only be run from the mbed TLS root directory.
* An error code is returned to the environment when a potential error
    in the source code is found.

### CODE REVIEW

**Comment by andresag01** [comment]
The CI is failing because this PR fixes a bug in the check-doxy-blocks.pl script that uncovers other issues. Therefore, the test scripts fail. I have created a separate PR to deal with this issue:
https://github.com/ARMmbed/mbedtls/pull/721

**Comment by andresag01** [comment]
I recommend that the PR https://github.com/ARMmbed/mbedtls/pull/721 is merged **before** this one, otherwise the CI will fail in future tests.

**Comment by sbutcher-arm** [comment]
Reviewed, approved, merged into `development`.

@andresag01 - Why did you close this? It looks like a mistake.

**Comment by andresag01** [comment]
@sbutcher-arm: Its because I moved it here: https://github.com/ARMmbed/mbedtls/pull/841. Also, there is a backport:
2.1: https://github.com/ARMmbed/mbedtls/pull/842

**Pull request closed without merging**
