### PR TITLE
Allow to forward declare of mbedtls_blowfish_context #1215

### PR DESCRIPTION
**Pull request by gelldur**
## Status
**READY**
## Requires Backporting
NO  
## Migrations
NO

### CODE REVIEW

**Comment by gelldur** [comment]
For issue: #1215

**Comment by gelldur** [comment]
Probably I should extend this PR for other such structs.

**Comment by yanesca** [comment]
@gelldur First of all thank you for your contribution! I agree, it would be best to extend other such structs too, because the issue (#1215) mentioned this as a general problem and blowfish was just an example.

**Comment by gelldur** [comment]
@yanesca I added (i think) all needed forward declares

**Comment by yanesca** [comment]
@gelldur Thanks for extending the fix! Could you please extend it a little bit further? I was thinking about these structures:
```
mbedtls_x509_crt_profile                                                        
mbedtls_havege_state                                                            
mbedtls_oid_descriptor_t                                                        
mbedtls_aes_xts_context                                                         
mbedtls_mpi                                                                     
mbedtls_pk_rsassa_pss_options                                                   
mbedtls_pk_debug_item                                                           
mbedtls_entropy_source_state                                                    
mbedtls_net_context
```

**Comment by yanesca** [comment]
(There are some other structs in `_internal` headers, but those shouldn't be used by the application anyway and therefore it is safe to leave them as they are.  Preventing the forward declaration even has a function in this case as it further discourages the use of the internal headers.)

**Comment by gelldur** [comment]
@yanesca I updated. I'm not sure about your last comment. Did I add to many forward declare or it is ok ?

**Comment by yanesca** [comment]
@gelldur Thank you! You didn't add too many, I was just justifying why I didn't ask you to add even more.

**Comment by yanesca** [comment]
@gelldur Could you please rebase to have a single commit with all the changes and explain in the commit message why we are doing these changes?

**Comment by gelldur** [comment]
@yanesca done

**Comment by sbutcher-arm** [comment]
Whilst reviewing this, I was wondering if we need some style guidelines or similar to give `struct` names a different name from the `typedef`'s (eg. the idiom of `typedef struct _mystruct {...} mystruct;`), however, I found we already appear to reuse the same name, as you can see in 
`asn1.h`.

As such, I'm approving the change, but I see no need to backport.

**Pull request merged**
