### PR TITLE
Bug fix: mutex access within entropy_contex after it has been zeroed leads to app crash.

### PR DESCRIPTION
**Pull request by ptahpeteh**

### CODE REVIEW

**Comment by mpg** [comment]
Ouch, that's embarrassing. Thanks for your report and fix! I'll check every other occurrence of `polarssl_zeroize()` close to `mutex_free()` in order to make sure it's the only problem of this type.

Would you like to give us your name for attribution in the ChangeLog, our should we use your github username?

**Comment by mpg** [comment]
Merged in the 'development' branch (better to base your future contribution on this branch, btw). Thanks again!

**Comment by ptahpeteh** [comment]
You can use my real name: Rafał Przywara.

**Comment by mpg** [comment]
Done, thanks.

**Pull request closed without merging**
