### PR TITLE
Remove config-psa-crypto.h

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
This configuration file was useful in the early days of PSA crypto development. It stopped becoming relevant when `MBEDTLS_PSA_CRYPTO_C` entered the default configuration. Remove it: better late than never.

Backport: [2.x](https://github.com/ARMmbed/mbedtls/pull/4456)

### CODE REVIEW

**Review by ronald-cron-arm — DISMISSED** [review]

**Comment by mpg** [comment]
CI is failing `test_ref_configs`.

**Review by ronald-cron-arm — DISMISSED** [review]

**Review by mpg — APPROVED** [review]
Looks good to me, but unfortunately there are conflicts to be resolved.

**Comment by gilles-peskine-arm** [comment]
I've rebased to resolve the edit/remove conflict. The patch is the same.

**Review by ronald-cron-arm — DISMISSED** [review]

**Review by mpg — APPROVED** [review]

**Comment by gilles-peskine-arm** [comment]
Rebased again.

**Review by mpg — APPROVED** [review]

**Review by ronald-cron-arm — APPROVED** [review]

**Pull request merged**
