### PR TITLE
Fix missing void argument declarations #678

### PR DESCRIPTION
**Pull request by jorisa**
This is my first contribution so apologies in advance if I am violently ignoring any guidelines.

### CODE REVIEW

**Comment by sbutcher-arm** [comment]
Thanks for the contribution! To accept this or any future contributions we will need a Contributor’s Licence Agreement (CLA) signed or authorised by yourself. The easiest way to do this is if you create an mbed account and [accept this click through agreement](https://developer.mbed.org/contributor_agreement/) which is applicable if this is a personal contribution. Alternatively, you can find a [slightly different agreement to sign here] (https://www.mbed.com/en/about-mbed/contributor-license-agreements/), which can be signed and returned to us, and is applicable if you don't want to create an mbed account or alternatively if this is a corporate contribution.

Thanks for your understanding and again, thanks for the contribution!

**Comment by jorisa** [comment]
I already did this, but my mbed account was not linked to my github one yet (which I just did), could that have been the problem?

**Comment by jorisa** [comment]
@sbutcher-arm PING :ping_pong:

**Comment by jorisa** [comment]
@sbutcher-arm can you by any chance confirm my CLA status and merge this?

**Comment by sbutcher-arm** [comment]
Hi @jorisa. Can you please confirm that [this](https://developer.mbed.org/users/jorisa/) is your mbed account?

**Comment by jorisa** [comment]
Yes that is my mbed account.

**Comment by sbutcher-arm** [comment]
Thanks for confirming!

**Comment by sbutcher-arm** [comment]
Approved by me, but needs a second reviewer, so assigning to @gilles-peskine-arm.

@gilles-peskine-arm - once (or if) you approve, please mark as 'ready to merge'.

**Pull request merged**
