### PR TITLE
Backport 2.x: Fix x86_64 assembly for bignum multiplication

### LINKED ISSUE #4786: 8e464c4 breaks clang 12 -O2 (make test failed)
### Summary
seems that 8e464c407a1ce8b88412c6a8cc8aafa8d2cf1b0f (bisected) confused clang 12 when you compile with -O2....

### System information

Mbed TLS version (number or commit id): 3.0.0 or 2.27 branch
Operating system and version: archlinux x86_64 with clang 12, happens with llvm-mingw (windows cross-compiler) too
Configuration (if not default, please attach `mbedtls_config.h`): default
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Expected behavior

make test succeeded

### Actual behavior
make test failed

### Steps to reproduce
CC=clang cmake .. -DCMAKE_BUILD_TYPE=Release
make -j14
make -j14 test

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Backport of #4947

### CODE REVIEW

**Review by davidhorstmann-arm — DISMISSED** [review]
Looks good to me.

**Comment by xffbai** [comment]
Looks good to me.
I think you mean (%%rsi) in the commit message?

**Review by xffbai — APPROVED** [review]

**Comment by gilles-peskine-arm** [comment]
I fixed the register name in the commit message.

**Review by davidhorstmann-arm — DISMISSED** [review]
Thanks!

**Review by xffbai — DISMISSED** [review]

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM!

**Review by xffbai — APPROVED** [review]
LGTM

**Pull request merged**
