### PR TITLE
HKDF (RFC 5869) implementation

### PR DESCRIPTION
**Pull request by thomas-fossati**
Hi,

I've been working with Hannes at the IETF hackathon here in Berlin on the DTLS 1.3 implementation.

Of all the work we've done, I think the implementation of the core HKDF (which is used heavily by the 1.3 key scheduling) is probably something that might be shipped to the dev branch: it's both valid as a standalone primitive and will also be helpful when working on 1.3...

The code is accompanied by a set of test vectors taken from RFC 5869.

(BTW, is there a clang-format/indent file that I can apply to format the sources the mbedtls way?)

### CODE REVIEW

**Comment by thomas-fossati** [comment]
The travis checks run successfully, whereas circleci tests fail with a "no test commands were found" reason phrase...  I'm not sure I understand what I need to do to make them run?  Can someone shed some light on this?  Thanks!

**Comment by sbutcher-arm** [comment]
Hi and thanks for the contribution!

I can see you've put quite a lot of work into this, so thanks for the interest and support.

First to answer your question about CircleCI - we have several CI systems, and CircleCI is still a work in progress and if you hadn't realised, fails on all builds. Apologies for the confusion. For the moment, just ignore it's results. We work in the open pretty transparently, and that can be very good in some ways, but confusing when you reasonably expect something to work and it's not quite there yet.

So to accept your current contributions or any future contributions we will need a Contributor’s Licence Agreement (CLA) signed or authorised by yourself. You can [find an agreement to sign here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/), which can be signed and returned to us, or you could create an mbed account and [accept a slightly different agreement here with a click through](https://developer.mbed.org/contributor_agreement/) if this is a personal contribution. 

Thanks for your understanding!

**Comment by thomas-fossati** [comment]
Hi,

thanks for the clarifications. I've just registered as user "babongo" and accepted the Contributor Agreement.

Cheers, t

**Comment by Patater** [comment]
Hi @thomas-fossati 

Thanks for your contribution! I've rebased it on latest development, adapted the style, and made a new PR (#1497) to continue the process of getting your contribution merged. I'll close this PR and we'll continue the work in #1497.

Thanks!

**Pull request closed without merging**
