### PR TITLE
Implement SHA-3

### PR DESCRIPTION
**Pull request by damaki**
Hello!

Keccak won the SHA-3 competition in 2012 and was standardized by NIST in August 2015. This pull request adds the following SHA-3 hash functions and extendable output functions (XOF) to the cipher lib, as specified by NIST FIPS PUB 202:
    \* Hash: SHA3-224, SHA3-256, SHA3-384, and SHA3-512.
    \* XOF: SHAKE128 and SHAKE256.

The following modules have been added to the cipher lib:
    \* keccakf.c - Implements the Keccak-f[1600] permutation.
    \* keccak_sponge.c - Implements the Sponge cryptographic construction.
    \* sha3.c - Implements the SHA-3 hashing algorithms.
    \* shake.c - Implements the SHAKE XOFs.

I've also added the SHA-3 hash functions to the MD module.

Here's a list of references that were used:
    \* http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.202.pdf
    \* http://keccak.noekeon.org/Keccak-reference-3.0.pdf

I've added tests for each of the SHA-3 and SHAKE algorithms, with test vectors used from:
    \* http://csrc.nist.gov/groups/STM/cavp/secure-hashing.html#test-vectors
    \* http://csrc.nist.gov/groups/ST/toolkit/examples.html#aHashing
    \* http://www.di-mgt.com.au/sha_testvectors.html

I've also added the SHA-3 hashing functions to the benchmark program. Here's the performance of SHA-3 compared to the other hash functions:
  MD5                      :     353939 Kb/s,          5 cycles/byte
  RIPEMD160                :     205729 Kb/s,          9 cycles/byte
  SHA-1                    :     274623 Kb/s,          7 cycles/byte
  SHA-256                  :     116313 Kb/s,         17 cycles/byte
  SHA-512                  :     161491 Kb/s,         12 cycles/byte
  SHA3-224                 :     123865 Kb/s,         16 cycles/byte
  SHA3-256                 :     123939 Kb/s,         16 cycles/byte
  SHA3-384                 :     103150 Kb/s,         18 cycles/byte
  SHA3-512                 :      72815 Kb/s,         27 cycles/byte

This output was produced on a Ubuntu 14.04 system with an Intel Core i7-2630QM, built using GCC 4.9.3. I think there's still room for further improvement, though.

### CODE REVIEW

**Comment by sbutcher-arm** [comment]
Hi!

First, this is a pretty big contribution, so thanks both for the interest in mbed TLS and the support!

To accept this contribution and any further contribution we will need a Contributor’s Licence Agreement (CLA) signed by yourself or by whoever has the authority to do so. You can [find an agreement to sign here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/), which can be signed and returned to us, or you could create an mbed account and [accept a slightly different agreement here with a click through](https://developer.mbed.org/contributor_agreement/) if this is a personal contribution. 

Thanks in advance for your understanding.

Because this is a large contribution, I have only given this a brief review to confirm we'd like to accept it (you've followed our style and conventions very well), and I'll follow up with a more detailed review to identify any issues once we've received a CLA and are ready to merge.

Again, thanks for the support!

**Comment by damaki** [comment]
Hello again,

I've just rebased my branch with the latest mbedTLS development branch to resolve the merge conflicts and to keep it more up-to-date.

**Comment by kneehat** [comment]
Any plans for this to accepted?

**Comment by gilles-peskine-arm** [comment]
Thanks you very much for your contribution! Since it's been a while, I've rebased it to the current development and adapted it to our latest conventions in #1549. We'll continue any further work in #1549.

**Comment by trashoverride** [comment]
i will use this and test ! i am  needing :)

**Comment by sbutcher-arm** [comment]
I think having two SHA-3 PR's open is confusing, and given this PR is being developed as PR #1549, and further work should be done there, I think its best to close this one.

@damaki - If you'd like to contribute further on SHA-3 - please either raise a new PR or push to the #1549 PR. Thanks!

**Pull request closed without merging**
