### PR TITLE
Added checking for QNX operating system to make mbedtls build on QNX

### PR DESCRIPTION
**Pull request by modbw**

### CODE REVIEW

**Comment by sbutcher-arm** [comment]
Shouldn't the check for `__QNXNTO__`be better as `__QNX__`?

See [here](http://www.qnx.com/developers/docs/660/index.jsp?topic=%2Fcom.qnx.doc.neutrino.prog%2Ftopic%2Fdevel_Neutrino_specific.html) for an explanation.

**Comment by sbutcher-arm** [comment]
I know that this is only a small contribution, but to accept this or any future contributions we will need a Contributor’s Licence Agreement (CLA) signed or authorised by yourself. You can [find an agreement to sign here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/), which can be signed and returned to us, or you could create an mbed account and [accept a slightly different agreement here with a click through](https://developer.mbed.org/contributor_agreement/) if this is a personal contribution. 

Thanks for your understanding!

**Comment by modbw** [comment]
I have accepted the agreement with my new mbed account with the same username as my github account. I think we should stick with __QNXNTO__ as QNX 4 is more or less dead and only NTO was tested.

**Comment by yanesca** [comment]
Hi @modbw,

Thank you for your contribution!

I have reviewed it and it looks good to me, I have only two minor remarks:
- We may want to extend the conditions on line 446 in net.c to avoid a very unlikely conversion problem
- Also we should do the same on line 39 in programs/ssl/mini_client.c if we wan't it to do something sensible

**Comment by modbw** [comment]
Both changes are OK to me. Should I update the pull request or do you modify it when applying?

**Pull request merged**
