### PR TITLE
Backport 2.x: Remove config-psa-crypto.h

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
This configuration file was useful in the early days of PSA crypto development. It stopped becoming relevant when `MBEDTLS_PSA_CRYPTO_C` entered the default configuration. Remove it: better late than never.

Backport of https://github.com/ARMmbed/mbedtls/pull/4455

### CODE REVIEW

**Review by ronald-cron-arm — DISMISSED** [review]

**Comment by mpg** [comment]
Is it OK to remove this file in a stable branch? What was it used for, is it possible that some users relied on it?

**Comment by gilles-peskine-arm** [comment]
@mpg We've done it before: https://github.com/ARMmbed/mbedtls/pull/1280, https://github.com/ARMmbed/mbed-crypto/pull/71. We did announce it in the changelog, so I'll add a changelog entry.

**Review by ronald-cron-arm — APPROVED** [review]

**Review by mpg — APPROVED** [review]
LGTM

**Comment by mpg** [comment]
Just holding out waiting for conflicts to be resolved in the main PR, as I think it's slightly cleaner to merge them both at the same time.

**Pull request merged**
