### PR TITLE
Backport 2.x : Use proper formatting macros when using MinGW provided stdio

### PR DESCRIPTION
**Pull request by ekoby**
Signed-off-by: eugene <eugene.kobyakov@netfoundry.io>

## Description
Fixed build failure with MinGW toolchain

## Status
READY

## Requires Backporting
NO. the build has been broken since 2.26.0 but had no reports

## Migrations
NO

## Additional comments
Any additional information that could be of interest

## Todos
- [x] Changelog updated
- [x] Backported

## Steps to test or reproduce
build with mingw toolchain

### CODE REVIEW

**Comment by paul-elliott-arm** [comment]
Hi @ekoby - Thanks for your contribution - could you make another PR targetting development as well, as this would need to be fixed on both branches ideally, as (this) the 2.x branch would only be a backport.

We *do* build with MinGW, but clearly not in the way you do, as this passes CI. I presume we have `__USE_MINGW_ANSI_STDIO` set to 0, and I also presume this is the default, as we don't set it anywhere. I apologise for my lack of MinGW knowledge, but is this a typical option to use? Should we be doing CI testing with this?

Could you also add a changelog entry to this, and the other PR? (see https://github.com/ARMmbed/mbedtls/blob/development/ChangeLog.d/00README.md)

**Comment by ekoby** [comment]
Changelog entry added.

I am certainly sure that this is triggered for me because I am using MinGW-W64 targeting amd64, this causes `PRIuPTR` to be defined as `"llu"` and requires format to be checked against `gnu_printf` standard

> Hi @ekoby - Thanks for your contribution - could you make another PR targetting development as well, as this would need to be fixed on both branches ideally, as (this) the 2.x branch would only be a backport.
> 
> We _do_ build with MinGW, but clearly not in the way you do, as this passes CI. I presume we have `__USE_MINGW_ANSI_STDIO` set to 0, and I also presume this is the default, as we don't set it anywhere. I apologise for my lack of MinGW knowledge, but is this a typical option to use? Should we be doing CI testing with this?
> 
> Could you also add a changelog entry to this, and the other PR? (see https://github.com/ARMmbed/mbedtls/blob/development/ChangeLog.d/00README.md)

**Comment by ekoby** [comment]
development PR https://github.com/ARMmbed/mbedtls/pull/4497

**Comment by paul-elliott-arm** [comment]
Does this mean your build is still broken if `__USE_MINGW_ANSI_STDIO` is set to zero?

Admittedly I am not sure of any way we could work around that either.

> Changelog entry added.
> 
> I am certainly sure that this is triggered for me because I am using MinGW-W64 targeting amd64, this causes `PRIuPTR` to be defined as `"llu"` and requires format to be checked against `gnu_printf` standard
>

**Comment by ekoby** [comment]
if `__USE_MINGW_ANSI_STDIO` is set to zero explicitly then MinGW sets `PRluPTR` to `"I64u"` so it works with mcvrt.dll
 
> Does this mean your build is still broken if `__USE_MINGW_ANSI_STDIO` is set to zero?
> 
> Admittedly I am not sure of any way we could work around that either.
> 
> > Changelog entry added.
> > I am certainly sure that this is triggered for me because I am using MinGW-W64 targeting amd64, this causes `PRIuPTR` to be defined as `"llu"` and requires format to be checked against `gnu_printf` standard

**Review by paul-elliott-arm — APPROVED** [review]
LGTM

**Review by mpg — APPROVED** [review]
LGTM

**Pull request merged**
