### PR TITLE
add Visual Studio 2015 solution and projects

### PR DESCRIPTION
**Pull request by RonEld**
Add new solution and projects for VS 2015, to support both 2010 and 2015
VS projects

### CODE REVIEW

**Comment by NWilson** [comment]
Just out of curiosity, what is the rationale for adding these? As a contributor, do I need to edit all these random Visual Studio versions each time I add a file? Surely the point of CMake is that you don't need to maintain all these project files.

**Comment by sbutcher-arm** [comment]
mbed TLS can be built in two different ways with Visual Studio - via cmake and msbuild on the command line, and through the Visual Studio IDE.

The Visual Studio solution and project files in the `visuals\VS2010` directory, are provided to ease users into building mbed TLS in the IDE and are meant to make introduction into mbed TLS easier.

Because we provide Visual Studio 2010 build files, which can be imported without problem into all later versions of Visual Studio, I don't see much need for this Pull Request, and I think it just increases the support burden.

It's also worth mentioning that the Visual Studio files are intended to be generated by the script `scripts/generate_visualc_files.pl` which depend on template files. If we do want to include Visual Studio 2015 files, we should probably add additional template files for use with that script.

As such, I'm closing the pull request without merging - but if anyone has a strong need for Visual Studio 2015 project and solution files, please reply and we can discuss it!

**Comment by confusedsushi** [comment]
Adding something like

```xml
  <PropertyGroup Label="Configuration">
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">10.0</VisualStudioVersion>
    <PlatformToolset Condition="'$(VisualStudioVersion)' == '10.0'">v100</PlatformToolset>
    <PlatformToolset Condition="'$(VisualStudioVersion)' == '11.0'">v110</PlatformToolset>
    <PlatformToolset Condition="'$(VisualStudioVersion)' == '12.0'">v120</PlatformToolset>
    <PlatformToolset Condition="'$(VisualStudioVersion)' == '14.0'">v140</PlatformToolset>
    <PlatformToolset Condition="'$(VisualStudioVersion)' == '15.0'">v141</PlatformToolset>
  </PropertyGroup>
```

to the project files will make the project usable in any Visual Studio starting with 2010 without the need of converting them.

What do you think of this? If you like it, I will prepare a pull request.

**Comment by RonEld** [comment]
Hi @confusedsushi 
I am not a windows expert, and we need to think about the consequences, however this sounds like something we would like to adopt, as long as it owqn't break cmake build, or any other vs version project.
Please remember to use `generate_visualc_files` script

**Pull request closed without merging**
