### PR TITLE
Backport 2.1: Treat warnings as errors for IAR

### PR DESCRIPTION
**Pull request by mazimkhan**
Backport of: Treat warnings as errors for IAR #1646

### CODE REVIEW

**Comment by miklis** [comment]
retest

**Comment by miklis** [comment]
retest

**Comment by sbutcher-arm** [comment]
This PR has received an extra commit of 78606e6, so the reviews are stale. There are also conflicts, so it needs rebasing.

But why are we backporting this anyway? I don't think we need this PR. Improving or raising the quality bar for a compiler that wasn't supported when we created the `mbedtls-2.1` branch isn't necessary. Adding support for an extra compiler is basically an extra feature.

**Comment by mazimkhan** [comment]
@sbutcher-arm we do build 2.1 with IAR for the sake of common CI scripts. But we don't need to improve it's quality. Hence, I agree with you in closing this.

**Comment by sbutcher-arm** [comment]
This PR and the PR it's back porting, #1646, duplicated the work of another PR, #750 bar @roneld.

#750 which was much older than this one was targeting `mbedtls-2.1`, I'm going to reverse my decision to not backport this one, and re-open it.

@mazimkhan - can you please rebase it and rework it?

**Comment by sbutcher-arm** [comment]
Now rebased, and ready for re-review.

**Pull request merged**
