### PR TITLE
[baremetal] AES remove forward reverse tables to save ROM

### PR DESCRIPTION
**Pull request by artokin**
## Description

Replace AES forward/reverse tables with instant calculation to save ROM.

__Impact on code-size:__

| | GCC | ARMC5 | ARMC6 |
| --- | --- | --- | --- |
| `libmbedcrypto.a` before | 20915 | 21387 | 23477 |
| `libmbedcrypto.a` after | 18875 | 19207 | 21441 |
| gain Total | 2040 | 2180 | 2036 |

## Status
**READY**

## Additional comments
This PR contains commits from PR #2888

### CODE REVIEW

**Comment by mpg** [comment]
@artokin Did you make any measurement of the effect on speed, preferably on a target of interest? (We have a crypto brenchmark program for Mbed OS which could be useful: https://github.com/ARMmbed/mbed-os-example-tls/tree/master/benchmark - or you could roll your own.) The main benefit of larger tables is speed, so it would be interesting to know how much we loose by removing them.

**Comment by artokin** [comment]
@mpg , bench-marking results attached, only AES test results copied here as there were no significant difference in the other tests:

__Benchmarking with ARMC5:__

| test | before | after |
| --- | --- | --- |
| AES-CBC-128      | 536 KB/s | 160 KB/s
| AES-CBC-192      | 472 KB/s | 134 KB/s
| AES-CBC-256      | 422 KB/s | 115 KB/s
| AES-CTR-128      | 564 KB/s | 162 KB/s
| AES-CTR-192      | 494 KB/s | 136 KB/s
| AES-CTR-256      | 437 KB/s | 116 KB/s
| AES-GCM-128      | 317 KB/s | 132 KB/s
| AES-GCM-192      | 293 KB/s | 114 KB/s
| AES-GCM-256      | 272 KB/s | 100 KB/s
| AES-CCM-128      | 240 KB/s | 77 KB/s
| AES-CCM-192      | 214 KB/s | 65 KB/s
| AES-CCM-256      | 192 KB/s | 56 KB/s
| AES-CMAC-128     | 474 KB/s | 152 KB/s
| AES-CMAC-192     | 422 KB/s | 128 KB/s
| AES-CMAC-256     | 379 KB/s | 111 KB/s
| AES-CMAC-PRF-128 | 473 KB/s | 152 KB/s

**Comment by mpg** [comment]
Thanks for making the measurements!

Wow, that's a pretty big performance hit! Looking only at the line for AES-CCM-128, which I think is the only one we care about, the tableless version is 3 times slower.

This makes me doubt if this codesize optimisation is really worth it. Currently it's measured at about 2kB, but #2890 already achieved a gain of 2.5kB without any performance hit, and I doubt the gains between those two PRs are additive (ie, this PR's gain would probably be smaller if measured on top of #2890).

@sbutcher-arm What do you think? Is it acceptable to make AES-CCM-128 3 times slower for a gain of 2kB of code size (or maybe less)? Or should we instead focus on other ways to save code size, that don't impact performance as much?

**Comment by artokin** [comment]
This was rebased due merge conflict in `scripts/config.pl`.
Please note, a new rebase will be needed when once #2890 and #2891 are merged.

**Comment by mpg** [comment]
@artokin Out of curiosity, could you try to do a quick local rebase over 2891 (or merge 2891 with this one in a local branch) and measure what the codesize improvement is when enabling `MBEDTLS_AES_SBOX_ONLY` on top of `MBEDTLS_AES_ONLY_ENCRYPT`? I suspect it's likely to be about half of the currently measured one, so about 1kB, but it's easy to guess wrong with these things, so an actual measurement would be better than my guess :)

**Comment by sbutcher-arm** [comment]
I can see your concerns @mpg, but to make a decision I think we need absolute figures.

@artokin - Once we've merged the *other* AES PR's, can you measure again the improvement in codesize and cost in RAM? Once we have that, we can make a decision.

**Comment by artokin** [comment]
I made a merge in my workarea and here are the initial ROM figures:

__Configuration impact to code size using ARMC5_5.06 update 6__

| Configuration | ROM usage | Gain to baremetal |
|--------|-----------|------|
| baremetal | 42762 | 0 |
| AES 128-bit key | 42512  | -250  |
| AES 128-bit key + encrypt_only | 39894 | -2868 |
| AES 128-bit key + encrypt_only + SBOX Table| 38728 | -4034 |

**Comment by mpg** [comment]
@artokin Thanks for those doing those measurements! So if I'm reading the table correctly, the additional gain of table-less AES on top of encrypt-only is 1166 bytes.

To summarize, here's the trade-off that this PR implements:

**Benefit:** saving 1166 bytes of flash.
**Costs:**

* Dividing performance by 3 for AES-CCM-128 (from 240 to 77kB/s on the target)
* Consume 256 more bytes of static RAM (fixed cost for the application, not per context or operation, but permanent (not on stack or heap)).

@artokin Do you think this summary is accurate?

@sbutcher-arm Considering that summary, do you think we should pursue this or park it?

My opinion is that the performance cost is so high that we should give priority to other ways of saving code size, that don't impact performance as much - we still have ideas for such optimisations.

**Comment by artokin** [comment]
@mpg , your summary is excellent!

**Comment by sbutcher-arm** [comment]
There are no plans to finish this PR, so I'm now closing it.

It's probably something that could be picked up and resubmitted by someone in the community, but we have no plans to do antything more with it.

**Pull request closed without merging**
