### PR TITLE
pkcs5: add support for additional hmacSHA algorithms

### PR DESCRIPTION
**Pull request by ordex**
Currently only SHA1 is supported as hmac algorithm for PBKDF2
in PKCS5. This means that keys encrypted and authenticated using
another algorithm of the SHA family cannot be decrypted.

This deficiency has become particularly incumbent now that
PKIs created with openssl-1.1 are encrypting keys using
hmacSHA256.

Enable support for all the digest algorithms of the SHA
family for PKCS5.

Signed-off-by: Antonio Quartulli <antonio@openvpn.net>

## Status
**READY**

## Requires Backporting
NO  

## Migrations
NO

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated

## Steps to test or reproduce
Try to import a pk created and encrypted using openssl-1.1 and observe failure. With this PR the import succeeds.

### CODE REVIEW

**Comment by ordex** [comment]
I have signed the CLA in the past.
The terminology in the commit message might be a bit off.

**Comment by ordex** [comment]
Since now all the SHA* digests are accepted, I have modified the unit-test payload to contain MD5 (the uni-test check that the parsing routine fails with an unsupported digest).

**Comment by ordex** [comment]
removed extra empty line

**Comment by ordex** [comment]
rebased on top of latest master and signed commit.

**Comment by ordex** [comment]
Hi there, any comment on this? I understand that merging the patch will require some time, but at least getting an initial feedback would be helpful on our side.

If we know the patch is "reasonable" we could start testing it on a broader scale.
Several OpenVPN users need to work around this issue by either not using key encryption or by manually re-encrypting the key with different settings.

Right now we are a bit stuck on this issue :/

Thanks!

**Comment by ordex** [comment]
Thanks for your feedback @hanno-arm ! Will do!

**Comment by ordex** [comment]
@hanno-arm I was able to generate PBKDF2 test vectors using python's hashlib. But I am having some troubles finding an easy way to get those for PBES2. Do you happen to have an alternative implementation I could use to generate them?

**Comment by hanno-arm** [comment]
@ordex I think the easiest would be to extend https://github.com/ARMmbed/mbedtls/blob/development/tests/data_files/Makefile which already generates a large number of test cases for PBES2 using OpenSSL tools.

**Comment by ordex** [comment]
@hanno-arm thanks for the hint. I'll have a look!

**Comment by hanno-arm** [comment]
@ordex It would be great if you could adopt this approach of documenting the source of test files and, if possible, only use tools that are already in our test toolchain, such as OpenSSL. The lates PR which made a similar enhancement and test extension was https://github.com/ARMmbed/mbedtls/pull/1062, so you might want to have a look.

**Comment by ordex** [comment]
@hanno-arm btw, I see that https://github.com/ARMmbed/mbedtls/blob/development/tests/data_files/Makefile does not contain any instruction to generate test_suite_pkcs5.data. Therefore I guess that the latter was handwritten.
My current approach is to simply create copies of test_suite_pkcs5.data, one for each SHA algorithm, and modify the payloads (both input and output) with something meaningful for the specific alg.

The Makefile seems to be oriented towards a different approach: generate DER/PEM files and later fed them to unit tests.

Are you suggesting to drop the approach used by the PKCS5 unit test (i.e. use a .data file) in favour of using OpenSSL to generate PKCS#5 encrypted keys and then validate/parse them with mbedTLS?

If that's the case, I feel like this would test a wider set of components compared to having a simple unit test focused only on mbedtls_pkcs5_pbkdf2_hmac()

**Comment by hanno-arm** [comment]
@ordex The approach is different: All (unit) test suites have a `xxx.data` file which together with the corresponding `xxx.function` file is autogenerated into an `xxx.c` test file which is then compiled and executed. Some tests within `xxx.data` are standalone and don't use external files (such as the `pkcs5.data` tests at the moment), while some, such as the `pkparse.data` test suite, take a file argument. 

You're right that solely extending the `pkparse` tests isn't ideal, because it would involve more than a unit test for PKCS5, namely integration testing with the PK parsing. Suggestion:
* Extend `pkcs5.data` by tests analogous ones already present, but using the newly introduced hash algorithms. I don't know how the original payloads were generated, though - it doesn't seem to be documented. So you may generate them using your preferred way, though a command line generation based on tools like those of OpenSSL (that could be added to the test description as a comment) would be preferred. 
* If you want, also extend `pkparse.data` by tests exercising keys that have been protected via PKCS5 and the newly supported hash functions.

Does that make sense?

**Comment by ordex** [comment]
@hanno-arm Yeah, it does.

Your first point is exactly what I was currently doing: I have created one `pkcs5.xxxx.data` for each algo (similar to what you have with `gcm.xxxx.data`) and extended the Makefile to auto generate and compile the .c units.

Now, about the .data content: generating the test vectors for `pbkdf2_hmac()` was fairly easy, while payloads used for testing `mbedtls_pkcs5_pbes2()` need some more work because they include ASN1 objects. Anyway, I'll find out how to generate them and document it in the data file.

Thanks for your hints so far!

**Comment by hanno-arm** [comment]
@ordex Thanks! To my knowledge, we unfortunately don't yet have a utility tool for PKCS5 PBES2 encryption/decryption in the `programs` folder, but I would be surprised if it wasn't possible with OpenSSL, so you might want to have a look.

**Comment by hanno-arm** [comment]
@ordex See https://tls.mbed.org/kb/development/test_suites for more on the design of our test system.

**Comment by ordex** [comment]
thanks @hanno-arm

**Comment by ordex** [comment]
Apparently not even OpenSSL exposes its PKCS5 PBES2 functionalities via the command line tool.
@hanno-arm How about we live with the basic `pbkdf2_hmac()` for now and later we implement a tool in `programs` taking care of pkcs5? At that point we can extend the unit tests.

After all, `mbedtls_pkcs5_pbes2()` is already verified in the sha1 unit test. On top of that we are adding tests for `pbkdf2_hmac()` using the new algorithms, therefore we should have enough coverage already.

Would that be acceptable?

**Comment by ordex** [comment]
@hanno-arm in the meantime, I extended also `CMakeLists.txt` (I had forgotten about it) and rebased my branch on top of the latest `development`.

The current code is doing what I said in my last comment. Let me know what you think it's best to move forward.

**Comment by sbutcher-arm** [comment]
Hi @hanno-arm, @mpg,

Could you please review this PR?

Thanks

**Comment by mpg** [comment]
Hi @ordex and thanks for your contribution!

I had a first look at this PR and your code looks good! (Though I'll have a closer look later.)

Regarding tests, I agree with Hanno that we ideally want both unit tests (included in your PR, thanks!) and integration/functional tests: those would test what a end-user sees. For example, the PR cover states "Try to import a pk created and encrypted using openssl-1.1 and observe failure. With this PR the import succeeds." I think that's a great basis for a test: can you use openssl-1.1 in `tests/data_files/Makefile` to generate encrypted keys that we currently cannot import, and add a test to `test_suite_pkparse` demonstrating that it now works with your PR?

Regarding the unit tests your provided, can you state in the `.data` file where the data comes from? Ideally the source should be a published standard (like an RFC), or if that can't be found, data generated using another, preferably well-established, implementation. OTOH, data generated using our own implementation is generally not enough: we not only want to catch regressions, but also have some evidence that our initial implementation is correct too. I was able to find published test vectors for PBKDF2-HMAC_SHA256 in [RFC 7914 section 11](https://tools.ietf.org/html/rfc7914#page-12), but for other hashes the best I could find so far is [this](https://github.com/Anti-weakpasswords/PBKDF2-Test-Vectors/releases).

On a practical note, I think I'd prefer keeping a single `test_suite_pkcs5` suite rather than splitting it in sub-suites as I don't think it's big enough to justify a split: currently the `.data` file is only 126 lines and with your additions it would grow to a bit more that 200 lines - so far suites that are split that way all have more than 1000 lines of total data.

Thanks again, and I'm looking forward to working with you on finalizing this PR!
Manuel.

**Comment by ordex** [comment]
Hi @mpg and thanks a lot for your feedback! Ok, I'll rework the test and merge the files as you suggest.

For the test vectors: I used the hashlib library in python to generate them. Is that valid enough?
I couldn't find any RFC and so I did generate them myself with one line of python.

However, I can use those provided by the RFC for SHA256 if you prefer.

About the other link: it seems the user just generated them by himself. Would you prefer that instead of the python oneliner with hashlib? If we go for the latter, I can easily copy/paste the code in the test file. But either one is fine with me.

What about the `PBES2` test? Can I assume that by decrypting an openssl-1.1 generated key we are covering this part?

Thanks!

**Comment by mpg** [comment]
Regarding PBKDF2 test data, Python's hashlib is clearly well-established (I just checked that it includes `pbkdf2_hmac`, I previously thought you coded it yourself from hmac or the hashes, sorry for the misunderstanding), so that data is valid enough. Just add `(python hashlib)` in each test description, and in the commit message include the exact line of python you used as well as the Python version.

I you don't mind adding the test vectors from RFC 7914 for SHA256 on top of that (with `RFC 7914` in the test description), that would be great!

Regarding PBES2, while in principle it would be ideal to have independent tests for it, I think decrypting openssl-1.1 generated keys will cover it well enough, considering as you mentioned that we already have unit tests for PBES2 with PBKDF2-HMAC-SHA1.

**Comment by ordex** [comment]
Thanks @mpg that sounds good!
I'll modify this PR accordingly.

**Comment by ordex** [comment]
@mpg about generating an encrypted key with OpenSSL 1.1: do you have any recommendation about how to check in the Makefile that we are actually using v1.1 and not v1.0?
Should I just make implement a comparison against the version returned by `openssl version` and skip the pkcs5 test if the version is not 1.1? (sounds a bit cumbersome to be implemented in a Makefile :P)

**Comment by mpg** [comment]
This Makefile is actually not part of the build system - the files it generates are commited in the repo, so it's really just a form of executable documentation of how they were generated. As such, I think you can just add a comment above that rule clarifying the version to be used. Or perhaps use a variable `OPENSSL11` for the command (with a default value of `false`, that people would have to override with the path to openssl 1.1) if you want to make extra sure this rule is not used by mistake with the wrong version.

**Comment by ordex** [comment]
Yeah, makes sense! Thanks for the suggestion

**Comment by ordex** [comment]
In order to better understand the exact command I needed to generate the required encrypted keys, I decided to dive into the OpenSSL code and I found some interesting details about the real cause of this incompatibility.

Here are my observations:
- the core of the problem is in the PRF used when encrypting keys with PKCS#8/PKCS#5v2.0
- OpenSSL 1.0 by default encrypts keys using PKCS#5v1.0, thus the generated key material is compatible with mbed TLS
- OpenSSL 1.0 invoked with `pkcs8 -v2 CIPHER` by default encrypts keys using PKCS#5v2.0 with PRF = SHA1, thus the generated key material is compatible with mbed TLS
- OpenSSL 1.0 can be tweaked to use another PRF. `openssl pkcs8 -v2 CIPHER -v2prf hmacWithSHAX` encrypts keys using PKCS#5v2.0 with PRF = SHAX. If X != 1, the generated key material is NOT compatible with mbed TLS. **This means that it is possible to reproduce the problem also with OpenSSL1.0**.
- OpenSSL 1.1 when used to create keys within a cert-request, by default encrypts keys using PKCS#8/PKCS#5v2.0
- OpenSSL 1.1 when used to encrypt keys using PKCS#8/PKCS#5v2.0 uses hmacWithSHA256 by default.

The last 2 points are what triggered the "incompatibility" of new PKIs with mbed TLS.

I am not extremely expert in this field, therefore bare with me if I used the wrong terminology when pairing the various PKCS/PRF/etc..etc acronyms.

**Comment by ordex** [comment]
The code I just pushed add all the new keys to verify the different PRF algorithms as suggested.
For each new SHA algorithm, I created as many keys as those we already have for SHA1.

Reverting my commit `pkcs5v2: add support for additional hmacSHA algorithms` results in the failure of the `tests_suite_pkparse` module.

However, I noted that all the keys are generated using DES and 3DES. I think it would be meaningful, as a regression test, to also add keys encrypted with AES*. (but this can be done later)

**Comment by ordex** [comment]
@mpg do you have any additional feedback? I feel we are pretty close :)

**Comment by mpg** [comment]
Thanks for adding those tests and making the suggested changes! I reviewed it and am quite happy with the result, the only thing that's still missing is the ChangeLog entry. Please add one, crediting yourself in the way you prefer - as soon as it's done, I'll formally approve the PR.

The next steps is that a second member of the team (@hanno-arm I assume) will review the PR, and the Mbed TLS architect (@sbutcher-arm) as well since this PR extends the API (even though the new function is mainly internal). When they're both happy, your PR will be ready for merge.

**Comment by ordex** [comment]
patches rebased on top of the latest development branch and Changelog updated (in `pkcs5v2: add support for additional hmacSHA algorithms`). Feel free to reword the line.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2085

**Comment by mpg** [comment]
Thanks for the rebase and ChangeLog entry! Unfortunately I'm afraid it's in the wrong section: please create a new section `= mbed TLS x.x.x branch released xxxx-xx-xx` at the top and add your entry in that section. Also, I believe the "Features" sub-section would be more appropriate than "API Changes".

**Comment by ordex** [comment]
Changed :) sorry, but by being the first contribution I am a bit clueless as of how to make these changes. Thanks for your hints so far!

**Comment by mpg** [comment]
No problem, there's always a lot of non-obvious things when contributing to a new project. Thanks for working with us!

**Comment by gilles-peskine-arm** [comment]
Note to gatekeepers: this fixes #1339. We should make a note in the ChangeLog that this isn't just a new feature, it fixes an interoperability issue as well.

Unfortunately we missed the window for 2.7.0, but we should include this in 2.7.1. So this should be merged both to `development` and to `mbedtls-2.7`.

We may want to include this in the next 2.1 patch release as well. Backport: #1373

**Comment by mpg** [comment]
@gilles-peskine-arm I'd like to question how much of an interop issue it is (just for the purpose of deciding whether to backport or not, IMO it's absolutely clear that we want to add it in the main branch ASAP).

It seems to me that if people have a key created (and encrypted) with OpenSSL 1.1 that uses an algorithm not supported by (an legacy version of) Mbed TLS, they can always turn the new key into something readable by (their version of) Mbed TLS by using openssl to re-encrypt it, for example:
```
openssl pkcs8 -in new.pem -out new2.pem -topk8 -v1 PBE-SHA1-3DES
```
I tested this command using openssl 1.0.2g as well as 1.1.1-pre1 to make sure that support for PKCS#8 v1 was not removed from newer version of OpenSSL, it's just no longer the default.

**Comment by gilles-peskine-arm** [comment]
@mpg The conversion requires the password. Using SHA-1 may also cause compliance issues (even if there's no security issue with SHA-1 as used in PBKDF), for example some environments work with a build of OpenSSL that doesn't have any non-FIPS-compliant algorithm. So there are people who can't use this workaround. Maybe not many people, so I'm not sure we need to backport. People who really need it could take this patch anyway.

**Pull request merged**
