### PR TITLE
Fix minor issues in MSVC projects.

### LINKED ISSUE #3297: A bug in .vcxpoj files and suggested fix
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug
`x64|Debug` configuration in `mbedTLS.vcxproj` has an incorrect `WIN32` preprocessor definition instead of `WIN64`.
The macro was never used, but this is still a bug.

**OS**  
Windows

**mbed TLS build:**  
All versions have this bug.

----------------------------------------------------------------
## Enhancement

**Justification - why does the library need this feature?** 
MSVC has a number of predefined macros, and project wizards used to add something too.
Search in mbedTLS files reveals that macros `WIN32`, `WIN64` and, `_WINDOWS` remain unused; these are obsolete. Also, predefined `_DEBUG` is defined once again in projects, but never used.
Instead, predefined `_WIN32` and `_WIN64` are used in library code.

**Suggested enhancement**  
Remove unused definitions from scripts and projects; keep relying on predefined macros.
Visual Studio solution has built successfully with these changes in my test.

### PR DESCRIPTION
**Pull request by irwir**
## Description
Resolves #3297 - erroneous definition is removed.
Removed preprocessor definitions from project files:
as unused - `_WINDOWS`  `WIN32`  `WIN64` 
as predefined - `_DEBUG`

Removed explicit settings with default values:
`PrecompiledHeader` and `ShowProgress`

## Status
**READY**

## Requires Backporting
NO, but might be considered.
Which branch?
development

## Migrations
NO

## Additional comments
I left for now, but may also delete `_CONSOLE`.
This is never referenced anywhere in the repository and probably is not useful in the example programs.

### CODE REVIEW

**Comment by danh-arm** [comment]
Thanks for you contribution. Unfortunately this fails our CI:
```
******************************************************************

* check_generated_files: Check: freshness of generated source files 

* Tue May 19 17:22:53 UTC 2020

******************************************************************

'visualc/VS2010/mbedTLS.vcxproj' was either modified or deleted by 'scripts/generate_visualc_files.pl'

^^^^check_generated_files: Check: freshness of generated source files: tests/scripts/check-generated-files.sh -> 1^^^^


******************************************************************

* check_generated_files: Done, cleaning up 

* Tue May 19 17:22:53 UTC 2020

******************************************************************


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

FAILED: 1

check_generated_files: Check: freshness of generated source files: tests/scripts/check-generated-files.sh -> 1

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by danh-arm** [comment]
We're still getting a test failure in one of our configs:
```
./tests/scripts/all.sh --seed 4 --keep-going check_generated_files
```
```
******************************************************************

* check_generated_files: Check: freshness of generated source files 

* Wed May 20 12:36:12 UTC 2020

******************************************************************

'visualc/VS2010/zeroize.vcxproj' was either modified or deleted by 'scripts/generate_visualc_files.pl'

^^^^check_generated_files: Check: freshness of generated source files: tests/scripts/check-generated-files.sh -> 1^^^^


******************************************************************

* check_generated_files: Done, cleaning up 

* Wed May 20 12:36:13 UTC 2020

******************************************************************


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

FAILED: 1

check_generated_files: Check: freshness of generated source files: tests/scripts/check-generated-files.sh -> 1

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by irwir** [comment]
In my opinion a more straightforward message saying generated file differs from the one in the library might habe been more clear that `Check: freshness of generated source files`.
Anyway, all the tests passed.
`_CONSOLE` macro was deleted in this version.

**Comment by paul-elliott-arm** [comment]
Hi!

Apologies, this is admittedly slightly confusing. Only the template files (`scripts/data_files/vs2010-(app|main)-template.vcxproj`) are supposed to be edited. If you revert (or shelve) your changes to all the other files, and run `scripts/generate_visualc_files.pl ` then you should find the changes you made to the templates propagated to all the other .vcxproj'es.

Once you have done this, tests/scripts/check-generated-files.sh should run without error (it will moan if the generated version doesn't match the version in a given changelist).

_Hopefully_, this will achieve the same changes as you made, and you can submit a changelist with just the templates in it.

For what its worth, I agree on removing _CONSOLE as well.

Feel free to ping me / comment here if you need any more help!

**Comment by irwir** [comment]
Thank you, @paul-elliott-arm
Edited projects were messed up somehow, and finally the sure way was taken - generate the projects with the script.

By the way, `script/data files` has three files for Visual Studio 6.
Is it intentional or the files could be purged as unsupported?

**Comment by gilles-peskine-arm** [comment]
Text files need a LF at the end. The lack of a LF at the end of a changelog entry files breaks the changelog assembly file with a hard-to-understand error. That's low-priority because it's about dealing with ill-formed input that `check-files.py` now rejects anyway. We only very recently updated `check-files.py` to check changelog entries, and this branch is too old to have the check, which is why pr-head passes. `check_files` fails on pr-merge
```
Missing newline at end of file:
ChangeLog.d/bugfix_PR3333.txt
```
and fixing this will make `check_changelog` pass.

**Comment by danh-arm** [comment]
I'm taking Paul's previous approval since there was only the LF change to the ChangeLog entry. All CI passing now.

**Pull request merged**
