### PR TITLE
Document `psk_list` parameter of ssl_server2 example program

### PR DESCRIPTION
**Pull request by hanno-arm**
__Summary:__ This PR adds documentation for the (pre-existing) `psk_list` command line parameter of `programs/ssl/ssl_server2` which allows to specify the PSKs+Identities that the server should know.

### CODE REVIEW

**Comment by hanno-arm** [comment]
Sorry @AndrzejKurek, I missed a typo. Could you please re-review?

**Comment by hanno-arm** [comment]
Jenkins failed because of timing on FreeBSD.

**Comment by sbutcher-arm** [comment]
@hanno-arm - Looks like a backport is needed to 2.7. Is there a reason we don't have one?

**Comment by hanno-arm** [comment]
@sbutcher-arm As this is a documentation enhancement only, I didn't consider the PR for a backport. Do you think it's worth creating one?

**Comment by sbutcher-arm** [comment]
It's an omission in the documentation, so yes, we should backport. Can you please create another PR.

**Comment by hanno-arm** [comment]
@sbutcher-arm #2356

**Pull request merged**
