### PR TITLE
Fix minor doc issue

### PR DESCRIPTION
**Pull request by attilamolnar**

### CODE REVIEW

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by sbutcher-arm** [comment]
Hi @attilamolnar 

I know this is trivial fix, but unfortunately our policy is to not accept contributions without a CLA.

To accept the contribution and any future contribution we will need a Contributor’s Licence Agreement (CLA) signed by yourself or by whoever has the authority to do so. You can [find an agreement to sign here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/), which can be signed and returned to us, or you could create an mbed account and [accept a slightly different agreement here with a click through](https://developer.mbed.org/contributor_agreement/) if this is a personal contribution. 

Thanks in advance for your understanding.

**Comment by attilamolnar** [comment]
Hi,

This is a personal contribution so I have created an mbed account (https://developer.mbed.org/users/attilamolnar/) and accepted the contributor agreement.

**Comment by sbutcher-arm** [comment]
Thanks for responding so quickly! I have now merged the fix.

**Pull request merged**
