### PR TITLE
[baremetal] Use mbedtls_platform_memset()

### PR DESCRIPTION
**Pull request by mpg**
## Description

This PR makes sure that the function `mbedtls_platform_memset()` introduced by #2870 is used in all relevant places in the library, while trying to minimise the impact on code size. It does that in two steps:

1. Replace `memset()` with `mbedtls_platform_memset()` everywhere.
2. Revert to `memset()` in places that are identified as safe and relevant with `config/baremetal.h`.

Impact on code size (sum of the three libraries in bytes, with armcc 5):

| | total | diff from previous line | diff from first line |
| --- | --- | --- | --- |
| before this PR | 43572 | | |
| after step 1 | 43672 | +100 | +100 |
| after step 2 | 43724 | -48 | +52 |

__Note to gatekeeper:__ This PR is based on #2870 which needs to be merged first.

__Note to reviewers:__ The first commit in this PR (not in #2870) is "Replace memset() with mbedtls_platform_memset()". Earlier commits need not be reviewed here.

_See also:_ Siblings PRs #2876 and #2880 do the same for `memcpy()` and `memcmp()` respectively.

## Status
**READY**

### CODE REVIEW

**Comment by sbutcher-arm** [comment]
After reviewing this PR with @mpg, I've decided to promote it back to 'ready for merge'.

I do think rework (or further review and debate) is required before upstreaming but for baremetal this PR is acceptable.

**Comment by sbutcher-arm** [comment]
@mpg - I went to merge this PR and found a merge conflict with PR #2870. Could you please look at this? Looks like it needs rebasing.

**Comment by mpg** [comment]
@sbutcher-arm Sorry for that and thanks for noticing. I've rebased on top of current #2870 in order to fix the problem.

@jarvte @jarlamsa Since your previous approval I've rebased on top of #2870 in order to resolve a conflict, and I also took this opportunity to add a new commit to revert to `memset()` in a place (HMAC-DRBG seeding) where I noticed in the meantime that it was safe to do so. Could you review again? Thanks!

**Comment by mpg** [comment]
@jarlamsa @jarvte I just added a commit to fix an issue found by the CI. Please review again.

@sbutcher-arm The API-ABI check is expected to fail in the pr-head job and succeed in the pr-merge job. As discussed earlier, this is an artifact of how it picks versions, and can be ignored (as implemented, this check really only makes sense in the pr-merge job).

**Comment by mpg** [comment]
With two approvals, a CI that's passing except for the expected and non-significant failure of the API-ABI checked in the pr-head job (passing in the pr-merge job where it actually makes sense), no conflicts, and its single dependency also ready for merge (and now a proper git ancestor), this PR is ready for merge again.

**Pull request merged**
