### PR TITLE
Backport 2.16: Fix x86_64 assembly for bignum multiplication

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Backport of #4947

### CODE REVIEW

**Review by davidhorstmann-arm — APPROVED** [review]
Have double-checked the fix locally

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM!

**Review by xffbai — APPROVED** [review]
LGTM

**Comment by gilles-peskine-arm** [comment]
pr-merge had a failure in a test with a known race condition, pr-head passed, so the CI is acceptable.

**Pull request merged**
