### PR TITLE
Rename existing support macros for output buffer sizes for PSA Crypto API 1.0.0

### LINKED ISSUE #3268: PSA: update support macros for output buffer sizes since API 1.0 beta 3
The support macros for output buffers are up to date for PSA Crypto API 1.0 beta 3 but not for 1.0.0 final. The current macros have somewhat inconsistent naming and some are missing or don't take the right parameters.

The goal of this task is to define the new macros. Keep the existing ones as aliases for backward compatibilty in `crypto_compat.h`.

See the [specification](https://armmbed.github.io/mbed-crypto/psa/#application-programming-interface) for a list. The [section on changes](https://armmbed.github.io/mbed-crypto/html/appendix/history.html#changes-between-1-0-beta-3-and-1-0-0) enumerates the macros that have changed since beta 3 (which was aligned with Mbed Crypto by construction). The [private discussion](https://github.com/ARMmbed/psa-crypto-api/pull/293) may be useful.

The following macros are currently missing (they may be present under an older name):

- [x] PSA_AEAD_DECRYPT_OUTPUT_MAX_SIZE
- [x] PSA_AEAD_ENCRYPT_OUTPUT_MAX_SIZE
- [x] PSA_AEAD_FINISH_OUTPUT_MAX_SIZE
- [x] PSA_AEAD_TAG_MAX_SIZE
- [x] PSA_AEAD_UPDATE_OUTPUT_MAX_SIZE
- [x] PSA_AEAD_VERIFY_OUTPUT_MAX_SIZE
- [x] PSA_ASYMMETRIC_DECRYPT_OUTPUT_MAX_SIZE
- [x] PSA_ASYMMETRIC_ENCRYPT_OUTPUT_MAX_SIZE
- [x] PSA_BLOCK_CIPHER_BLOCK_MAX_SIZE
- [x] PSA_BLOCK_CIPHER_BLOCK_LENGTH
- [x] PSA_CIPHER_DECRYPT_OUTPUT_MAX_SIZE
- [x] PSA_CIPHER_DECRYPT_OUTPUT_SIZE
- [x] PSA_CIPHER_ENCRYPT_OUTPUT_MAX_SIZE
- [x] PSA_CIPHER_ENCRYPT_OUTPUT_SIZE
- [x] PSA_CIPHER_FINISH_OUTPUT_MAX_SIZE
- [x] PSA_CIPHER_FINISH_OUTPUT_SIZE
- [x] PSA_CIPHER_UPDATE_OUTPUT_MAX_SIZE
- [x] PSA_CIPHER_UPDATE_OUTPUT_SIZE
- [x] PSA_EXPORT_KEY_OUTPUT_SIZE
- [x] PSA_EXPORT_KEY_PAIR_MAX_SIZE
- [x] PSA_EXPORT_PUBLIC_KEY_MAX_SIZE
- [x] PSA_EXPORT_PUBLIC_KEY_OUTPUT_SIZE
- [x] PSA_HASH_LENGTH
- [x] PSA_MAC_LENGTH
- [x] PSA_RAW_KEY_AGREEMENT_OUTPUT_MAX_SIZE
- [x] PSA_RAW_KEY_AGREEMENT_OUTPUT_SIZE
- [x] PSA_TLS12_PSK_TO_MS_PSK_MAX_SIZE

Related: https://github.com/ARMmbed/mbedtls/issues/3269: the usage of these macros in the library and in tests.

### PR DESCRIPTION
**Pull request by gabor-mezei-arm**
This PR contains only the renames of the buffer size macros.
The newly introduced macros are in #3386.

Fixes parts of #3268

### CODE REVIEW

**Comment by bensze01** [comment]
For the benefit of any other reviewers: Compare and contrast #3967, which set out to do the same thing.

**Review by bensze01 — CHANGES_REQUESTED** [review]
include/psa/crypto_sizes.h: [L307-L313](https://github.com/ARMmbed/mbedtls/blob/e92e0c0fba1854341f0c40984ce7d9d8fe54ca3b/include/psa/crypto_sizes.h#L307-L313) and [L667-L673](https://github.com/ARMmbed/mbedtls/blob/e92e0c0fba1854341f0c40984ce7d9d8fe54ca3b/include/psa/crypto_sizes.h#L667-L673)
```diff
--- a/include/psa/crypto_sizes.h
+++ b/include/psa/crypto_sizes.h
@@ -307,7 +307,7 @@
  * implementation to delay the output until it has a full block. */
 #define PSA_AEAD_UPDATE_OUTPUT_SIZE(alg, input_length)                  \
     (PSA_ALG_IS_AEAD_ON_BLOCK_CIPHER(alg) ?                             \
-     PSA_ROUND_UP_TO_MULTIPLE(PSA_MAX_BLOCK_CIPHER_BLOCK_SIZE, (input_length)) : \
+     PSA_ROUND_UP_TO_MULTIPLE(PSA_BLOCK_CIPHER_BLOCK_MAX_SIZE, (input_length)) : \
      (input_length))

 /** A sufficient ciphertext buffer size for psa_aead_finish().
@@ -667,7 +667,7 @@
  *         and AEAD algorithm that it recognizes, but does not support.
  */
 #define PSA_AEAD_NONCE_LENGTH(key_type, alg) \
-    (PSA_BLOCK_CIPHER_BLOCK_SIZE(key_type) == 16 && \
+    (PSA_BLOCK_CIPHER_BLOCK_LENGTH(key_type) == 16 && \
          (PSA_ALG_AEAD_WITH_DEFAULT_TAG_LENGTH(alg) == PSA_ALG_CCM || \
           PSA_ALG_AEAD_WITH_DEFAULT_TAG_LENGTH(alg) == PSA_ALG_GCM) ? 12 : \
      (key_type) == PSA_KEY_TYPE_CHACHA20 && \
```
ChangeLog.d:
```diff
--- /dev/null
+++ b/ChangeLog.d/psa-crypto-rename-output-buffer-size-macros.txt
@@ -0,0 +1,9 @@
+API changes
+   * Renamed the PSA Crypto API output buffer size macros to bring them in line
+     with version 1.0.0 of the specification.
+
+New deprecations
+   * PSA_KEY_EXPORT_MAX_SIZE, PSA_HASH_SIZE, PSA_MAC_FINAL_SIZE,
+     PSA_BLOCK_CIPHER_BLOCK_SIZE, PSA_MAX_BLOCK_CIPHER_BLOCK_SIZE and
+     PSA_ALG_TLS12_PSK_TO_MS_MAX_PSK_LEN have been renamed, and the old names
+     deprecated.
```
Aside from the changes I requested, the other differences between this PR and #3967 are out of scope (renaming `PSA_ALG_AEAD_WITH_DEFAULT_TAG_LENGTH` to `PSA_ALG_AEAD_WITH_DEFAULT_LENGTH_TAG` and `PSA_ALG_AEAD_WITH_TAG_LENGTH` to `PSA_ALG_AEAD_WITH_SHORTENED_TAG`).

I will repurpose that #3967 to upstream these remaining, out of scope renames.

**Review by bensze01 — DISMISSED** [review]
Looks good to me.

**Review by ronald-cron-arm — CHANGES_REQUESTED** [review]
Looks almost good to me. I've just some minor comments.

**Review by ronald-cron-arm — APPROVED** [review]
Thanks for the changes. This looks good to me now.

**Comment by ronald-cron-arm** [comment]
@bensze01 still ok for you ?

**Review by bensze01 — APPROVED** [review]
@ronald-cron-arm Yes, the changes since my last approval look ok as well.

**Pull request merged**
