### PR TITLE
Fix compile-time size checking for MBEDTLS_ECDSA_MAX_LEN

### PR DESCRIPTION
**Pull request by zeil**
3 + 2 \* ( 3 + 124 ) = 257 but we want total len <= 255

### CODE REVIEW

**Comment by sbutcher-arm** [comment]
I've reviewed this and am happy to merge it, but we have a policy to not accept any contributions without a CLA (Contributor's License Agreement) which applies to this pull request even if it's a single byte fix. I really can't see how this fix could be more trivial, but I'm afraid that's the policy we have.

If this is a _personal contribution_, the easiest way to approve a CLA is to create an mbed account and accept an agreement online with [a click through agreement here](https://developer.mbed.org/contributor_agreement/). 

Alternatively you can sign a slightly different agreement, which can be found [here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/), which must be signed and returned to us. This type of agreement is necessary for a Corporate contribution and must be signed by someone with authority to do so.

Thanks for your understanding!

**Comment by RonEld** [comment]
Hi @zeil Please confirm that [this](https://os.mbed.com/users/zeil/) is your Mbed zccount

**Comment by zeil** [comment]
Hello! Yes, this is my mbed account.

**Comment by gilles-peskine-arm** [comment]
CI succeeded except for timing tests (known test issue).

**Comment by gilles-peskine-arm** [comment]
Hi @zeil ,

The purpose of the check is to verify that the formula for `MBEDTLS_ECDSA_MAX_LEN` below is correct. That formula assumes that the length of the sequence can be encoded in at most two bytes in ASN.1, hence the 3 (1 tag byte + 2 length bytes). A length *n* of up to 127 is encoded as one byte *n*, and a length of 128 to 255 is encoded as `0x81` *n*. A length of 256 to 65535 would be encoded as three bytes `0x82` *n₁* *n₀*, which would take more space than is allowed by `MBEDTLS_ECDSA_MAX_LEN`. That's the length of the *content* of the sequence, i.e. the two INTEGERs, which themselves each occupy at most `ECP_MAX_BYTES` plus 1 byte of tag plus at most 2 bytes of length, i.e. the length of the content is at most `2 * (3 + MBEDTLS_ECP_MAX_BYTES)`. This is the number that needs to be ≤255, and so `MBEDTLS_ECP_MAX_BYTES`=124 fits. Therefore I believe the current check is correct.

Do you see a reason why the *total* length of the encoded SEQUENCE, and not the *content* of the sequence, would need to be at most 255 bytes long?

**Comment by mpg** [comment]
We've carefully reviewed the code and believe it is correct, as explained by Gilles above. Therefore I'm closing this as not a bug. If you disagree, please re-open and explain where you disagree with Gilles's explanation. Thanks again for your interest in Mbed TLS.

**Pull request closed without merging**
