### PR TITLE
ssl-opt.sh: wait for proxy to start before running the script further

### PR DESCRIPTION
**Pull request by AndrzejKurek**
Resolves issue IOTSSL-2885.

### CODE REVIEW

**Comment by Patater** [comment]
We probably ought to backport this after getting another review.

**Comment by AndrzejKurek** [comment]
> We probably ought to backport this after getting another review.

Yep, that's the plan.

**Comment by mpg** [comment]
Please do backport it to 2.16, so that it lands in baremetal next time we merge from it!

**Comment by AndrzejKurek** [comment]
Backports created.

**Comment by mpg** [comment]
Backports are approved and should be ready as soon as CI finishes running on them.

**Pull request merged**
