### PR TITLE
Backport 2.x: doc improvements in aes and sha256 includes

### PR DESCRIPTION
**Pull request by tom-cosgrove-arm**
- Add return value description to the docs of mbedtls_sha256
- Remove description of non-existing "mode" parameter from the docs of mbedtls_aes_crypt_ctr

Backport of #5105

### CODE REVIEW

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM, thanks!

**Review by davidhorstmann-arm — CHANGES_REQUESTED** [review]
Whoops I forgot - could you add the sha256 doc to `mbedtls_sha256_ret()` as @gilles-peskine-arm mentioned [here](https://github.com/ARMmbed/mbedtls/pull/5105#pullrequestreview-799283420)

**Comment by tom-cosgrove-arm** [comment]
@davidhorstmann-arm oops, sorry, missed that - done on both PRs

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM, thanks!

**Review by gilles-peskine-arm — APPROVED** [review]

**Pull request merged**
