### PR TITLE
PSA storage format test case generator

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
This pull requests augments `generate_psa_tests.py` to generate test cases for the stability of the storage format, working towards [key storage testing](https://github.com/ARMmbed/mbedtls/blob/development/docs/architecture/testing/psa-storage-format-testing.md#user-content-key-storage-testing). The goal of this pull request is to set up the framework and use it for some easily generated test data. Coverage is out of scope.

Good coverage of the storage format will require further work. I have identified the following gaps, there may be more:
* Test how the key id relates to the storage file.
* Test lifetime values.
* For each algorithm, generate keys of compatible types and with sensible usage flags, and exercise the key in read tests.
* Test attempts to read a key of a type that is not supported in the current configuration, or with a policy that uses metadata that is not supported (version, algorithm, usage flags, …).

Many test cases are skipped because their `PSA_WANT_xxx` dependency symbols are not in place yet. This should be resolved once all the `PSA_WANT_xxx` symbols are declared in `include/psa/crypto_config.h`.

### CODE REVIEW

**Comment by d3zd3z** [comment]
Typo in the last commit text: "parameeters".

**Review by d3zd3z — DISMISSED** [review]
Other than the typo, the code change looks good.

**Comment by gilles-peskine-arm** [comment]
I amended the last commit to fix the typo in the commit message.

**Review by d3zd3z — APPROVED** [review]

**Comment by tom-daubney-arm** [comment]
Two minor typos in tests/suites/test_suite_psa_crypto_storage_format.function:

Ln 169-170: "The stability of the test data in future versions of ~~the~~ Mbed TLS will guarantee..." --> remove "the"
Ln 214: "past versionf of Mbed TLS." --> change "versionf" to "versions".

Otherwise all changes LGTM. Will approve as soon as typos are corrected.

**Review by tom-daubney-arm — APPROVED** [review]
Great, thanks for the small fixes. All LGTM now.

**Review by d3zd3z — APPROVED** [review]

**Pull request merged**
