### PR TITLE
Fix use-after-scope error in programs/ssl

### PR DESCRIPTION
**Pull request by bensze01**
## Description
This PR fixes a use-after-scope error in `programs/ssl/ssl_client2.c` and `programs/ssl/ssl_server2.c`.

## Status
**READY**

## Requires Backporting
NO

## Migrations
If there is any API change, what's the incentive and logic for it.

NO

### CODE REVIEW

**Review by paul-elliott-arm — COMMENTED** [review]
The code seems fine, but a couple of questions:

1. Given this is a bugfix, wouldn't this require a changelog entry?
2. Also given its a bugfix, why not backport?

**Comment by bensze01** [comment]
@paul-elliott-arm AFAIK this bug only affects a sample program, testing DTLS-SRTP, support for which was added only in the latest release (i.e. not in the LTS branches). I didn't include a changelog entry, because it didn't affect the main library.

**Review by paul-elliott-arm — DISMISSED** [review]
LGTM

**Comment by bensze01** [comment]
I've added a changelog entry.

**Review by paul-elliott-arm — APPROVED** [review]
Looks even better now :)

**Review by chris-jones-arm — APPROVED** [review]
LGTM.

**Pull request merged**
