### PR TITLE
CMake: generate the list of test suites automatically

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
We keep forgetting to register new test suites in `tests/CMakeLists.txt`. To
fix this problem once and for all, remove the need for manual registration.

The following test suites were missing:

    test_suite_cipher.aria
    test_suite_psa_crypto_driver_wrappers
    test_suite_psa_crypto_generate_key.generated

Backport: https://github.com/ARMmbed/mbedtls/pull/5465

### CODE REVIEW

**Review by AndrzejKurek — DISMISSED** [review]

**Review by d3zd3z — DISMISSED** [review]

**Comment by mpg** [comment]
@gilles-peskine-arm The CI fails in `test_cmake_as_subdirectory` (only in the pr-merge job, though).

**Comment by gilles-peskine-arm** [comment]
@mpg Thanks for letting me know! Previous pr-merge jobs passed, so this is a conflict with https://github.com/ARMmbed/mbedtls/pull/5385. I can reproduce the failure on my machine, but I don't understand it yet. Once I find a fix I'll probably push a new version of this PR rebased on top of the merge of https://github.com/ARMmbed/mbedtls/pull/5385.

**Comment by gilles-peskine-arm** [comment]
Actually the failure is non-deterministic. #5385 is probably a red herring.

**Comment by gilles-peskine-arm** [comment]
I can reproduce the failure of `test_cmake_as_subdirectory` intermittently on Ubuntu 16.04. I can't reproduce it on Ubuntu 20.04. I think this is in fact the known issue https://github.com/ARMmbed/mbedtls/issues/5223, which we decided to work around rather than fix. I guess we should expand the workaround to other components that do an out-of-source build: `test_cmake_as_subdirectory`, `test_cmake_as_package`, `test_cmake_as_package_install`.

**Comment by gilles-peskine-arm** [comment]
I took the same workaround for https://github.com/ARMmbed/mbedtls/issues/5223 from https://github.com/ARMmbed/mbedtls/pull/5233 and applied it to the similar cmake jobs. I also removed a bit of dead code I noticed in `all.sh`. I made similar patches to the backport.

**Review by AndrzejKurek — APPROVED** [review]

**Review by d3zd3z — APPROVED** [review]

**Pull request merged**
