### PR TITLE
doxygen: add missing asterisk to group closures

### PR DESCRIPTION
**Pull request by AndrzejKurek**
Clarify section names next to closing braces

Partially fixing Issue https://github.com/ARMmbed/mbedtls/issues/3497
Related PRs: #5371, #5372

### CODE REVIEW

**Review by d3zd3z — APPROVED** [review]
Looks good to me

**Review by mprse — APPROVED** [review]

**Review by minosgalanakis — APPROVED** [review]
LGTM

**Comment by gilles-peskine-arm** [comment]
Please backport to 2.28.

**Comment by AndrzejKurek** [comment]
I also found one missing asterisk in `ecp.h` that is not picked up by the current doxygen generating script.

**Review by minosgalanakis — APPROVED** [review]
LGTM

**Review by gilles-peskine-arm — APPROVED** [review]

**Pull request merged**
