### PR TITLE
Backport 2.x: Fix builds when config.h only defines MBEDTLS_BIGNUM_C

### LINKED ISSUE #4929: missing limits.h in bignum.c
### Summary

File **library/bignum.c** is using CHAR_BIT macro but does not include **limits.h**.

The file does not compile when other included headers do not include **limits.h**, for instance on Linux/glibc/gcc 10.3.0.

### System information

Mbed TLS version (number or commit id): 3c28fd3393a2e85
Operating system and version: Gentoo Linux x86_64, glibc
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): -O2 -march=native
Additional environment information: 

### Expected behavior

everything compiles

### Actual behavior

library/bignum.c does not compile

### Steps to reproduce

Attempt to build with gcc 10.3.0 on Glibc'ish Linux with MBEDTLS_BIGNUM_C is enabled

### Additional information

I suggest that you add **#include <limits.h>** to **bignum.c**.

### PR DESCRIPTION
**Pull request by tom-cosgrove-arm**
Backport of https://github.com/ARMmbed/mbedtls/pull/5269

### CODE REVIEW

**Review by davidhorstmann-arm — DISMISSED** [review]
LGTM! I have checked that this builds locally against a `config.h` containing only `#define MBEDTLS_BIGNUM_C`

**Review by daverodgman — DISMISSED** [review]

**Comment by daverodgman** [comment]
From a very quick look, 2.16 doesn't build in this configuration, and a trivial backport of this doesn't fix it (`fatal error: 'string.h' file not found`). I don't think that it is worth chasing this in 2.16.

**Comment by gilles-peskine-arm** [comment]
What about `development`?

**Comment by daverodgman** [comment]
> What about `development`?

Good point, confirmed that it's needed & a trivial fwd-port fixes it. I'll push a PR.

**Review by daverodgman — APPROVED** [review]

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM

**Pull request merged**
