### PR TITLE
Fix GCC format-signedness warnings

### PR DESCRIPTION
**Pull request by kennethsoerensen**
Please see https://github.com/ARMmbed/mbed-crypto/pull/362

Signed-off-by: Kenneth Soerensen <knnthsrnsn@gmail.com>

### CODE REVIEW

**Comment by mpg** [comment]
Thanks for submitting again!

Unfortunately `test-ref-configs.pl` is now failing: https://travis-ci.org/github/ARMmbed/mbedtls/jobs/669755076 - I looked at the results of our internal CI (sorry they're not available publicly yet) and that seems to be the only failure (related to this PR). Could you look into those warnings and fix them as well? Thanks!

**Comment by mpg** [comment]
Oops, sorry, I nearly overlooked one: `tests/scripts/all.sh test_variable_ssl_in_out_buffer_len_CID` is failing as well:
```
/var/lib/build/programs/ssl/ssl_client2.c:2236:29: error: format '%x' expects argument of type 'unsigned int', but argument 2 has type 'int' [-Werror=format=]
             mbedtls_printf( " failed\n  ! mbedtls_ssl_conf_cid_len returned -%#04x\n\n",
/var/lib/build/programs/ssl/ssl_server2.c:3051:29: error: format '%x' expects argument of type 'unsigned int', but argument 2 has type 'int' [-Werror=format=]
             mbedtls_printf( " failed\n  ! mbedtls_ssl_conf_cid_len returned -%#04x\n\n",
```

**Comment by mpg** [comment]
Thanks for fixing the issues with `test-ref-configs.pl`. Unfortunately the other test is still failing:
```
% tests/scripts/all.sh test_variable_ssl_in_out_buffer_len_CID 
[...]
[ 36%] Building C object programs/ssl/CMakeFiles/ssl_client2.dir/ssl_client2.c.o
/home/manpeg01/src/mbedtls/programs/ssl/ssl_client2.c: In function ‘report_cid_usage’:
/home/manpeg01/src/mbedtls/programs/ssl/ssl_client2.c:1069:25: error: format ‘%x’ expects argument of type ‘unsigned int’, but argument 2 has type ‘int’ [-Werror=format=]
         mbedtls_printf( " failed\n  ! mbedtls_ssl_get_peer_cid returned -0x%x\n\n",
                         ^
/home/manpeg01/src/mbedtls/programs/ssl/ssl_client2.c:1093:29: error: format ‘%x’ expects argument of type ‘unsigned int’, but argument 2 has type ‘int’ [-Werror=format=]
             mbedtls_printf( " failed\n  ! mbedtls_ssl_get_peer_cid returned -0x%x\n\n",
                             ^
/home/manpeg01/src/mbedtls/programs/ssl/ssl_client2.c:1103:29: error: format ‘%x’ expects argument of type ‘unsigned int’, but argument 2 has type ‘int’ [-Werror=format=]
             mbedtls_printf( " failed\n  ! mbedtls_ssl_get_peer_cid returned -0x%x\n\n",
                             ^
cc1: all warnings being treated as errors
```
Could you fix that as well? Thanks!

**Comment by danh-arm** [comment]
Hi @kennethsoerensen. Your PR looks good but unfortunately another recently merged PR conflicts with this. Could you resolve the conflicts and push again? Thanks, Dan.

**Comment by mpg** [comment]
@kennethsoerensen One last thing I nearly forgot: our policy is to acknowledge all external contributions in our ChangeLog. Could you add a new file in `ChangeLog.d` (see `00README.md`in the directory) for your contribution? Suggested content:
```
Changes
   * Fix warnings about signedness issues in format strings. The build is now clean of -Wformat-signedness warnings. Contributed by <your name and/or affiliation in your preferred form> in #3153.
```
Thanks!

**Pull request merged**
