### PR TITLE
Remove dependency of built-in keys on storage

### LINKED ISSUE #4877: Remove dependency on key storage for built-in keys
### Suggested enhancement
The Mbed TLS library has a dependency on key storage to be able to load built-in keys. This is not something that should be mandated.

### Justification

Mbed TLS needs this so that devices can use built in keys without having to use ITS resources.

### PR DESCRIPTION
**Pull request by silabs-ArchanaM**
## Description
The psa_open_key API depends on MBEDTLS_PSA_CRYPTO_STORAGE_C.
This is unnecessary for built-in keys and so is fixed.
Fixes #4877 

## Status
**READY**

## Migrations
 NO

## Additional comments
Being a configuration update, test vectors do not follow through easily. Has been validated against silicon labs device suite.
Backport PR is #4954

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [x] Backported

## Steps to test or reproduce
A call to psa_open_key for a built-in key should return success with MBEDTLS_PSA_CRYPTO_STORAGE_C disabled.

### CODE REVIEW

**Comment by yanesca** [comment]
@silabs-ArchanaM thank you for your contribution! 

The `test_no_platform` component of `all.sh` is failing on the CI (`./tests/scripts/all.sh test_no_platform`):
```
test_suite_psa_crypto_slot_management ............................. FAIL
```

Could you please fix it?

**Review by mstarzyk-mobica — APPROVED** [review]

**Review by gabor-mezei-arm — APPROVED** [review]
Looks good to me

**Comment by silabs-ArchanaM** [comment]
@yanesca, Can this be merged ?
Anything holding this back ?

**Comment by gilles-peskine-arm** [comment]
"needs:backports " is what's holding this PR back. I agree that this should be backported to 2.2x. Can you please make a backport to `development_2.x`?

**Pull request merged**
