### PR TITLE
Remove two unused SSL error codes for Mbed TLS 3.0

### PR DESCRIPTION
**Pull request by hanno-arm**
The following SSL error codes are not used anywhere within the library:
* `MBEDTLS_ERR_SSL_UNKNOWN_CIPHER`
* `MBEDTLS_ERR_SSL_PEER_VERIFY_FAILED`

This PR removes them from the public API for Mbed TLS 3.0.

__Note:__ `MBEDTLS_ERR_SSL_PEER_VERIFY_FAILED` being unused comes as a surprise, at is seems to be reasonable to report it to the user upon peer CRT verification failure. However, this study (can potentially re-introduction of the code) can be left for 3.x, while the error code removal can only happen in 3.0.

### CODE REVIEW

**Review by davidhorstmann-arm — APPROVED** [review]

**Review by mpg — CHANGES_REQUESTED** [review]
This looks good to me, but since we seem to agree this is an API change, we should also agree that it needs a ChangeLog entry and a migration guide entry :) Though I agree that the migration guide entry can absolutely emphasize that most users will be unaffected.  people are only affected if they checked explicitly for this error in their code, which seems quite unlikely.

**Comment by hanno-arm** [comment]
I am still a bit puzzled by `MBEDTLS_ERR_SSL_PEER_VERIFY_FAILED` not being used. Also, I'm no longer sure that my claim

>  However, this study (can potentially re-introduction of the code) can be left for 3.x, while the error code removal can only happen in 3.0.

is actually true: Whatever we return currently when the peer's CRT verification fails, we can't suddenly change it in 3.x, can we? It would be an API break.

**Comment by gilles-peskine-arm** [comment]
> MBEDTLS_ERR_SSL_PEER_VERIFY_FAILED being unused comes as a surprise, at is seems to be reasonable to report it to the user upon peer CRT verification failure

Or not, because we return different error codes depending on the reason for the failure, right? (`MBEDTLS_ERR_X509_xxx` if the failure came from X.509, `MBEDTLS_ERR_SSL_BAD_HS_CERTIFICATE` if the SSL code didn't like the certificate, …)

**Comment by mpg** [comment]
Oops, I came here to participate in the discussion about `VERIFY_FAILED`, only to be informed by github that I merged that a few minutes ago... I actually merged #4447 which was based on this but didn't have the "needs: preceding PR" label... we should be more careful with stacked PRs: on the author side, labeling, and on the gatekeeper side, double-checking the description (which clearly mentioned it) before pressing "merged".

Coming back to the discussion: we indeed return `MBEDTLS_ERR_X509_CERT_VERIFY_FAILED` if the issue was found by `mbedtls_x509_crt_verify()`, as evidenced by our `ssl-opt.sh` tests for `"Authentication: ` - on failure we expect `X509 - Certificate verification failed` in the output, which is the stringification of that error.

Regarding whether it would be an API break to change what specific error code is returned: I think that's kind of a grey area. If the specific error codes were documented, then clearly it would be a break and wouldn't be permissible (unless for perhaps for pressing security reasons). Since it's not documented, it's a change of observable but undocumented behaviour, and IMO it would have to be judged on a case-by-case basis - how likely is it that a reasonable application would rely on that behaviour? Was that the only way to achieve this purpose? Etc.

Of course we could also decide to publicly document that it's never OK to rely on undocumented behaviour, and that if people want to be able to rely on some undocumented behaviour they should contact us and ask us to document said behaviour. I have a few personal notes (which I'll turn into a github ticket when I find the time) about improvements we could make to the "Backwards compatibility" section of `BRANCHES.md` (which btw should also be moved to the docs repo), and clarifying this is one of them.

**Pull request merged**
