### PR TITLE
[mbedtls-2.16] Typo fix in test_suite_asn1write.function

### LINKED ISSUE #2782: Typo in ASN1 test dependency
Hi,
I think I found a typo in the commit 0fbbc64.
Maybe I'm wrong, but I could not find `MBEDTLS_ASN1PARSE_C` anywhere, while `MBEDTLS_ASN1_PARSE_C` seems to be used in many files...
Because of this some tests were not enabled (message : "Test suite not enabled" ).
That's it, thanks !

### PR DESCRIPTION
**Pull request by AndrzejKurek**
This PR fixes #2782 , spotted by tmarti2.
This issue does not exist on development, it has been fixed in the so called meantime.
Signed-off-by: Andrzej Kurek <andrzej.kurek@arm.com>

### CODE REVIEW

**Comment by AndrzejKurek** [comment]
Both CI jobs failed on 

> Fatal error[LMS001]: License check failed.  Use the IAR License Manager to resolve the problem.

**Comment by gilles-peskine-arm** [comment]
The IAR license is being renewed. In the meantime we're ignoring the IAR jobs, and we've even temporarily disabled them (but this PR went through CI just before that).

**Comment by mpg** [comment]
The pr-merge job fully passed, and the pr-head job only failed in the IAR test which is a license issue, so independent from this PR.

**Comment by mpg** [comment]
Oops, pressed the wrong button, meant to merge that...

**Pull request merged**
