### PR TITLE
Add support for external ECDSA priv keys in pk.c

### PR DESCRIPTION
**Pull request by andresag01**
This patch adds support for external ECDSA private keys in the PK layer. This feature can be enabled/disabled via the macro `MBEDTLS_PK_ECDSA_ALT_SUPPORT` in `include/mbedtls/config.h`. This change includes:
* A new `mbedtls_pk_info_t` that includes the function pointers and description for ECDSA-alt.
* Wrapper functions that will forward a call from the PK abstraction layer to the external ECDSA private key implementation.
* A new API call `mbedtls_pk_setup_ecdsa_alt()` in `include/mbedtls/pk.h` that allows to set the callbacks for external ECDSA private key functions.
* Doxygen documentation.
* ChangeLog entry for the new feature.
* A new test in `tests/suites/test_suite_pk.function` and `tests/suites/test_suite_pk.data`.

### CODE REVIEW

**Comment by wipu-arm** [comment]
If I understood correctly what I quickly read, this feature still keeps the callback synchronous i.e. the thread is blocked until the callback function has finished its calculation. Unfortunately this doesn't help us with the HSM service case where the calculation is delegated via https.

**Comment by wipu-arm** [comment]
I have visualized the need for asynchronous callbacks in https://jira.arm.com/browse/ONSP-1877

**Comment by marcobrador** [comment]
Hi all,

Any update on that topic? Is there any plan to support external implementation of ECDSA?

Thanks in advance,
Marc

**Comment by gilles-peskine-arm** [comment]
Note that AFAIR, if you want `PK_ECDSA_ALT` keys to work as private keys in an SSL connection, I think you need an additional one-line patch so that the TLS code doesn't try to access the private key object as if it had the non-alt representation. https://github.com/ARMmbed/mbedtls/pull/1300/commits/858880686ebe4919b7c433c7a0d96c19ad47740c

**Comment by andresag01** [comment]
@sbutcher-arm: There have been API changes since this PR was opened. Would you like me to rebase and update it?

**Comment by mpg** [comment]
@andresag01 I can't speak for Simon, but as far as I'm concerned, since this PR hasn't received detailed code review yet, I think it would be better to rebase it before it does - that way we get the advantages of a rebase (cleaner history) without the inconvenience (disruption of review history).

Also, you'll probably want to address @gilles-peskine-arm's point and add some tests to make sure we didn't forget anything in the TLS modules. I'm pretty unlikely to approve this PR without tests for integration in the TLS modules.

**Comment by andresag01** [comment]
As discussed previously, there is a preexisting testing gap in the PK_RSA_ALT feature (and as a consequence on this one). Therefore, further work on this PR will not happen (for now) and I am now closing it to avoid any misunderstanding. If we decide we do want to continue this work in the future, then it can be reopened.

**Pull request closed without merging**
