### PR TITLE
Generate the private key file and generate the public key file

### PR DESCRIPTION
**Pull request by kemaqi**
It is very inconvenient to only generate the private key file during use, so it is more reasonable to increase the generation of the public key file

### CODE REVIEW

**Comment by ronald-cron-arm** [comment]
Thank you for your interest in Mbed TLS. Could you explain more the motivation of this PR? What does it bring to the project? You mentioned that it is "very inconvenient to only generate the private key file". Could you elaborate on that? In which use cases have you experienced this inconvenience.
 
Otherwise: each commit must have at least one Signed-off-by: line from the committer to certify that the contribution is made under the terms of the Developer Certificate of Origin.

**Comment by kemaqi** [comment]
> Thank you for your interest in Mbed TLS. Could you explain more the motivation of this PR? What does it bring to the project? You mentioned that it is "very inconvenient to only generate the private key file". Could you elaborate on that? In which use cases have you experienced this inconvenience.
> 
> Otherwise: each commit must have at least one Signed-off-by: line from the committer to certify that the contribution is made under the terms of the Developer Certificate of Origin.

Thanks ronald for reply.
       When some embedded devices use rsa encryption and decryption scenarios, in order to save processor processing time as much as possible, they usually define N, E, D and other parameters directly, and then use them directly, avoiding encoding conversion, extracting related parameters and other operations . However, the standard PKCS-related format is usually used in the scenario of interacting with the server, and the relevant parameters such as N, E, and D are not directly used. Therefore, in order to ensure convenient communication with the server, it is only necessary to generate RSA N, E,  D related parameters, generate the public key and provide it to the server.

**Comment by kemaqi** [comment]
> Thank you for your interest in Mbed TLS. Could you explain more the motivation of this PR? What does it bring to the project? You mentioned that it is "very inconvenient to only generate the private key file". Could you elaborate on that? In which use cases have you experienced this inconvenience.
> 
> Otherwise: each commit must have at least one Signed-off-by: line from the committer to certify that the contribution is made under the terms of the Developer Certificate of Origin.

Thanks ronald for reply.
When some embedded devices use rsa encryption and decryption scenarios, in order to save processor processing time as much as possible, they usually define N, E, D and other parameters directly, and then use them directly, avoiding encoding conversion, extracting related parameters and other operations . However, the standard PKCS-related format is usually used in the scenario of interacting with the server, and the relevant parameters such as N, E, and D are not directly used. Therefore, in order to ensure convenient communication with the server, it is only necessary to generate RSA N, E, D related parameters, generate the public key and provide it to the server.

**Review by chris-jones-arm — COMMENTED** [review]
I'm not sure I'm convinced by the use case of this PR. I can understand that in certain applications you only need to provide a public key file instead of a private key file however it seems quite limited in it's applications.

Remember that this is an **example** program which users can then customise to their own needs and I don't think most users would need two separate key files by default, if they did then they can implement it themselves for their specific use case. It will also take (marginally) more processing time to generate the extra file and extra storage to store it afterwards. While I don't think the extra processing time and storage are particularly significant in themselves I think together there is no need for everyone to be using this feature by default.

I do think that this could be turned into a command line option however which could provide the flexibility for users and also demonstrate in the code how to generate public keys.

**Comment by gilles-peskine-arm** [comment]
> I can understand that in certain applications you only need to provide a public key file instead of a private key file however it seems quite limited in it's applications.

It's not very common to need a public key file: often the key is certified by a PKI and the first step for that is a certificate signing request, which embeds the public key, and which you can generate with the sample program `cert_req`.

> Remember that this is an example program which users can then customise to their own needs

But conversely, it's good to have an example program demonstrating how to write a public key. However, this already exists in `key_app_writer`.

> It will also take (marginally) more processing time to generate the extra file and extra storage to store it afterwards.

Completely irrelevant for a sample program.

> I do think that this could be turned into a command line option however which could provide the flexibility for users and also demonstrate in the code how to generate public keys.

It is a command line option. But I'd suggest making the public key file generation optional: don't write a public key file by default, but do write one if the option `public_filename` is specified.

**Comment by daverodgman** [comment]
Closing. I think this is covered, as @gilles-peskine-arm comments above, by the existing example programs.

**Pull request closed without merging**
