### PR TITLE
replace win32 functions that are not allowed in windows 10 apps

### PR DESCRIPTION
**Pull request by joycepg**
In the Universal Windows Platform (UWP), only a subset of WIN32 API is available. FindFirstFile is not allowed, but FindFirstFileEx is allowed. Also lstrlen is not allowed. Attempting to use them will fail at link time of the app.
This pull request changes the use of the banned APIs to ones that work on all versions of Windows (desktop apps and Windows Store apps (also known as Universal Windows Applications or UWA)).

### CODE REVIEW

**Comment by sbutcher-arm** [comment]
Thanks for the contribution! To accept this we'll need to review the contribution and may need some modifications (which we may do ourselves), but first to accept or any future contributions we will need a Contributor’s Licence Agreement (CLA) signed or authorised by yourself. You can [find an agreement to sign here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/), which can be signed and returned to us, or you could create an mbed account and [accept a slightly different agreement here with a click through](https://developer.mbed.org/contributor_agreement/) if this is a personal contribution. 

Thanks for your understanding!

**Comment by joycepg** [comment]
I have emailed a scan of the signed agreement to the email address on the form.

**Comment by joycepg** [comment]
i notice that a similar pull request https://github.com/ARMmbed/mbedtls/pull/730 was opened a few months after this.

also, one of my changes is now no longer required - Microsoft have since added FindFirstFile to the allowed APIs for Store Apps.

**Comment by mazimkhan** [comment]
Closing as change no longer required and rework already going on in #730 and #1453.

**Pull request closed without merging**
