### PR TITLE
mbedTLS.def

### PR DESCRIPTION
**Pull request by ssrlive**
Definition file for the DLL version of the crypto library from mbedTLS

### CODE REVIEW

**Comment by sbutcher-arm** [comment]
Thanks for the contribution!

This looks really useful for Windows users. Can I ask how you generated the file? If you have a script or a means to export the `.def` file that we can automate, we can ensure the file is kept up to date automatically.

This looks really useful, but unfortunately we have a policy of only accepting contributions with a  Contributor’s Licence Agreement (CLA), signed or authorised by yourself.

The easiest way to do this is if you create an mbed account and [accept this click through agreement](https://developer.mbed.org/contributor_agreement/) which is applicable if this is a personal contribution. Alternatively, you can find a [slightly different agreement to sign here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/), which can be signed and returned to us, and is applicable if you don't want to create an mbed account or alternatively if this is a corporate contribution.

Thanks for your understanding!

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2090

**Comment by RonEld** [comment]
related to #470

**Comment by sbutcher-arm** [comment]
Hi @ssrlive

Just a reminder - without a signed CLA, we cannot accept your code contribution. As I state above, this can be done by a [click through agreement](https://os.mbed.com/contributor_agreement/), or alternatively, [by contract](https://www.mbed.com/en/about-mbed/contributor-license-agreements/).

**Comment by sbutcher-arm** [comment]
Looks like we should be able to use `cmake` in future to generate this file. See [here](https://blog.kitware.com/create-dlls-on-windows-without-declspec-using-new-cmake-export-all-feature/).

**Comment by sbutcher-arm** [comment]
Additional note - if we include a `.def` file, it should be included in the `.vcxproj`, `Makefile` and `cmake` files.

**Comment by sbutcher-arm** [comment]
Unfortunately without a CLA we can't accept this contribution, so I'm going to close this PR.

@ssrlive - If you do join up to Mbed and/or provide a CLA, please feel free to re-open this PR, or submit a new one.

To all else - this is still recognised as an issue in #470, and we will be addressing with use of CMake at, I hope, some point in the future.

**Pull request closed without merging**
