### PR TITLE
encode/parse CSR with 'challengePassword' attribute

### PR DESCRIPTION
**Pull request by viktorTarasov**
Include the 'challengePassword' attribute into Certificate Request.

The far target is to use it in the certificate enrollment procedure (SCEP or others).

### CODE REVIEW

**Comment by viktorTarasov** [comment]
PR rebased after fix of doxygen issues

**Comment by viktorTarasov** [comment]
PR rebased after fixing error (TAB instead of spaces in headers) reported by  _tests/scripts/check-names.sh_.

**Comment by sbutcher-arm** [comment]
Apologies for the long delay, but we're finally following up on some of these older PR's. 

Unfortunately we have a policy of only accepting contributions with a  Contributor’s Licence Agreement (CLA), signed or authorised by yourself, so to progress the contribution we really need a CLA.

The easiest way to do this is if you create an mbed account and [accept this click through agreement](https://developer.mbed.org/contributor_agreement/) which is applicable if this is a personal contribution. Alternatively, you can find a [slightly different agreement to sign here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/), which can be signed and returned to us, and is applicable if you don't want to create an mbed account or alternatively if this is a corporate contribution.

Thanks for your understanding!

**Comment by sbutcher-arm** [comment]
Hi @viktorTarasov,

Just a reminder - we can't accept the contribution without a CLA!

**Comment by viktorTarasov** [comment]
@sbutcher-arm 
> Just a reminder - we can't accept the contribution without a CLA!

I accepted 'Contribution Agreement' following the first link.

If it's not sufficient, how can I deliver the signed 'mbed Community Corporate Contributor License Agreement' ?
Could it be uploaded somewhere, sent by mail, ...?

**Comment by viktorTarasov** [comment]
Well, I see how to email it.

**Comment by RonEld** [comment]
@viktorTarasov Could you please send a link to your Mbed account? As github and Mbed accounts are not linked, we need to search manually for your account, using your account ID, 
Thank you for your cooperation

**Comment by viktorTarasov** [comment]
@RonEld 
_Could you please send a link to your Mbed account?_ 

https://os.mbed.com/users/vtarasov/

**Comment by daverodgman** [comment]
Closing as this has conflicts and has not been updated for some time.

**Pull request closed without merging**
