### PR TITLE
Backport 2.16: bn_mul.h: require at least ARMv6 to enable the ARM DSP code

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Fix the build on ARMv5TE in ARM mode. The assembly code in `bn_mul.h` uses DSP instructions that are not available on this particular architecture, so set the conditional compilation directives to exclude them.

Fix originally contributed in #2169 by @aurel32. I rebased to mbedtls-2.16 to facilitate testing and added a changelog entry and a non-regression test.

### CODE REVIEW

**Comment by jainvikas8** [comment]
I see a test [failure](https://jenkins-internal.mbed.com/blue/organizations/jenkins/mbedtls-pr-multibranch/detail/PR-2778-head/3/pipeline)

> DTLS proxy: duplicate every packet, server anti-replay off ............. FAIL
> ! pattern 'resend' MUST be present in the Client output
> ! outputs saved to o-XXX-548.log

Is this a known issue?

**Comment by AndrzejKurek** [comment]
@jainvikas8 Oh, DTLS proxy tests consistency was an issue some time ago, I thought that it has already been fixed :)

**Comment by gilles-peskine-arm** [comment]
The test failure is one instance of one DTLS test, presumably due to a timeout, which is a known problem and obviously unrelated to this PR. So CI is ok.

**Comment by gilles-peskine-arm** [comment]
@k-stachowiak It's ok, we resolve add/add changelog conflicts at merge time.

**Pull request merged**
