### PR TITLE
Backport: Fixed unchecked calls to mbedtls_md_setup in rsa.c (#502)

### PR DESCRIPTION
**Pull request by andresag01**
* Fixed unchecked calls to mbedtls_md_setup in rsa.c:

* style fixes

### CODE REVIEW

**Comment by yanesca** [comment]
+1

**Comment by sbutcher-arm** [comment]
@andresag01 - Please add the fix to the ChangeLog and resubmit the PR.

**Comment by andresag01** [comment]
Add ChangeLog entry and rebased on mbedtls-2.1.

**Comment by sbutcher-arm** [comment]
Reviewed, approved and merged.

**Pull request closed without merging**
