### PR TITLE
Backport 2.16: TAGS: Fix lookup in test/suites/!(test_suite_*).function

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Backport of https://github.com/ARMmbed/mbedtls/pull/4019

### CODE REVIEW

**Review by ronald-cron-arm — APPROVED** [review]
LGTM. Sorry missed this before to merge #4019.

**Comment by ronald-cron-arm** [comment]
@gabor-mezei-arm ok with this backport on your side ?

**Comment by gilles-peskine-arm** [comment]
For a trivial backport, it's ok to merge with one reviewer approval (but I prefer to wait for a CI approval).

**Review by gabor-mezei-arm — APPROVED** [review]
LGTM

**Pull request merged**
