### PR TITLE
Tests: add dependency on MBEDTLS_ECDSA_C where needed. (issue #1040)

### PR DESCRIPTION
**Pull request by gertvdijk**
Adjust dependencies on tests so that a configuration without
MBEDTLS_ECDSA_C/MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED will work.

Fixes GitHub issue: https://github.com/ARMmbed/mbedtls/issues/1040

Reproduce:

$ make clean
$ ./scripts/config.pl unset MBEDTLS_ECDSA_C
$ ./scripts/config.pl unset MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED
$ make check

Notes:
* Pull requests cannot be accepted until:
-  The submitter has [accepted the online agreement here with a click through](https://developer.mbed.org/contributor_agreement/) 
   or for companies or those that do not wish to create an mbed account, a slightly different agreement can be found [here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/)
  _I have accepted the agreement on the mbed TLS developer site, but unable to connect my GitHub account. See https://developer.mbed.org/forum/bugs-suggestions/topic/27991/ for bug report._
- The PR follows the [mbed TLS coding standards](https://tls.mbed.org/kb/development/mbedtls-coding-standards)

## Description
Add `MBEDTLS_ECDSA_C` dependency on some unit tests to allow for running unit tests with PASS result in configurations without this flag.

## Status
**READY**

## Requires Backporting
It's a simple bugfix. Not strictly 'required', but would be nice if 2.6.x would be fixed. `mbedtls-2.6` branch does not exist yet, though.

## Migrations
NO

## Additional comments
Any additional information that could be of interest

## Todos
- [x] Tests
- [x] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
See commit message. :)

### CODE REVIEW

**Comment by gertvdijk** [comment]
I'm not sure where to edit the ChangeLog at this time. 2.6.0 'branch' is closed (released). Should I add a new section...

     = mbed TLS x.x.x branch released xxxx-xx-xx

?

**Comment by RonEld** [comment]
HI @gertvdijk Than you for your contribution!
To answer your question, yes, a new Changelog entry should be in a section:
~~~
mbed TLS x.x.x branch released xxxx-xx-xx
~~~
As you did.
We will look into your contribution

**Comment by gertvdijk** [comment]
Thanks for considering this!

> Personally, I think adding a no-ecdsa.pl script is redundant, since then we will need a no-xxx.pl script for all other features\modules.

Fair enough. Feel free to cherry-pick the commits based on the need for `no-ecdsa.pl`. Or would you like me to remove the commit from the PR?

**Comment by mpg** [comment]
Hi @gertvdijk ! Thanks for your contribution. We think it's so useful that in the meantime, we've been addressing the same problem independently. Our take at it is in [this larger branch](https://github.com/mpg/mbedtls/commits/iotssl-1381-x509-verify-refactor) which is in the final stages of review and should be merged soon. We added a slightly more general [test script](https://github.com/mpg/mbedtls/commit/902bb6a018d05ee4ee0c471724d9640dcc8f835a) and [fixed the test suites](https://github.com/mpg/mbedtls/commit/43be6cda4719af291691e684a11e3cdd567953f7).

I tend to agree with Ron that we probably don't want a no-xxx.pl script for each module. Most of these dependencies issues arise when we can access different things with the same API (in this case different PK algorithms via the PK abstraction layer) so it probably makes more sense to have one script per abstraction layer rather than per module. The linked branch adds one for the PK and MD layers, and we might add one for the cipher layer some time too.

Again, thanks for your contribution, and if you want to review that part of our branch to make extra sure it solves the issue you were tackling, that would be really appreciated!

**Comment by gertvdijk** [comment]
Hi @mpg,

Thanks for addressing this in your refactor. It seems that one test is still failing in my configuration:

    $ git remote add mpg https://github.com/mpg/mbedtls.git
    $ git fetch --all
    $ git checkout -b issue1040-test upstream/development
      (currently 72ea31b0... Update version number to 2.6.0)
    $ git merge mpg/iotssl-1381-x509-verify-refactor
    $ make clean
    $ ./scripts/config.pl unset MBEDTLS_ECDSA_C
    $ ./scripts/config.pl unset MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED
    $ make check

Fails on

    test_suite_debug .................................................. FAIL

Running that script by itself:

    $ cd tests; ./test_suite_debug

shows that `Debug print certificate #2 (EC)` still fails.

Will make a PR for your branch then. :)

**Comment by mpg** [comment]
Thanks for spotting that! Actually I'm thinking maybe we should modify `depends-pkalgs.pl` to not disable the whole SSL thing but only specific key exchanges. (I think that's the reason the script missed that issue.) Would you like to do that in your PR?

**Comment by gertvdijk** [comment]
I've tried to understand what you are trying to do in `depends-pkalgs.pl`. It appears you indeed made the explicit assumption:

> SSL is not in the test suites anyways

I also see why you were doing it; those list of requirements are exploding in length. _It feels odd that those scripts are now responsible for listing the reverse dependencies._ Wouldn't it be better if we could just improve `config.pl` with an `unset-with-dependencies` subcommand? Would save a lot of work in many other scripts too.

Anyway, I managed to include it in the [PR](https://github.com/mpg/mbedtls/pull/1/files).

**Comment by mpg** [comment]
Thanks for adding that to the PR! That change looks good to me.

I agree that improving `config.pl` would be better in the long run, but I wanted a solution that works now. Also, your original script `no-ecdsa.pl` also listed a reverse dependency (though it was only one), so I guess it was already in the same line of making incremental improvements, rather than wait for a perfect solution later.

**Comment by mpg** [comment]
I merged your other PR in my branch, which is undergoing the last round of reviews as we speak before it is merged in development. I think this PR can now be closed - I'll let you do that if you agree.

Thanks again for your contribution and your reactivity to our feedback.

**Comment by gertvdijk** [comment]
Hi @mpg, good to hear about the progress and I'm looking forward to see all the good stuff included in the main branch.
As you said, let's close this for now! :)

**Pull request closed without merging**
