### PR TITLE
Backport 2.7: Rationalize Travis builds

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Mostly straightforward backport of #3218. Differences:

* There's no `psa_constant_names` in 2.7, and so no need for Python on Windows.
* In `all.sh`, `build_arm_none_eabi_gcc_arm5vte` didn't exist in 2.7, so I added it.

Like in the 2.16 backport (#3247), first backport (the applicable part of) #2821 because it's easier to keep all LTS branches in synch.

### CODE REVIEW

**Comment by ronald-cron-arm** [comment]
I consider it as a fair backport as well. What about to add in the description that one patch of #2821 has been dropped?

**Comment by gilles-peskine-arm** [comment]
> What about to add in the description that one patch of #2821 has been dropped?

Sorry, I don't understand. Which description? Which patch?

**Comment by ronald-cron-arm** [comment]
Which description: the description of the PR at the top of the page. Not sure this is the right name for it but I cannot find a better one: https://github.com/ARMmbed/mbedtls/pull/3248#issue-409373643.
Which patch: I should have said commit probably. Thus commit "Remove blocked branches" which has been dropped from #2821. Is that clearer?

**Comment by gilles-peskine-arm** [comment]
Why would the history in the 2.7 branch mention something that isn't relevant to the 2.7 branch? We don't normally do that and I don't see a good reason to start doing so.

**Comment by ronald-cron-arm** [comment]
It's just that in https://github.com/ARMmbed/mbedtls/pull/3248#issue-409373643 you describe what has been dropped from #3218 thus I was thinking why not doing it for #2821 as well.  Anyway, this is just a suggestion, I am fine if you feel that it is not worth mentioning what has been dropped (because not relevant to 2.7) from #2821 in that description.

**Comment by gilles-peskine-arm** [comment]
Ah, ok. I added “the applicable part of” in the PR description. Given the nature of that PR, I think that's enough detail.

**Comment by ronald-cron-arm** [comment]
ok, fine by me, thanks.

**Comment by gilles-peskine-arm** [comment]
I force-pushed a change in the commit "Travis: rebalance the Linux builds" because in this branch, it accidentally removed the call to `test-ref-configs.pl`.

**Pull request merged**
