### PR TITLE
[baremetal] tinycrypt ARM assembler and other optimisations

### PR DESCRIPTION
**Pull request by kjbracey-arm**
* Add T32/A32 assembler optimisations for core tinycrypt/microecc routines, for ARMC5 and GCC.
* Use fast integer types to avoid frequent narrowing instructions
* Use `__builtin_clz`
* Avoid boolean ops (speed optimisation, and to achieve constant-time intent. Boolean operations are generally not compiled as constant time on T32/A32).

Achieves something close to a doubling of speed of DTLS handshake on an M0+/M4 pair of devices.

### CODE REVIEW

**Comment by kjbracey-arm** [comment]
This seems to be showing the same test failures as #3749. So not apparently related to the PR.

**Comment by yogpan01** [comment]
@AndrzejKurek @shelib01 we need to get this in, can we check what is the failure and whether those are valid in baremetal context.

**Comment by shelib01** [comment]
> @AndrzejKurek @shelib01 we need to get this in, can we check what is the failure and whether those are valid in baremetal context.

@kjbracey-arm , @yogpan01 it seems it fails with armcc 5 compiler. And it is strange because other job with armcc 5 compiler that run baremetal only stuff passed. @kjbracey-arm , please add MBEDTLS_USE_TINYCRYPT flag to wrap this assembler functions, so we will be sure it is compiled only if TINYCRYPT should be used.

**Comment by AndrzejKurek** [comment]
I would rather suggest having these optimizations under a compilation flag, just so that the user can choose whether to compile it in or not.

**Comment by kjbracey-arm** [comment]
They're used if `MBEDTLS_HAVE_ASM` and `MBEDTLS_USE_TINYCRYPT`.   

Not totally sure, but I'm guessing that if `MBED_USE_TINYCRYPT` is active, we're not using the other `MBEDTLS_HAVE_ASM` implementation, so that flag is now just controlling this, rather than switching both simultaneously.

But we could add another flag like `MBEDTLS_HAVE_TINYCRYPT_ASM`.

**Comment by shelib01** [comment]
@kjbracey-arm , tinycrypt disabling worked, so  if we compiling the assembler code only when required, it does not have compilation problems. We will wrap it using some new added flag and merge it tomorrow

**Comment by kjbracey-arm** [comment]
I think that's effectively cheating - pass CI by ifdeffing out the new code :)

But maybe if the option is off by default, and we flag it with some sort of "experimental" or something, then it's kind of honest.

**Comment by shelib01** [comment]
> I think that's effectively cheating - pass CI by ifdeffing out the new code :)
> 
> But maybe if the option is off by default, and we flag it with some sort of "experimental" or something, then it's kind of honest.

@kjbracey-arm , new code was ifdefed out only if it shouldn't run. All places that use tinycrypt were compiled and tests performed. So I am not feeling bad  with it. The main question here if we need tinycrypt in this specific version of armc 5.0x compiler that  has compilation problem. If not we are fine, if yes we should continue to try to find the problem.

**Comment by kjbracey-arm** [comment]
What was the armc5 failure? Is it now ifdeffed out?

**Comment by AndrzejKurek** [comment]
> What was the armc5 failure? Is it now ifdeffed out?

Looking at previous failures:
ARM Compiler 6:
`ELF file has unsupported machine code 62 (we only handle EM_ARM = 40)`

ARM Compiler5:
```
"../tinycrypt/ecc.c", line 782: Error:  #667: "asm" function is nonstandard
  static __asm void uECC_vli_rshift1(uECC_word_t *vli)
  ^
"../tinycrypt/ecc.c", line 789: Warning:  #11-D: unrecognized preprocessing directive
      MOVS    r2,#__cpp(4 * (NUM_ECC_WORDS - 1))
                  ^
```
I took the liberty of introducing an additional flag for the optimizations and adding it to the baremetal config here: 
https://github.com/ARMmbed/mbedtls/pull/3785

**Comment by shelib01** [comment]
> What was the armc5 failure? Is it now ifdeffed out?

@kjbracey-arm , Lets make the stuff more clear: 
I dint ifdefout any compiler, I only ifdeffed out an option to compile this code if we don't run tinycrypt functionality at all. So if we have tinycrypt tests run with armc 5 compiler the tests compiled and run. 
For example this job passed with and without my changes :
```
 * armcc: /usr/local/ARM_Compiler_5.06u3/bin//armcc : Product: ARM Compiler 5.06

Component: ARM Compiler 5.06 update 3 (build 300) 

 * armclang: /usr/local/ARM_Compiler_6.6/bin//armclang : Product: ARM Compiler 6.6 Professional

Component: ARM Compiler 6.6 

 * arm-none-eabi-gcc: /opt/gcc-arm-none-eabi-5_4-2016q3/bin/arm-none-eabi-gcc : arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496] 



 * gcc: /usr/bin/gcc : gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609 

 * clang: /usr/bin/clang : clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)

Target: x86_64-pc-linux-gnu 

 * ldd: /usr/bin/ldd : ldd (Ubuntu GLIBC 2.23-0ubuntu10) 2.23 

 * valgrind: /usr/bin/valgrind : valgrind-3.11.0 

 * gdb: /usr/bin/gdb : GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1 



 * perl: /usr/bin/perl : This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi 

 * python: /usr/bin/python : Python 2.7.12 

 * pylint3: /usr/bin/pylint3 : pylint3 1.5.2,  


 * openssl (default): /usr/local/openssl-1.0.2g/bin/openssl : OpenSSL 1.0.2g  1 Mar 2016 



 * openssl (legacy): /usr/local/openssl-1.0.1j/bin/openssl : OpenSSL 1.0.1j 15 Oct 2014 



 * openssl (next): /usr/local/openssl-1.1.1a/bin/openssl : OpenSSL 1.1.1a  20 Nov 2018 



 * gnutls-cli (default): /usr/local/gnutls-3.4.10/bin/gnutls-cli : gnutls-cli 3.4.10 



 * gnutls-serv (default): /usr/local/gnutls-3.4.10/bin/gnutls-serv : gnutls-serv 3.4.10 



 * gnutls-cli (legacy): /usr/local/gnutls-3.3.8/bin/gnutls-cli : gnutls-cli 3.3.8 



 * gnutls-serv (legacy): /usr/local/gnutls-3.3.8/bin/gnutls-serv : gnutls-serv 3.3.8 



 * Installed asan versions:

libasan2: 5.4.0-6ubuntu1~16.04.11
```

******************************************************************

* **build_baremetal_raw_armcc**: build: scripts/baremetal.sh gcc/armc5/armc6 
  
This is the job that failed before I added the flag , and this job does not run tests with tinycrypt, but compiled the code for some reason (you can see Andrzej comment above for exact error and warnings) :

```
 export ARMLMD_LICENSE_FILE=7010@10.6.26.52:7010@10.6.26.53:7010@10.6.26.54:7010@10.6.26.56
+ export MBEDTLS_TEST_OUTCOME_FILE=all_sh-ubuntu-16.04-build_armcc-outcome.csv
+ ./tests/scripts/all.sh --seed 4 --keep-going build_armcc

******************************************************************
* info: ./tests/scripts/all.sh configuration 
* Tue Oct 13 08:34:28 UTC 2020
******************************************************************
MEMORY: 0
FORCE: 0
SEED: 4
OPENSSL: /usr/local/openssl-1.0.2g/bin/openssl
OPENSSL_LEGACY: /usr/local/openssl-1.0.1j/bin/openssl
OPENSSL_NEXT: /usr/local/openssl-1.1.1a/bin/openssl
GNUTLS_CLI: /usr/local/gnutls-3.4.10/bin/gnutls-cli
GNUTLS_SERV: /usr/local/gnutls-3.4.10/bin/gnutls-serv
GNUTLS_LEGACY_CLI: /usr/local/gnutls-3.3.8/bin/gnutls-cli
GNUTLS_LEGACY_SERV: /usr/local/gnutls-3.3.8/bin/gnutls-serv
ARMC5_BIN_DIR: /usr/local/ARM_Compiler_5.06u3/bin/
ARMC6_BIN_DIR: /usr/local/ARM_Compiler_6.6/bin/

******************************************************************
* info: output_env.sh 
* Tue Oct 13 08:34:28 UTC 2020
******************************************************************
** Platform:

Linux variant
Description:	Ubuntu 16.04.5 LTS
Codename:	xenial

 * uname: /bin/uname : Linux d7bca2fc9c2e 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux 


** Tool Versions:

 * armcc: /usr/local/ARM_Compiler_5.06u3/bin//armcc : Product: ARM Compiler 5.06
Component: ARM Compiler 5.06 update 3 (build 300) 

 * armclang: /usr/local/ARM_Compiler_6.6/bin//armclang : Product: ARM Compiler 6.6 Professional
Component: ARM Compiler 6.6 

 * arm-none-eabi-gcc: /opt/gcc-arm-none-eabi-5_4-2016q3/bin/arm-none-eabi-gcc : arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496] 

 * gcc: /usr/bin/gcc : gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609 

 * clang: /usr/bin/clang : clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu 

 * ldd: /usr/bin/ldd : ldd (Ubuntu GLIBC 2.23-0ubuntu10) 2.23 

 * valgrind: /usr/bin/valgrind : valgrind-3.11.0 

 * gdb: /usr/bin/gdb : GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1 

 * perl: /usr/bin/perl : This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi 

 * python: /usr/bin/python : Python 2.7.12 

 * pylint3: /usr/bin/pylint3 : pylint3 1.5.2,  

 * openssl (default): /usr/local/openssl-1.0.2g/bin/openssl : OpenSSL 1.0.2g  1 Mar 2016 

 * openssl (legacy): /usr/local/openssl-1.0.1j/bin/openssl : OpenSSL 1.0.1j 15 Oct 2014 

 * openssl (next): /usr/local/openssl-1.1.1a/bin/openssl : OpenSSL 1.1.1a  20 Nov 2018 

 * gnutls-cli (default): /usr/local/gnutls-3.4.10/bin/gnutls-cli : gnutls-cli 3.4.10 

 * gnutls-serv (default): /usr/local/gnutls-3.4.10/bin/gnutls-serv : gnutls-serv 3.4.10 

 * gnutls-cli (legacy): /usr/local/gnutls-3.3.8/bin/gnutls-cli : gnutls-cli 3.3.8 

 * gnutls-serv (legacy): /usr/local/gnutls-3.3.8/bin/gnutls-serv : gnutls-serv 3.3.8 

 * Installed asan versions:
libasan2: 5.4.0-6ubuntu1~16.04.11


******************************************************************
* build_armcc: build: ARM Compiler 5 
* Tue Oct 13 08:34:41 UTC 2020
****************************************************************** 
```
I don't know what exactly the difference between compilers or configurations here, it can be investigated later if needed(take into account that Andrzej and me are not assembler guru  ).

**Comment by AndrzejKurek** [comment]
I updated this PR with the latest version of the code, to see if the PR passes.

**Comment by kjbracey-arm** [comment]
The ""asm" function is nonstandard" error is I believe a response to being a `--strict` compile.

My previous attempts to nobble it with a "pragma diag_suppress" appear to still be failing. Don't know why.

From the compiler manual you could detect a strict compile with `#ifdef __STRICT_ANSI__`. Could undefine the new assembler flag if that's set.

I wouldn't have expected a a "--strict" compile to necessarily kill assembler optimisations, but I guess I can see the logic.

**Comment by AndrzejKurek** [comment]
Sorry for the confusion with updating two PR's, but the CI passed on https://github.com/ARMmbed/mbedtls/pull/3785. The only failure is related to changing the API/ABI of the library, because of these optimizations and removing tinycrypt code if the use_tinycrypt define isn't defined.
@kjbracey-arm - Are you aware of any case where tinycrypt is used through Mbed TLS by any application code without the actual `MBEDTLS_USE_TINYCRYPT` being defined when compiling the library?

**Comment by AndrzejKurek** [comment]
https://github.com/ARMmbed/mbedtls/pull/3785 passed the CI with the scrict / non strict changes.
There are however two things that, in my opinion, need to be clarified:
@kjbracey-arm:

- Warning for ARM Compiler 6:
`ELF file has unsupported machine code 62 (we only handle EM_ARM = 40)`

- Possible usage of tinycrypt by an external application without `MBEDTLS_USE_TINYCRYPT` defined (see my previous comment). Maybe @yogpan01 can help us with this?

**Comment by kjbracey-arm** [comment]
I have no idea who the other users of this branch are, so who would care about ABI changes. ABI changes are only an issue when providing shared libraries, which certainly happens on master for non baremetal systems, but I would assume this baremetal branch is never used in shared library form.

Note that the tinycrypt here is not the standard tinycrypt - it's been cut down in a number of ways already. I wouldn't have throught non-silent API changes were a problem.

The ABI change isn't a core part of the PR - it's a little bonus optimisation. If it's problematic you can just drop/revert that commit.

I saw the "unsupported machine code" warning, but assumed that was pre-existing - someone using a slightly mismatched "fromelf" with the compiler. Are you saying it is caused by this PR?

**Comment by AndrzejKurek** [comment]
> I have no idea who the other users of this branch are, so who would care about ABI changes. ABI changes are only an issue when providing shared libraries, which certainly happens on master for non baremetal systems, but I would assume this baremetal branch is never used in shared library form.
> 
> Note that the tinycrypt here is not the standard tinycrypt - it's been cut down in a number of ways already. I wouldn't have throught non-silent API changes were a problem.
> 
> The ABI change isn't a core part of the PR - it's a little bonus optimisation. If it's problematic you can just drop/revert that commit.
> 
> I saw the "unsupported machine code" warning, but assumed that was pre-existing - someone using a slightly mismatched "fromelf" with the compiler. Are you saying it is caused by this PR?

OK, about the "fromelf" - It is indeed pre-existing, checked it on the CI of a different PR.
Regarding the API/ABI changes - I'll contact Antti Kauppila to make sure we're good to merge it.
No other issues for now.

**Comment by shelib01** [comment]
@AndrzejKurek , i think we can merge it. All functions that were changed are internal tinycrypt functionality. Related to wrapping of TINYCRYPT by flag, I see that all crypto algs like AES ,CCM , ECDSA and others are wrapped. It seems tinycrypt was not wrapped by mistake

**Comment by AndrzejKurek** [comment]
PR closed as https://github.com/ARMmbed/mbedtls/pull/3785 was merged.

**Pull request merged**
