### PR TITLE
Backport 2.7: Fix missing depends in X509 test case

### LINKED ISSUE #911: X.509 test failure in configuration without SHA-1 and without 1/n-1 record splitting
On the configuration below, the test `test_suite_x509parse` fails:

```
X509 CRL Malformed Input (trailing spaces at end of file) ......... FAILED
  mbedtls_x509_crl_parse_file( &crl, crl_file ) == result
  at line 175, suites/test_suite_x509parse.function
```

Observed on tag `mbedtls-2.4.2` and in `development` as I write. Originally found by @andresag01 [while reviewing](https://github.com/ARMmbed/mbedtls/pull/904#issuecomment-300813372).

```
diff --git a/include/mbedtls/config.h b/include/mbedtls/config.h
index 0f7e29b..733412d 100644
--- a/include/mbedtls/config.h
+++ b/include/mbedtls/config.h
@@ -1043,7 +1043,7 @@
  *
  * Comment this macro to disable 1/n-1 record splitting.
  */
-#define MBEDTLS_SSL_CBC_RECORD_SPLITTING
+//#define MBEDTLS_SSL_CBC_RECORD_SPLITTING
 
 /**
  * \def MBEDTLS_SSL_RENEGOTIATION
@@ -1111,7 +1111,7 @@
  *
  * Comment this macro to disable support for TLS 1.0
  */
-#define MBEDTLS_SSL_PROTO_TLS1
+//#define MBEDTLS_SSL_PROTO_TLS1
 
 /**
  * \def MBEDTLS_SSL_PROTO_TLS1_1
@@ -1123,7 +1123,7 @@
  *
  * Comment this macro to disable support for TLS 1.1 / DTLS 1.0
  */
-#define MBEDTLS_SSL_PROTO_TLS1_1
+//#define MBEDTLS_SSL_PROTO_TLS1_1
 
 /**
  * \def MBEDTLS_SSL_PROTO_TLS1_2
@@ -2190,7 +2190,7 @@
  *
  * This module is required for SSL/TLS and SHA1-signed certificates.
  */
-#define MBEDTLS_SHA1_C
+//#define MBEDTLS_SHA1_C
 
 /**
  * \def MBEDTLS_SHA256_C
```

### PR DESCRIPTION
**Pull request by mpg**
This test file is signed with SHA1

fixes #911

### CODE REVIEW

**Comment by andresag01** [comment]
@mpg: The PEM file used in that particular test has two CRLs and they use ECDSA, SHA1 and SHA512. I havent tried but I think the test will still fail if PEM parsing and SHA1 are enabled but, say ECDSA is disabled. Perhaps these should also be added to the `depends_on`? i.e. `MBEDTLS_SHA1_C:MBEDTLS_ECDSA_C:MBEDTLS_SHA512_C`

**Comment by mpg** [comment]
I didn't notice there was a second CRL in that file (openssl only shows the first one without a hint that there are others). Anyway, it just so happens the the PEM error is detected before the second CRL can be parsed, so that SHA512 is not needed.

You're right however about the ECDSA dependency, and actually there are many other tests that have that undeclared dependency. I'm working on it.

**Comment by mpg** [comment]
After all I created IOTSSL-1388 for the ECDSA issue as this requires some work to be done properly, and doesn't seem urgent for this release (as opposed to the SHA1 part).

**Comment by mpg** [comment]
Please note that this branch is superseded by the first part of https://github.com/ARMmbed/mbedtls-restricted/pull/382 which adds scripts to test this kind of depend issue in a more systematic way.

**Comment by mpg** [comment]
Close as this is superseeded by ARMmbed/mbedtls-restricted#382

**Comment by gilles-peskine-arm** [comment]
https://github.com/ARMmbed/mbedtls-restricted/pull/382 will fix this in `development`. I'm reopening this PR and retargeting it to `mbedtls-2.7`.

**Comment by gilles-peskine-arm** [comment]
The same issue is present in 2.1, can you please make a PR with a 2.1 backport?

**Comment by mpg** [comment]
I would assume the issue in 2.1 to be fixed by this PR: https://github.com/ARMmbed/mbedtls-restricted/pull/457 Are you saying that it isn't?

**Comment by gilles-peskine-arm** [comment]
@mpg Ah, thanks, I hadn't located it in the backport, but it's present. Ok, we need one more reviewer for this one, and I need to do another pass to ensure the backports are complete. @mpg The backports are supposed to be complete at this point, right?

**Comment by mpg** [comment]
@gilles-peskine-arm It seems to me that this part of https://github.com/ARMmbed/mbedtls-restricted/pull/382 is included in the 2.7 backport https://github.com/ARMmbed/mbedtls-restricted/pull/456 (specifically [this commit](https://github.com/ARMmbed/mbedtls-restricted/pull/456/commits/483a776019543c74de7205988527dc6f72a41f46) fixes this particular issue in a more complete way than this PR) and the 2.1 backport https://github.com/ARMmbed/mbedtls-restricted/pull/457 (specifically [this commit](https://github.com/ARMmbed/mbedtls-restricted/pull/457/commits/57176e5cd594e9caf3f30f8e2be263bbf1b15a9e)).

So I believe this PR can be closed again and a separate backport for 2.1 is not needed.

**Comment by mpg** [comment]
@gilles-peskine-arm oops, I didn't see your last comment comment yet when I wrote the previous one.

"The backports are supposed to be complete at this point, right?" I would have replied "yes" five minutes ago but I just belatedly realised the backport add two new test scripts `tests/scripts/depend-{hashes,pkalg}.sh` (to `all.sh`) and I never ran those scripts (or `all.sh` on the backports) so far. I'm doing that right now and I'll report the results in the respective backports.

**Pull request closed without merging**
