### PR TITLE
Fix ECDHE-PSK-only build configuration

### PR DESCRIPTION
**Pull request by soundguy66**
Fixed Issue #270 and added a new configuration file and test to verify the fix.

### CODE REVIEW

**Comment by mpg** [comment]
Thanks! Looks good to me!

**Comment by miklis** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by mpg** [comment]
I'm sorry, we finally decided to take a different approach for the tests (we'll use a script to systematically test all configs with a single key exchange), so we won't need your config.h.

Thanks anyway for your contribution, I hope you understand.

**Comment by soundguy66** [comment]
Hi @mpg 

I think your solution to testing is better. I didn't have the time to propose such a significant change; I just needed a test to show exactly WHY I needed to delete line 254 of include/mbedtls/ssl_ciphersuites.h to allow compilation.

Are you still going to incorporate commit 05fbe18 which includes the actual fix?

Thanks,
-Chris

**Comment by mpg** [comment]
Yes, the fix is in branch "misc" which is pending review and should be integrated in our next release: https://github.com/ARMmbed/mbedtls/pull/325

This is a bit embarrassing, I kept confusing #270 and #310 as they are quite similar, so I thought there was no PR for #270 (there is none for #310) and fixed it myself... I still attributed it to you in the ChangeLog.

**Comment by mpg** [comment]
Closing, as #270 is now fixed.

**Pull request closed without merging**
