### PR TITLE
Error on removed options

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
If the compile-time configuration enables an option that was removed in Mbed TLS 3.0, and the effect of removing the option would likely not be detected at build time, `#error` out in `check_config.h`.

I didn't add `#error` clauses if the use of the feature would be detected at compile time. For example, if an application uses the test certificates that were formerly enabled by `MBEDTLS_CERTS_C`, it will fail to link, so no extra error detection is necessary.

### CODE REVIEW

**Comment by tom-daubney-arm** [comment]
I have done a quick review. Minor point in check_config.h Line 868: "See the ChangeLog **for** entry if you really need SHA-1-signed certificates."

Should the "for" be there? I was reading it as "See the ChangeLog entry if you..." which I thought maybe made more sense? But perhaps I am reading it wrong. Either way minor detail.

I have verified all of the links and can see they are good and so subject to CI passing I will approve this as soon as.

**Review by tom-daubney-arm — APPROVED** [review]
LGTM.

**Review by mpg — APPROVED** [review]
LGTM. Thanks for thinking about this!

**Comment by mpg** [comment]
The Travis run failed at git-clone time, so its failure is not indicative of a problem in this PR. The jenkins jobs are passing and I think it's enough to merge this PR.

**Pull request merged**
