### PR TITLE
Extend driver dispatch tests for MAC multipart

### PR DESCRIPTION
**Pull request by mprse**
## Description
- Split `mac_sign` test case into single and multi part test case,
- Split `mac_verify` test case into single and multi part test case,
- Extend multipart test cases to test different number of parts.

For 0 parts I generated result using online generator. Not sure if this is acceptable approach:
https://www.liavaag.org/English/SHA-Generator/HMAC/

All cases are run at least by the `component_test_psa_crypto_drivers`.

## Status
**READY**

## Requires Backporting
Yes
2.x: TBD

## Migrations
NO

### CODE REVIEW

**Review by AndrzejKurek — APPROVED** [review]
Looks all good. I also had problems finding test vectors with message lengths of 0.

**Comment by mprse** [comment]
`CI pr-merge` seems like hanged (pending) for a very long time. Also all is green. Not sure if this result can be considered as passed.

**Comment by mprse** [comment]
Rebased on `development` branch due to some problems with CI.

**Comment by mprse** [comment]
`The command "choco install python --version=3.5.4" failed and exited with 1 during .`

I got constantly the following CI error for windows build.

**Comment by gilles-peskine-arm** [comment]
I've seen choco install fail randomly before. It recently failed on https://app.travis-ci.com/github/ARMmbed/mbedtls/jobs/554887762 as well but passed on https://app.travis-ci.com/github/ARMmbed/mbedtls/builds/244535790. [The package still exists](https://community.chocolatey.org/packages/python/3.5.4). It should work if you update the branch.

I clicked the rerun button on this PR but it doesn't seem to have any effect. It used to be a known problem that the rerun button had no effect, but that was when we were on a legacy service plan, and now we're on a normal plan and I think it should work. I clicked the restart button on the job itself and [that is rerunning](https://app.travis-ci.com/github/ARMmbed/mbedtls/jobs/554887723).

**Review by AndrzejKurek — DISMISSED** [review]

**Review by minosgalanakis — DISMISSED** [review]
LGTM

**Comment by mprse** [comment]
@AndrzejKurek @minosgalanakis Sorry guys I had to rebase this PR on `development` to fix CI issue with `choco install`.

**Review by AndrzejKurek — APPROVED** [review]

**Review by minosgalanakis — APPROVED** [review]

**Pull request merged**
