### PR TITLE
EAP-TLS: Support for RCF 5216 to generate key_material

### PR DESCRIPTION
**Pull request by rohanghige**
- Added new macro MBEDTLS_SSL_EXPORT_KEY_MATERIAL to generate key_material
  and register pointer to key_material

### CODE REVIEW

**Comment by sbutcher-arm** [comment]
CLA requested in #809.

**Comment by sbutcher-arm** [comment]
This PR still doesn't have a CLA, so unfortunately we can't accept the code contribution.

@rohanghige - if you do join Mbed and/or sign and return a CLA, please feel free to re-open this PR.

**Comment by manuelgavidia** [comment]
@rohanghige - I am doing the same job as you did and I think the correct solution would be to support https://tools.ietf.org/html/rfc5705 .

The RFC 5705 expects that user could use the negotiated session PRF to derive new key material. So the solution could be to export a function with following signature/prototype: PRF(label, lenght). This function will use the negotiated master secret and random bytes without exposing them.

**Comment by RonEld** [comment]
@manuelgavidia Please note that we have raised a similar PR, in #2538 to export such keys.
We can't get contribution from @rohanghige because he hasn't accepted yet our CLA.

**Comment by manuelgavidia** [comment]
@RonEld thank you for your reply. I have some questions, but I will comment on your PR.

**Pull request closed without merging**
