### PR TITLE
Remove compat-1.3

### LINKED ISSUE #4112: Remove `compat-1.3.h`
The header file `include/mbedtls/compat-1.3.h` was meant to somewhat ease the transition from PolarSSL/Mbed TLS 1.3 to Mbed TLS 2.0 (especially as 100% of the public symbols were renamed to include an `mbedtls_` prefix).

It no longer makes sense to have it around in Mbed TLS 3.0.

### PR DESCRIPTION
**Pull request by mstarzyk-mobica**
compat-1.3.h was used for transition from 1.3 to 2.0. It's no longer needed in Mbed TLS 3.0.

Resolves #4112

### CODE REVIEW

**Comment by gilles-peskine-arm** [comment]
Please fix the typo `comapt` in the commit message so that `grep compat` finds it.

**Comment by mpg** [comment]
See also [this comment](https://github.com/ARMmbed/mbedtls/issues/4112#issuecomment-783331976) on the ticket (sorry for the moving target).

Also, should this have a ChangeLog entry? While hopefully no-one is still relying on `compat-1.3.h` nowadays, technically it's still an API change, so we might want to briefly mention it.

**Comment by mpg** [comment]
I think in order for the tests for pass you need to remove the corresponding include line from `programs/test/cpp_dummy_build.cpp`.

Also, it would be good to clean up the scripts in `tests/scripts` that used to exclude this file, because they no longer need to. Ideally, `git grep 'compat-1.*3` should return no result except ChangeLog entries.

**Review by mpg — CHANGES_REQUESTED** [review]
This looks good to me except two minor points:

1. The commit message should probably not say "TLS" as this was for the whole library, not just the TLS part.
2. Even if hopefully no-one was still using that, as a matter of principle we probably sill want a ChangeLog entry, for example "Remove helpers for the transition from Mbed TLS 1.3 to Mbed TLS 2.0: the header compat-1.3.h and the script rename.pl."

**Review by mpg — APPROVED** [review]
Thanks for addressing my feedback. Looks all good to me now!

Note: I believe the CI failures were due to yesterday's series of issues with the CI. However I'm not restarting the jobs now, as I'd rather save CI capacity for urgent PRs today (we have a merge freeze tonight for the next release) - we can restart those tomorrow instead.

**Review by yanesca — APPROVED** [review]
Checked that apart from the ChangeLog, there is no more occurrences of `compat-1.3`. LGTM

**Pull request merged**
