### PR TITLE
Update comment

### PR DESCRIPTION
**Pull request by damv**

### CODE REVIEW

**Comment by sbutcher-arm** [comment]
Thanks for the feedback! The reason the function was missed, is the name is actually misspelt and should have been `ctr_drbg_init()` not `ctr_crbg_init()`, so our renaming script missed the function, and unfortunately your fix is still wrong. Thanks anyway for raising the issue!

This has now been fixed in commit 295639b.

**Comment by damv** [comment]
Are you sure ? Because mbedtls_ctr_drbg_seed_entropy_len used to be called by the init function, but it is no longer the case. I think it is an other error in addition of the missing mbedtls prefix.

**Comment by sbutcher-arm** [comment]
Yes, you are quite right. I spotted your mistake in not correcting `crbg` to `drbg` which is why the script to update the functions with the new `mbedtls_` prefix missed the function, but missed that you'd changed the final word to seed. 

Now updated in commit 71c7ac5. Thanks for pointing out my mistake!

**Comment by damv** [comment]
I get your point now ! Thank's !

Le mer. 11 mai 2016 00:52, Simon Butcher <notifications@github.com> a
écrit :

**Pull request closed without merging**
