### PR TITLE
Fix build failure in tests when MBEDTLS_CHECK_PARAMS is enabled but MBEDTLS_ECP_RESTARTABLE isn't

### PR DESCRIPTION
**Pull request by hanno-arm**
__Summary:__ This PR fixes https://github.com/ARMmbed/mbedtls/issues/2329.

__Needs backports:__ Mbed TLS 2.16

### CODE REVIEW

**Comment by hanno-arm** [comment]
Rebased the PR on top of @gilles-peskine-arm's #2325. @mpg Could you please re-review?

**Comment by AndrzejKurek** [comment]
Unfortunately this PR has conflicts that must be resolved before merging.

**Comment by mpg** [comment]
Adding label "needs: backports" as the PR description says it does.

**Comment by tom-cosgrove-arm** [comment]
Closing this as `MBEDTLS_CHECK_PARAMS` was removed in 3.0, and the benefit to 2.28 wouldn't be worth the increased divergence from 3.0 if we just did this as a backport.

**Pull request closed without merging**
