### PR TITLE
[baremetal] MPS: Make record encryption/decryption standalone and add unit tests

### PR DESCRIPTION
**Pull request by mpg**
This is the side-port of https://github.com/ARMmbed/mbedtls/pull/1633 to the baremetal branch.

Most of the side-port is pretty obvious, except:

- there were some non-trivial conflicts due to refactorings in `ssl_derive_keys()` (I guess related to addind PSA-based MS derivation in development)
- I removed one commit that was about adapting a PSA code path

### CODE REVIEW

**Comment by mpg** [comment]
@k-stachowiak Since you're a reviewer on the base PR, do you think you could review this side-port as well? It would probably be more efficient than finding another reviewer who isn't familiar with the PR.

**Comment by k-stachowiak** [comment]
@mpg I will gladly do so, but because of non-trivial differences between this and the main PR, I will need some time, which, due to the upcoming holiday, I won't finish before this week.

**Comment by hanno-arm** [comment]
@k-stachowiak It's your choice how to review this, of course, but I'd recommend you do the rebase yourself and compare the results - there aren't too many conflicts.

**Comment by k-stachowiak** [comment]
@hanno-arm That sure is a good way to check if a PR is generally OK, however, I have witnessed git automatically messing code in a non-obvious way during a rebase (e.g. duplicating pieces of code, which was not detectable during tests), so I still prefer to look at the code, specifically for rebase screw-ups.

**Comment by hanno-arm** [comment]
@sbutcher-arm Please consider for merging.

**Comment by mpg** [comment]
Moving to https://github.com/ARMmbed/mbedtls-restricted/pull/562

**Pull request closed without merging**
