### PR TITLE
Backport 2.16: Fix several bugs with the value 0 in bignum

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Backport of https://github.com/ARMmbed/mbedtls/pull/4644.

The commit structure is the same as the main PR. Differences with the main PR:

* Several commits that tweaked existing testing had conflicts in the rebase due to modifying test functions or test cases that didn't exist in 2.16.
* In "Use mbedtls_test_read_mpi in test suites", there are extra replacement points in `test_suite_pkcs1_v21` where `mbedtls_mpi_read_string` was used in 2.16 but no longer in 2.26+.
* "Fix null pointer dereference in mbedtls_mpi_exp_mod" is different, with a patch in `mbedtls_mpi_exp_mod` and no change in `mbedtls_mpi_copy`. "Changelog for the fix to mbedtls_mpi_exp_mod(A=0)" is melded into the bug-fixing commit.
* I omitted "mbedtls_mpi_gcd: small optimization".
* The behavior of `mbedtls_mpi_read_string` on the empty string is not changing in 2.16.

Status: currently up-to-date with https://github.com/ARMmbed/mbedtls/pull/4644.

### CODE REVIEW

**Comment by mpg** [comment]
This has a conflict now.

**Comment by gilles-peskine-arm** [comment]
Another day, another rebase (same conflict as https://github.com/ARMmbed/mbedtls/pull/4644#issuecomment-865872990).

**Review by ronald-cron-arm — APPROVED** [review]
I've been through the rebase of #4644 on top of mbedtls-2.16(56efc52d6ba1ea39ca144fd5bb8e7aeab002303c) and with the help of the description of the differences between this backport and #4644 I've obtained the same final state but insignificant differences. I've also checked the last rebase. Finally I've checked that the changes to the library code (bignum.c) are limited to the bug fixes.

**Review by yanesca — APPROVED** [review]
Did the rebase of #4644 directly to 07941f45e6. Only found differences mentioned in the PR description.

**Comment by yanesca** [comment]
(Travis is a subset of Jenkins and Jenkins has passed.)

**Pull request merged**
