### PR TITLE
[Backport 2.x] Move base64 constant-time functions to the new module

### LINKED ISSUE #4926: Move base64 constant-time functions to the new module
https://github.com/ARMmbed/mbedtls/issues/3649 (PR: https://github.com/ARMmbed/mbedtls/pull/4866) moves constant-time functions to a new module. https://github.com/ARMmbed/mbedtls/issues/4814 (PR: https://github.com/ARMmbed/mbedtls/pull/4835) rewrites base64 constant-time functions. To allow the two to proceed in parallel, the base64 work will happen inside `base64.c` and the main constant-time PR not touch the base64 functions.

The goal of this task is to move base64 constant-time functions to the new module, once both https://github.com/ARMmbed/mbedtls/issues/3649 and https://github.com/ARMmbed/mbedtls/issues/4814 are resolved.

### PR DESCRIPTION
**Pull request by gabor-mezei-arm**
Backport of #5236 
No changes made to the original PR.

## Description
The goal of this task is to move base64 constant-time functions to the new constant-time module.

resolves #4926

### CODE REVIEW

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM - thanks!

**Review by mpg — CHANGES_REQUESTED** [review]
I'm happy with the backport, but the CI points out that in 2.x we need to update the generated files.

**Review by mpg — APPROVED** [review]
LGTM

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM

**Pull request merged**
