### PR TITLE
Backport 2.16: Add session ID as an explicit parameter to SSL session cache API

### PR DESCRIPTION
**Pull request by hanno-arm**
Backport of robustness fix from https://github.com/ARMmbed/mbedtls/pull/4347 to 2.16.

### CODE REVIEW

**Review by mpg — APPROVED** [review]
LGTM, just need to decide if this needs a ChangeLog (like the 2.x backport).

**Review by yanesca — CHANGES_REQUESTED** [review]
There is a CI failure on Travis, it might be just a glitch, but it needs to be investigated before we could merge.

**Comment by hanno-arm** [comment]
Added ChangeLog entry. @mpg @yanesca Could you please re-review?

**Comment by ronald-cron-arm** [comment]
@hanno-arm The CI is falling on this one, please have a look as this is blocking the merge of the 3 PRs.

**Comment by hanno-arm** [comment]
@mpg @yanesca This backport isn't as straightforward as assumed, since Mbed TLS 2.16 doesn't yet use `mbedtls_ssl_session_copy()` to load sessions that have been found in the cache. Instead, it only writes specific fields, with the remaining ones - including `compression` and `ciphersuite` - being kept from the target session. 

I don't feel comfortable changing this behaviour in the LTS branch, and, on second thought, am inclined to abandon the backports for #4347. After all, the added check only adds robustness for compliance.

What do you think?

**Comment by mpg** [comment]
Agreed, let's drop this.

**Pull request closed without merging**
