### PR TITLE
Remove PKCS#11 library wrapper.

### LINKED ISSUE #4078: Remove module: libpkcs11-helper
Remove the wrapper for PKCS#11 library libpkcs11-helper (library/pkcs11.c).

Deprecating this module was covered in #3006, and there is some mailing list discussion here:

https://lists.trustedfirmware.org/pipermail/mbed-tls/2020-April/000024.html

This forms part of #4030

Estimated task size: S

### PR DESCRIPTION
**Pull request by mstarzyk-mobica**
Resolves #4078

### CODE REVIEW

**Review by TRodziewicz — APPROVED** [review]
Looks OK for me.

**Review by mpg — DISMISSED** [review]
LGTM, but as Tomasz noted, there are conflicts to be resolved. Please resolve them either by merging current `development_3.0` into this branch or re-basing this branch on top of current `development_3.0`, whatever you prefer. (If you're happy both ways, I have a preference for rebasing in this instance as this is a single-commit, easy to review PR.)

**Review by TRodziewicz — APPROVED** [review]
Looks OK.

**Review by mpg — APPROVED** [review]
LGTM

**Pull request merged**
