### PR TITLE
Add export_public_key entry point for drivers

### PR DESCRIPTION
**Pull request by stevew817**
## Description
This PR plugs in support for calculating the public key from a private key through the accelerator driver model as defined by @gilles-peskine-arm.

## Status
**READY**

## Requires Backporting
NO

## Migrations
NO

## Todos
- [X] Tests
- [X] Documentation
- [x] Changelog updated

## Steps to test or reproduce
Tests added to regression suite.

### CODE REVIEW

**Comment by stevew817** [comment]
The lingering CI failure should be fixed now.

**Review by gilles-peskine-arm — APPROVED** [review]

**Comment by stevew817** [comment]
@gilles-peskine-arm rebased onto development and force-pushed.

**Review by paul-elliott-arm — DISMISSED** [review]
Looks good to me, however also looks like it will require a rebase first.

**Comment by gilles-peskine-arm** [comment]
This breaks the new configuration option `MBEDTLS_PSA_CRYPTO_CONFIG`. The new code needs different ifdefs.

**Comment by stevew817** [comment]
Argh. OK then.

**Comment by stevew817** [comment]
I guess I'd need to wait until #3830 lands and then rebase on top of that. Doesn't make sense otherwise.

**Comment by gilles-peskine-arm** [comment]
#3830 is merged.

**Comment by stevew817** [comment]
@gilles-peskine-arm @paul-elliott-arm rebased and using the new defines.

**Comment by gilles-peskine-arm** [comment]
I took the liberty of pushing some commits to fix issues noticed by the CI. Feel free to rebase them out.

**Review by gilles-peskine-arm — APPROVED** [review]

**Comment by stevew817** [comment]
Thanks!

**Review by paul-elliott-arm — APPROVED** [review]
Looks good to me (again!)

**Pull request merged**
