### PR TITLE
Remove deprecated things

### LINKED ISSUE #4029: Remove deprecated things
Remove code that is marked with MBEDTLS_DEPRECATED_WARNING or \deprecated.

### PR DESCRIPTION
**Pull request by TRodziewicz**
## Description

This PR aims in removing all deprecated functions and macros.

See "Additional comments" below

Fix #4029

## Status
IN DEVELOPMENT

## Requires Backporting
NO

## Additional comments

There are still unresolved issues inside marked as `// TODO [TR] for #4029` in the code which need to be worked on.

E.g. the tests made by `all.sh for cipher.ccm`, `cipher.chachapoly`, `cipher.gcm` and `cipher.nist_kw` don't work as they depend on `mbedtls_cipher_auth_[en|de]crypt()` which are used in `auth_crypt_tv()`. The former now have different list of parameters and I understand work differently then I guess the latter needs to be reworked. So for now those tests are blocked to allow CI.

I decided to create the PR anyway to show what exactly the issues are to larger group of people who may help here.

So reviews with comments are appreciated.

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

### CODE REVIEW

**Comment by TRodziewicz** [comment]
Failing tests:
```
RC4: both enabled ...................................................... FAIL
error: SSL - The server has no ciphersuites in common with the client
```
and
```
Encrypt then MAC: client enabled, stream cipher ........................ FAIL
error: SSL - The server has no ciphersuites in common with the client
```

**Comment by yanesca** [comment]
This PR removes RC4 support from TLS, tests testing explicitly RC4 should be removed as well:
- Any test in `ssl-opt.sh` that has `force_ciphersuite=` followed by a ciphersuite with RC4 in it
- Any RC4 option in `compat.sh`
- References to RC4 will be obsolete in `all.sh` as well (as they won't be present in `compat.sh` anymore
- The `arc4` option wouldn't work anymore and should be removed from the `ssl_client2.c` and `ssl_server2.c` programs
- Furthermore all references to the RC4 cipher should be removed from the SSL stack (that is `ssl_tls.c`, `ssl_srv.c`, `ssl_cli.c`, `ssl_msg.c`, `ssl_ciphersuites.c`)

**Comment by yanesca** [comment]
The difference between the old and the new `mbedtls_cipher_auth_encrypt()` is that the old outputs the authentication tag into a separate buffer and the new appends the it to the end of the output buffer.

Similarly the old `mbedtls_cipher_auth_decrypt()` expects the authentication tag in a separate buffer and the new one expects it to be appended to the end of the input buffer.

The corresponding tests need to be modified accordingly.

**Comment by yanesca** [comment]
Also, removing everything together is a pretty big change, could you please break it up into smaller commits? (Eg. all the RC4 related removals and changes could go into the same commit. The changes related to the `cipher_auth` functions to another one. The straightforward SSL option removals to yet another one, etc.)

**Comment by mpg** [comment]
Note: it seems like we failed to define the task well enough, some parts of it were already done elsewhere: https://github.com/ARMmbed/mbedtls/issues/4031 - resulting in duplicated work. I think we should wait until 4031 is completed and merged, then do #4278, then come back to this. Or actually even better, split #4029 in several tasks and execute those one by one.

**Comment by mpg** [comment]
I'm closing the PR since as it stands, it's conflicting with/duplicating other work (our fault, we should have defined the scope of the task better, sorry for that) and task it was addressing has been split into smaller, hopefully better-defined task, which should be each address by one PR (as Janos was already suggesting).

**Pull request closed without merging**
