### PR TITLE
library: Port to Haiku.

### PR DESCRIPTION
**Pull request by waddlesplash**
Pretty straightforward. All tests do pass, so this should be good for a merge.

### CODE REVIEW

**Comment by waddlesplash** [comment]
And just accepted the CLA.

**Comment by gilles-peskine-arm** [comment]
Hi @waddlesplash , we're willing to merge this in principle but we can't test with Haiku. If you're still interested, would you mind updating this PR so that it doesn't have any merge conflicts, and confirming that it works for you?

**Comment by waddlesplash** [comment]
@gilles-peskine-arm Sure. Pretty busy the next few days, but I'll get to it in the next week or so, I think.

**Comment by waddlesplash** [comment]
Gah, I broke the PR. Sorry, I'll make a new one.

**Comment by gilles-peskine-arm** [comment]
Continued in #1567

**Pull request closed without merging**
