### PR TITLE
Fix for #492 - mbedtls_x509_crt_parse_path() - the array char entry_name[255] is too small

### PR DESCRIPTION
**Pull request by pjbakker**

### CODE REVIEW

**Comment by sbutcher-arm** [comment]
Fixes #492.

**Comment by sbutcher-arm** [comment]
Rather than an arbitrary number of 512, wouldn't it be better to have a configurable constant in `config.h` which defaults to 512? The possible values for this field could get really big dependent on the application, and I think a 'one-size-fits-all' value would be too big for many embedded applications.

**Comment by pjbakker** [comment]
Agreed

**Comment by andresag01** [comment]
@sbutcher-arm: As you say in issue https://github.com/ARMmbed/mbedtls/issues/492 in the mbed TLS code, entry_name path/filename where filename is `entry->d_name`. Now, `entry` is a `struct dirent` and according to the documentation:

```
The only fields in the dirent structure that are mandated by POSIX.1 are: d_name[], of unspecified size, with at most NAME_MAX characters preceding the terminating null byte ('\0');
```

In other words, it seems that regardless of the size we give `entry_name` the `readdir()` will not return anything over 256 characters long. In my opinion, `entry_name` should be set to 256 instead of 255.

**Comment by pjbakker** [comment]
You forget that `entry_name` will contain the path + the filename.

**Comment by andresag01** [comment]
Ok, I see what you mean

**Comment by sbutcher-arm** [comment]
Fixed in pull request #592, so this pull request can be closed.

**Pull request closed without merging**
