### PR TITLE
Backport 2.1: Add various dependencies on ASN.1 parsing module 

### PR DESCRIPTION
**Pull request by hanno-arm**
This is the backport to Mbed TLS 2.1 of #2101, fixing #1531.

A notable difference is that in Mbed TLS 2.1, the RSA module was still partially dependent on ASN.1 parsing, hence commit e577beb had to be added which is not present in #2101 or #2102.

### CODE REVIEW

**Comment by sbutcher-arm** [comment]
Travis is failing:
```
The command "tests/scripts/check-names.sh" exited with 1.
0.66s$ tests/scripts/check-files.py
```
Therefore marking as 'needs work'.

**Comment by hanno-arm** [comment]
@sbutcher-arm Thanks for noticing this. Fixed in b46e733.

@mpg @AndrzejKurek Please review.

**Comment by sbutcher-arm** [comment]
retest

**Comment by sbutcher-arm** [comment]
Jenkins CI failed because of `doxygen.sh` which is a known issue and has been fixed in the head of `mbedtls-2.1`. Therefore CI is a pass.

**Pull request merged**
