### PR TITLE
Fixed a problem with mbedtls_write_real() returning incorrect length

### PR DESCRIPTION
**Pull request by dhhome2006**
## Description
This PR is to fix the #1707 problem.

When the user calls mbedtls_ssl_write() to send the application data, if ssl->out_left is greater than 0, it indicates that the previous data has not been completed. These old data must be sent out before sending new data. At this point, if the network gets better, the old data will be sent successfully, but unfortunately mbedtls_write_real() does not continue to send the new data, but directly returns the length of the new data.

We removed a "else" line in mbedtls_write_real() and avoided this problem.

When the network is unblocked, the problem will not appear. But when the network is congested or the system is busy, this problem will arise.

## Status
**READY**

## Requires Backporting
YES

Which branch?
the LTS branches

## Migrations
NO

## Additional comments
None

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
Outline the steps to test or reproduce the PR here.

### CODE REVIEW

**Comment by RonEld** [comment]
@dhhome2006 THank you for your contribution!

In addition, unfortunately our policy is to not accept contributions, without a Contributor’s Licence Agreement (CLA) signed or authorised by yourself or your employer.
If this is a personal contribution, the easiest way to do this is if you create an mbed account and [accept this click through agreement](https://os.mbed.com/contributor_agreement/). Alternatively, you can find a [slightly different agreement to sign here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/), which can be signed and returned to us, and is applicable if you don't want to create an mbed account or alternatively if this is a corporate contribution.
Thanks for your understanding and again, thanks for the contribution!

**Comment by dhhome2006** [comment]
@RonEld : I've signed up for an ARM account and accepted CLA. How can I connect it to my github account? Thanks!

**Comment by RonEld** [comment]
@dhhome2006 Unfortunately, there isn't a way to link your github account to your Mbed account. You can, however, in your Mbed settings share a link to your github account.
I believe that [this](https://os.mbed.com/users/dhhome2006/) is your Mbed account though.

**Comment by RonEld** [comment]
@dhhome2006 Why do you think this issue does not require backporting?
Bugs that are reproduced on the LTS(currently 2.1 and 2.7) branches should be fixed there as well. 
In addition, would you mind adding an entry in the ChangeLog and credit yourself?

**Comment by dhhome2006** [comment]
@RonEld  1)You're right, those LTS branches should also be fixed.  2)I didn't mind at all. :)

**Comment by RonEld** [comment]
Closing this issue, as it addresses same issue fixed in #1006 which is more mature.
If you think this PR was wrongfully closed, you may reopen.
Thank you for your interest in mbed TLS!

**Pull request closed without merging**
