### PR TITLE
Fix: "mbedtls_x509_crt_verify ignores max_pathlen on intermediate certificates"

### PR DESCRIPTION
**Pull request by yanesca**
Test cases for enforcement of constrains on the length of certification path are added, including the case in [#280](https://github.com/ARMmbed/mbedtls/issues/280). There is also a Readme file in the new certificate directory to make the tests more legible.

Also the implementation did not take in consideration the possible self signed certificates in the path. According to [rfc5280](https://tools.ietf.org/html/rfc5280#section-6): "self-issued certificates are not counted when evaluating path length or name constraints". 

This is also fixed. (The fix only affects the path length constraints: I neither did look up how this interacts with name constraints nor verified how the current implementation handles it)

This fixes [#280](https://github.com/ARMmbed/mbedtls/issues/280).

### CODE REVIEW

**Comment by miklis** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by mpg** [comment]
At first glance, this looks very good. Thank you very much for preparing all those test cases and documenting them!

Before we can merge your contribution, can you please get in touch with @sbutcher-arm or @pjbakker regarding our Contributor Licence Agreement (if you haven't signed it already)? Thanks!

**Comment by yanesca** [comment]
You are very welcome, I am glad I could help.

No, I did not sign a CLA yet. I sent an email to @sbutcher-arm already and I will try to contact @pjbakker on Monday if I do not get a reply until then.

**Comment by mpg** [comment]
Note for Simon: I reviewed the test certificates and can confirm they are OK for inclusion (freshly generated for this purpose).

**Comment by mpg** [comment]
@yanesca : I noticed your changes often have whitespace at the end of the line, which should be avoided. This is not a big problem, but in case you intend to do other contributions, could you please try to avoid that in the future? Thanks.

Otherwise, I just did another review, and everything looks good to me.

**Comment by mpg** [comment]
Added a few tune-ups in #337

**Comment by yanesca** [comment]
Thank you for noticing, I was not aware of this bad habit of mine. I will pay attention to it in the future.

**Pull request closed without merging**
