### PR TITLE
Fix and test the MBEDTLS_PSA_CRYPTO_SPM build

### LINKED ISSUE #4649: Missing include psa_crypto_service_integration.h in psa_crypto_mac.c
### Summary
In psa_crypto_mac.c file, it calls some psa crypto spec APIs, like 'psa_hash_setup', 'psa_hash_update'.
It will cause some errors when integration mbedtls with other project if not include 'psa_crypto_service_integration.h' header.
I think it is some for other psa_crypto_xxx.c files if it calls standards psa crypto apis.

### System information

Mbed TLS version (number or commit id):  development branch
Operating system and version: 
Configuration (if not default, please attach `config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information:

### LINKED ISSUE #4651: Check the build with PSA_CRYPTO_SPM on the CI
We don't check that the library builds with `PSA_CRYPTO_SPM` enabled, leading to bugs like https://github.com/ARMmbed/mbedtls/issues/4649.

Goal of this issue: to add a build with `PSA_CRYPTO_SPM` enabled to `all.sh`, in such a way that not including `psa_crypto_se.h` where it should be included will break the build.

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Fix the build with `MBEDTLS_PSA_CRYPTO_SPM` enabled: `crypto_spe.h` needs to be included first, but sometimes it wasn't. Fix #4649.

Supersedes #4650. Now with a test! Fix #4651.

Backport: [2.x](https://github.com/ARMmbed/mbedtls/pull/4715)

### CODE REVIEW

**Review by ronald-cron-arm — COMMENTED** [review]
LGTM but maybe better to add now to crypto_spe.h the new PSA APIs that we are about to support and have just added support for:
psa_mac_compute/verify, psa_cipher_encrypt/decrypt, psa_aead_encrypt_setup ...

**Comment by gilles-peskine-arm** [comment]
> better to add now to crypto_spe.h the new PSA APIs

I agree that it would be better but I don't want to get bogged down in this during the scramble for the release. Filed as https://github.com/ARMmbed/mbedtls/issues/4714 and hopefully we can do it properly (i.e. in a way that won't break each time we add a new function).

**Review by ronald-cron-arm — APPROVED** [review]
ok to go with #4714

**Review by tom-daubney-arm — APPROVED** [review]
LGTM - Thanks!

**Pull request merged**
