### PR TITLE
Backport 2.7: Enable on-target execution of Mbed TLS unit tests 

### PR DESCRIPTION
**Pull request by dgreen-arm**
Combined backport of #930 and #1991

### CODE REVIEW

**Comment by RonEld** [comment]
Please cherry-pick commit from https://github.com/ARMmbed/mbedtls/pull/2172

**Comment by RonEld** [comment]
Please cherry-pick also the commit from the following PRs:
* https://github.com/ARMmbed/mbedtls/pull/2208  ( merged already)
* https://github.com/ARMmbed/mbedtls/pull/2191
* https://github.com/ARMmbed/mbedtls/pull/2207
* https://github.com/ARMmbed/mbedtls/pull/2231

**Comment by RonEld** [comment]
I have edited my comments, striking through PRs that I have created backports my slef, and are not dependent on the On Target Tests scripts.

@dgreen-arm If you wish, I will cherry-pick these commits to this PR, or create new PRs on top of it.

**Comment by RonEld** [comment]
#2660 Also needs to be cherry picked here

**Comment by gilles-peskine-arm** [comment]
The 2.7 branch has reached its end of life, so I am closing this pull request.

**Pull request closed without merging**
